### ISSUE TITLE
Add Flows().Has validator

### ISSUE THREAD

**Issue by safchain** [skydive-project/skydive#100]
Currently the "Has" expression is sent directly to the agents or the storage. It could improve the performances to check that the expression matches the Flow definition before sending the request. So that the expressions not matching the flow definition or using a wrong type for the value will not be executed on each flow.

**Comment by nplanel** [comment]
Do you mean validate the type of the parameter data against the protobuf "schema" type ?

**Comment by safchain** [comment]
Yes exactly
