### ISSUE TITLE
Flatten Flow structure

### ISSUE THREAD

**Issue by safchain** [skydive-project/skydive#105]
Currently flows are made of embed structure for statistics, keeping a statistics per layer. The goal here is to flatten the flow structure to keep only one level of statistics. The will help to improve the performance. Moreover one packet will possibly generate more than one flow depending on the encapsulation. The flows generated could be linked.

**Comment by nplanel** [comment]
like this : 


enum FlowEndpointLayer {
  LINK = 0;
  NETWORK = 1;
  TRANSPORT = 2;
}

enum FlowEndpointType {
  ETHERNET = 0;
  IPV4 = 1;
  TCPPORT = 2;
  UDPPORT = 3;
  SCTPPORT = 4;
  IPV6 = 5;
}

message FlowEndpointStatistics {
  string Value 	= 2;
  uint64 Packets = 5;
  uint64 Bytes = 6;
}

message FlowEndpointsStatistics {
  FlowEndpointType Type = 1;
  FlowEndpointStatistics AB = 3; /* A->B */
  FlowEndpointStatistics BA = 4; /* B->A */
}

message FlowStatistics {
  int64 Start = 1;
  int64 Last = 2;
  FlowEndpointsStatistics Link = 3;
  FlowEndpointsStatistics Network = 4;
  FlowEndpointsStatistics Transport = 5;
}

message Flow {
  /* Flow Universally Unique IDentifier

    flow.UUID is unique in the universe, as it should be used as a key of an
    hashtable. By design 2 different flows, their UUID are always different.
    flow.UUID can be used as Database Index.
  */
  string UUID 			= 1;
  string LayersPath 		= 2;

  /* Data Flow info */
  FlowStatistics Statistics	= 3;

  /* Flow Tracking IDentifier, from 1st packet bytes

    flow.TrackingID could be used to identify an unique flow whatever it has
    been captured on the infrastructure. flow.TrackingID is calculated from
    the bytes of the first packet of his session.
    flow.TrackingID can be used as a Tag.
  */
  string TrackingID             = 5;

  /* Topology info */
  string ProbeNodeUUID	= 11;
  string IfSrcNodeUUID	= 14;
  string IfDstNodeUUID	= 19;
}

**Comment by safchain** [comment]
Yes a TrackingParentID could be useful for encapsulated packets

**Comment by nplanel** [comment]
updated

**Comment by safchain** [comment]
Would do some modification

enum FlowEndpointType {
  ETHERNET = 0;
  IPV4 = 1;
  TCPPORT = 2;
  UDPPORT = 3;
  SCTPPORT = 4;
  IPV6 = 5;
}

message FlowEndpointMetric {
  uint64 Packets = 5;
  uint64 Bytes = 6;
}

message FlowEndpoints {
  FlowEndpointType Type = 1;
  string Src = 2; 
  string Dst = 3;
}

message FlowEndpointsMetric {
  int64 Start = 6;
  int64 Last = 7;
  FlowEndpointMetric SrcDst = 8;
  FlowEndpointMetric DstSrc = 9;
}

message Flow {
  /* Flow Universally Unique IDentifier

    flow.UUID is unique in the universe, as it should be used as a key of an
    hashtable. By design 2 different flows, their UUID are always different.
    flow.UUID can be used as Database Index.
  */
  string UUID = 1;
  string LayersPath = 2;

  /* Data Flow info */
  FlowEndpoints Link = 3;
  FlowEndpoints Network = 4;
  FlowEndpoints Transport = 5;

  /* Data Flow Metric info from the 1st layer */
 /* amount of data between two updates
 FlowEndpointsMetric LastUpdateMetrics = 6;
 /* Total amount of data for the whole flow duration 
 FlowEndpointsMetric TotalMetrics =7;

 /* Flow Tracking IDentifier, from 1st packet bytes
    flow.TrackingID could be used to identify an unique flow whatever it has
    been captured on the infrastructure. flow.TrackingID is calculated from
    the bytes of the first packet of his session.
    flow.TrackingID can be used as a Tag.
  */
  string TrackingID             = 10;

  /* Flow Parent IDentifier is used as reference to the parent flow
   Flow.ParentID is the same value that point to his parent flow.TrackingID
  */
  string ParentID                = 11; 

  /* Topology info */
  string ProbeNodeUUID  = 12;
  string SrcNodeUUID  = 13;
  string DstNodeUUID  = 14;
}

**Comment by nplanel** [comment]
enum FlowProtocol {
  ETHERNET = 0;
  IPV4 = 1;
  TCPPORT = 2;
  UDPPORT = 3;
  SCTPPORT = 4;
  IPV6 = 5;
}

message FlowLayer {
  FlowProtocol Protocol = 1;
  string A = 2; 
  string B = 3;
}

message FlowMetric {
  int64 Start = 1;
  int64 Last = 2;
  uint64 ABPackets = 3;
  uint64 ABBytes = 4;
  uint64 BAPackets = 5;
  uint64 BABytes = 6;
}

message Flow {
  /* Flow Universally Unique IDentifier
    flow.UUID is unique in the universe, as it should be used as a key of an
    hashtable. By design 2 different flows, their UUID are always different.
    flow.UUID can be used as Database Index.
  */
  string UUID = 1;
  string LayersPath = 2;

  /* Data Flow info */
  FlowLayer Link = 20;
  FlowLayer Network = 21;
  FlowLayer Transport = 22;

  /* Data Flow Metric info from the 1st layer */
 /* amount of data between two updates
 FlowMetric LastUpdateMetric = 31;
 /* Total amount of data for the whole flow duration 
 FlowMetric TotalMetric = 32;

 /* Flow Tracking IDentifier, from 1st packet bytes
    flow.TrackingID could be used to identify an unique flow whatever it has
    been captured on the infrastructure. flow.TrackingID is calculated from
    the bytes of the first packet of his session.
    flow.TrackingID can be used as a Tag.
  */
  string TrackingID             = 5;

  /* Flow Parent UUID is used as reference to the parent flow
   Flow.ParentUUID is the same value that point to his parent flow.UUID
  */
  string ParentUUID                = 6; 

  /* Topology info */
  string ProbeNodeUUID  = 11;
  string SrcNodeUUID  = 14;
  string DstNodeUUID  = 19;
}

**Comment by nplanel** [comment]
http://softwarefactory-project.io/r/#/c/4793/

**Comment by nplanel** [comment]
http://softwarefactory-project.io/r/gitweb?p=skydive.git;a=commit;h=958a3bb518e56e1c0a987e6dfafcfb9a7508e07c
