### ISSUE TITLE
Group flows by Application in Discovery and Conversation views

### ISSUE THREAD

**Issue by lindhor** [skydive-project/skydive#1058]
In relation to #810 and #1020 it would also be nice to be able to show traffic grouped by Application in the Discovery and Conversation views.

Would it be hard to show the layer 4 "Application" also in the Discovery view (in a similar way as DNS is shown as a UDP layer 4 sector today)?

The same goes for the Conversation view. I think it would make sense to group defined layer 4 flows into a single column/row with Application name rather than port number (or possible be able to select if port numbers or Application names should be shown).

**Comment by safchain** [comment]
Closing these views have been deprecated
