### ISSUE TITLE
Create a topology API

### ISSUE THREAD

**Issue by lebauce** [skydive-project/skydive#1069]
With alerting, user metadata and the coming fabric API, there will be 3 ways to interact with the graph. We could share some code and even merge APIs:

Proposal:

Fabric case/user metadata:
skydive client topoloy create node --when <gremlin express + js> --metadata {...} [--type] [--name]
skydive client topoloy update node --when <gremlin express + js> --usermetadata (just a helper for UserMetadata.) --metadata {...} (just for specific namespace)
skydive client topoloy delete node --when <gremlin express + js> --metadata {...} 

skydive client topology create edge --edge <expression + JS> --source <expression + JS> --destination <expression + JS> --metadata {...}
skydive client topology update edge --edge <expression + JS> --source <expression + JS> --destination <expression + JS> --metadata {...}
skydive client topology delete edge --edge <expression + JS> --source <expression + JS> --destination <expression + JS> --metadata {...}

RBAC:
    - usermetadata write
    - metadata write
    - topology write
    - topology update

Action plan:

Take the gremlin matcher + JS out from the alerting to make availble from other components, so will be use by "register api" and alerting

**Comment by masco-enovance** [comment]
https://github.com/skydive-project/skydive/pull/1146
