### ISSUE TITLE
UDP flow from agent causes "message too long" logs

### ISSUE THREAD

**Issue by lindhor** [skydive-project/skydive#1086]
When I use udp as flow transport protocol I get the following message in the agent
```
2018-06-10T11:13:53.460Z    ERROR   analyzer/flow_client.go:156 (*FlowClient).SendFlow  skydive-roli-node1.beans.io: flows connection to analyzer error write udp 10.123.8.11:33670->10.123.8.11:8082: write: message too long : try to reconnect
```
Changing to web socket works fine (since it's tcp).

Anyone else who have the same issue and knows if it's a bug or something in the environment that causes this and can be fixed somehow?

**Comment by nplanel** [comment]
Hi @lindhor,


Thanks for your report

1/ Could you provide us the Skydive version that you used, please ?
2/ This error seems linke to the 64K UDP protocol limit, but shouldn't happen ... (as flow are less than 64K)
     do you use any gremlin query, with RawPackets() for example ?
  
3/ Is it possible to provide you a branch to test or a binary, aim to retrieve more info ?


Regards,

Nicolas

**Comment by lindhor** [comment]
Again, thanks for quick response. Attached are the two config files for agent and analyzer. Version used is master f10d3cb (but seen it earlier as well).
I am using raw packet capture initiated via the web gui using default parameters except a limit of 10 raw packets.
I would be very happy to try any test branch/binary you can provide. Unfortunately I will be out travelling from tomorrow and the next 2-3 weeks, but will be on it as soon as I'm back.
[skydive-conf-f10d3cb.zip](https://github.com/skydive-project/skydive/files/2088777/skydive-conf-f10d3cb.zip)

**Comment by safchain** [comment]
@lindhor Any news on this one ? Can we close it ?

**Comment by lindhor** [comment]
I am not aware that any fix has been provided for this yet. It might have been solved anyway but I’ve not been able to try the latest commits yet since I’ve been busy on another project. If you’re not able to reproduce it I would say close this issue since we are now using webservices.

**Comment by safchain** [comment]
@lindhor ok thanks, I close it. We will re-open if needed
