### ISSUE TITLE
Add netlink Statistics to nodes

### ISSUE THREAD

**Issue by safchain** [skydive-project/skydive#109]
Add Statistics returned by netlink to interface nodes so that we can get dropped packet number, etc...
This need to add an async mechanism to get metrics in order to have them updated.

**Comment by matrohon** [comment]
I see two possible go libraries to do that : 
- https://github.com/safchain/ethtool : to get stats with syscalls
- https://github.com/shirou/gopsutil/tree/master/net : to get stats from linux net/dev files

**Comment by safchain** [comment]
Something we have to take care is the way the library is implemented especially around the syscalls as we got issues with namespace and goroutine. Something fixed in ethtool lib but that doesn't mean this is the best choice.

**Comment by matrohon** [comment]
I'm currently playing with the ethtool lib, and indeed, I'm having issues with syscall. I was suggesting your ethtool lib to avoid another dependency. but it might be safer to use gopsutil that only poll net/dev files. BTW, should it be treated as a new probe?

**Comment by safchain** [comment]
I meant that ethtool is safe with namespaces, not sure about gopsutil. And yes it should be treated as another probe polling interface metrics. I'll have a look at gopsutil to be sure.

**Comment by safchain** [comment]
I had at quick look at gopsutil and indeed no namespace safe, so If we want to use it we will have to send some PR to fix it.

**Comment by safchain** [comment]
What kind of issue you have with ethtool ? maybe you could open an issue

**Comment by matrohon** [comment]
done : 
https://github.com/safchain/ethtool/issues/11

**Comment by safchain** [comment]
fixed: https://softwarefactory-project.io/r/#/c/6331/
