### ISSUE TITLE
k8s probe used directly kubernetes information as metadata leading in race condition

### ISSUE THREAD

**Issue by safchain** [skydive-project/skydive#1195]
Add kubernetes object as metadata leads in race condition as both can be read and write by the probe/graph and kubernetes client even if the graph is locked. 

Kubernetes client can modify structures that are in metadata outside of the graph lock control.

Even the common.NormalizeValue doesn't protect against this.

The solution could be to deep copy the kubernetes info before setting the metadata.

**Comment by safchain** [comment]
@hunchback could you have a look at it please ?

**Comment by hunchback** [comment]
Will look
