### ISSUE TITLE
Add support for multiple analyzers

### ISSUE THREAD

**Issue by safchain** [skydive-project/skydive#120]

**Comment by safchain** [comment]
Removing analyzer flow tables ? it seems not use to keep this behavior only the pipeline is useful

**Comment by nplanel** [comment]
For communication, why not relay deepstream.io (for example), it's kind of AMQP so flows messages could be _multicasted_

**Comment by safchain** [comment]
So for websocket we already have almost all in Skydive for forwarding/broadcasting message and I don't want to multicast flows but I want to shard them.

**Comment by safchain** [comment]
https://softwarefactory-project.io/r/#/c/5949/
