### ISSUE TITLE
Making map[string]interface{} data being foldable

### ISSUE THREAD

**Issue by ErwanAliasr1** [skydive-project/skydive#1288]
I'm currently trying to add hardware information as metadata and the output of my tooling generates some various data types including some map[string]interface{} ones.

These ones are not foldable using too much visual space.

![capture d ecran de 2018-09-11 10-45-45](https://user-images.githubusercontent.com/4539421/45348831-f50d6480-b5af-11e8-9223-08f9660eff1a.png)

This capture shows some "Capabilities" items not being foldable

**Comment by safchain** [comment]
Addressed by #1513
