### ISSUE TITLE
support catpture for ovs+dpdk

### ISSUE THREAD

**Issue by jonnary** [skydive-project/skydive#1299]
When use ovs+dpdk. We can't capture in vhu port
We can add kni interface and do mirror to do capture.

**Comment by safchain** [comment]
does it not work with ovs port capture ? I mean, did you try to start a capture on an OVS port. It will create a tap interface within the bridge and will set mirroring automatically. So that you should be able to see the traffic on the tap ?

**Comment by jonnary2018** [comment]
We have finished this work.

**Comment by lebauce** [comment]
Addressed by https://github.com/skydive-project/skydive/pull/716
