### ISSUE TITLE
flowtable_agent_ratio not applied correctly if agent started before analyzer

### ISSUE THREAD

**Issue by safchain** [skydive-project/skydive#131]
In that case default value is applied

to reproduce

1. start both agent and analyzer
2. create a capture
3. stop both agent and analyzer
4. start agent
5. start analyzer

to check : 
skydive client topology query --gremlin 'G.Flows().Bandwidth()'

The duration should be close to the ratio

Probably due to the fact that etcd update is not handled by the agent for ratio

**Comment by kdorfman** [comment]
Working on this

**Comment by kdorfman** [comment]
http://softwarefactory-project.io/r/4855
