### ISSUE TITLE
Document ENV

### ISSUE THREAD

**Issue by kbaegis** [skydive-project/skydive#1331]
Successfully deployed skydive on kubernetes. I'm looking for documentation on the available ENV variables. Specifically, I'm trying to enable additional topology probes with skydive_topology_probes.

**Comment by eranra** [comment]
You can take a look in https://github.com/IBM/charts/blob/master/stable/ibm-skydive-dev/templates/deployment-analyzer.yaml you will find nice set of  skydive env. variables that are used as part of the IBM Cloud Private Helm chart

**Comment by safchain** [comment]
fixed: http://skydive.network/documentation/deployment#configuration-environment-variables
