### ISSUE TITLE
Gremlin usage

### ISSUE THREAD

**Issue by kbaegis** [skydive-project/skydive#1342]
Probably merely a usage issue/question. Variants:
```
g.V().or(__.Has('Type','ovsport'),__.Has('Type','device'))
g.V().or(Has('Type','ovsport'),Has('Type','device'))
or(g.V().Has('Type','ovsport'),g.V().Has('Type','device'))
```
None of them return any nodes.

Desired result:
Filter will select or highlight both network interfaces and ovs ports excluding other virtual device types. 

How do I do this?

**Comment by safchain** [comment]
Skydive gremlin language doesn't support or step currently but you can do

G.V().Has('Type', Within('ovsport', 'device'))

**Comment by kbaegis** [comment]
Thanks! Works-for-me.
