### ISSUE TITLE
Avoid duplicate capture with exact same gremlin expression

### ISSUE THREAD

**Issue by safchain** [skydive-project/skydive#135]

**Comment by safchain** [comment]
It is possible to do

skydive client capture create --gremlin 'G.V().Has("Name", "vm1-eth0", "Type", "veth")'
skydive client capture create --gremlin 'G.V().Has("Name", "vm1-eth0", "Type", "veth")'
skydive client capture create --gremlin 'G.V().Has("Name", "vm1-eth0", "Type", "veth")'

which will create 3 captures

**Comment by kdorfman** [comment]
Fixed with http://softwarefactory-project.io/r/4919
