### ISSUE TITLE
Add Swagger

### ISSUE THREAD

**Issue by safchain** [skydive-project/skydive#1355]

**Comment by eranra** [comment]
Was thinking on https://goswagger.io/

**Comment by eranra** [comment]
Update: there is a nice way to expose swagger API for projects as github pages ... maybe there is a way to automatically generate this from Skydive golang code so this can be part of CI/CD and we will have the full Skydive API available to users .

@safchain @nplanel 

Link: https://peterevans.dev/posts/how-to-host-swagger-docs-with-github-pages/

Example of how it looks in the end: https://peter-evans.github.io/swagger-github-pages/

**Comment by lebauce** [comment]
Addressed by https://github.com/skydive-project/skydive/pull/1935

That should give us something like : https://lebauce.github.io/skydive.network/swagger/
