### ISSUE TITLE
Add a skydive standalone mode starting agent + analyzer at the same time

### ISSUE THREAD

**Issue by safchain** [skydive-project/skydive#136]
So that no need to start agent and analyzer to test Skydive. The idea is to do what is done for functional tests

**Comment by lebauce** [comment]
As the agent has to be started as root, `skydive standalone` would have to be started as root. It would fork, start the agent in the child and drop the root privileges in the parent to start the analyzer.

**Comment by safchain** [comment]
Fixed by http://softwarefactory-project.io/r/#/c/5067/
