### ISSUE TITLE
Backend does not support history

### ISSUE THREAD

**Issue by xhottam** [skydive-project/skydive#1384]
I'm trying to pick some data from "Skydive Grafana Datasource" but the listener always responds 

Possibly unhandled rejection: {"data":"Backend does not support history","status":400,"config":
{"method":"POST","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"api/datasources/proxy/1/api/topology","headers":
{"Content-Type":"application/json","X-Grafana-Org-Id":1,"Accept":"application/json, text/plain, */*"},"data":
{"GremlinQuery":"G.At(1539692226,300).V().Has('Name', 'eth0').Metrics()"},"retry":0},"statusText":"Bad Request"}
(https://github.com/skydive-project/skydive/blob/master/topology/graph/graph.go)

I'm using https://github.com/skydive-project/skydive/blob/master/contrib/openshift/skydive-template.yaml in 
oc v3.7.54
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

openshift v3.7.54
kubernetes v1.7.6+a08f5eeb62

The Analyzer ,from the WebUI, is capturing data like a charm. Is the data  going to etcd?. 
Having a look into elastic one, i don't see any movemnt in his logs, should the analyzer send data to elastic?
(http://skydive.network/documentation/#architecture)

**Comment by safchain** [comment]
Yes you need to specify a backend to store flow and metrics. Etcd is used for configuration Elasticsearch for everything about history.

You set it here:
https://github.com/skydive-project/skydive/blob/master/etc/skydive.yml.default#L69
https://github.com/skydive-project/skydive/blob/master/etc/skydive.yml.default#L76
https://github.com/skydive-project/skydive/blob/master/etc/skydive.yml.default#L305

**Comment by safchain** [comment]
Sorry I didn't see that you were using kubernetes deployment. We need to update the yaml file. We are going to work on a fix.

**Comment by safchain** [comment]
We just merged related fixes #1387, could try them, thanks

**Comment by xhottam** [comment]
Thanks for fixing it so fast.
