### ISSUE TITLE
Bug: the conversation and discovery function cannot diplay in  WebUI

### ISSUE THREAD

**Issue by Yo641-10** [skydive-project/skydive#139]
## Bug: the conversation and discovery function cannot be used in  WebUI

- when i inspected elements in chrome and firefox , i found the div element of topology ***included*** the div elements of   conversation and discovery and the display attribute of topology div  is None. 
- I' m a student  from peking University. Our lab want to use this project, can i have ur email or other contact?

**Comment by safchain** [comment]
Hi,

You can write on the mailing list: skydive-dev@redhat.com

**Comment by safchain** [comment]
fixed by
http://softwarefactory-project.io/r/#/c/4873/

**Comment by Yo641-10** [comment]
thanks.
