### ISSUE TITLE
compilation broken due to proteus and specific GOROOT, GOPATH setup

### ISSUE THREAD

**Issue by hunchback** [skydive-project/skydive#1394]
@safchain  I am getting the following since adding flow layers, this appears to be only on my host (based on fc28) please assist:

```
[vagrant@dev skydive]$ make flow/layers/generated.proto                         mv /home/vagrant/.skydive-build-tool bin || true; ln -s vendor src || mv vendor src; cd src/gopkg.in/src-d/proteus.v1/cli/proteus; (unset GOARCH; unset CC; GOPATH=$GOPATH/src/github.com/skydive-project/skydive go install gopkg.in/src-d/proteus.v1/cli/proteus); cd -; mv bin /home/vagrant/.skydive-build-tool; unlink src || mv src vendor;
/home/vagrant/src/github.com/skydive-project/skydive
proteus proto -f ${GOPATH}/src -p github.com/skydive-project/skydive/flow/layers
error scanning package "github.com/skydive-project/skydive/flow/layers": /home/vagrant/src/github.com/skydive-project/skydive/flow/layers/layers.go:25:8: could not import github.com/google/gopacket/layers (/home/vagrant/src/github.com/skydive-project/skydive/vendor/github.com/google/gopacket/layers/arp.go:11:2: could not import encoding/binary (/home/vagrant/.gimme/versions/go1.9.1.linux.amd64/src/encoding/binary/binary.go:26:2: could not import io (/home/vagrant/.gimme/versions/go1.9.1.linux.amd64/src/io/pipe.go:12:2: could not import sync (/home/vagrant/.gimme/versions/go1.9.1.linux.amd64/src/sync/cond.go:8:2: could not import sync/atomic (/home/vagrant/.gimme/versions/go1.9.1.linux.amd64/src/sync/atomic/value.go:31:37: cannot convert v (variable of type *Value) to /home/vagrant/.gimme/versions/go1.9.1.linux.amd64/src/unsafe.Pointer)))))
make: *** [Makefile:226: flow/layers/generated.proto] Error 1
```

This is the offending commit: https://github.com/skydive-project/skydive/commit/e8cf79963e5d85b203becdc290df2cd2c6f38195

The error message is:

```
/home/vagrant/.gimme/versions/go1.9.1.linux.amd64/src/sync/atomic/value.go:31:37: cannot convert v (variable of type *Value) to /home/vagrant/.gimme/versions/go1.9.1.linux.amd64/src/unsafe.Pointer
```

but when attempting to build under go build all is ok:

```
cd flow/layers
go build
```

Thus indicating that the issue is due to promious compilation.

NOTE: that on other build machines there are no apparent issues ...

**Comment by safchain** [comment]
did you try to remove $GOPATH/.cache $GOPATH/pkg ?

**Comment by lebauce** [comment]
```
rm websocket/structmessage.pb.go flow/*.pb.go filters/*.pb.go
make install
```

**Comment by hunchback** [comment]
@safchain / @lebauce - tried all what was recommended - but I still get the reported issue

**Comment by safchain** [comment]
@hunchback can you try to delete  /home/vagrant/.skydive-build-tool

**Comment by lebauce** [comment]
@hunchback Did you try to remove the `vendor` directory and do `git checkout vendor` ?

**Comment by hunchback** [comment]
i did a fresh git clone skydive.git which did not resolve issue

**Comment by nplanel** [comment]
did you try to use a new GOPATH
are you sure that you didn't break/alter your GOROOT ?  (reinstall golang package)

**Comment by hunchback** [comment]
when i revert to an older commit on master (prior to the 15th of October
all workas fine)

**Comment by safchain** [comment]
can you confirm that you tried with 

- reinstalling the protoc tooling ? binary + include
- a fresh or new golang install using another GOROOT ?
- a new empty GOPATH ?

I did install twice fresh environment this afternoon without any issue. I guess for you the best is to reboostrap a golang environment.

**Comment by hunchback** [comment]
i will check and get back on this ...

**Comment by hunchback** [comment]
I have managed to minimally reproduce the issue:

On the following file `$GOPATH/src/check.go`:

```
package check

import "unsafe"

var ptr *int

var uptr = unsafe.Pointer(ptr)
```

When running `go build` all is ok but when running:

```
[vagrant@dev check]$ pwd
/home/vagrant/src/check
[vagrant@dev check]$ ~/.skydive-build-tool/proteus proto -f /home/vagrant/src -p check
error scanning package "check": /home/vagrant/src/check/check.go:7:27: cannot convert ptr (variable of type *int) to /home/vagrant/.gimme/versions/go1.9.1.linux.amd64/src/unsafe.Pointer
[vagrant@dev check]$
```

**Comment by nplanel** [comment]
```
rm -rf /home/vagrant/.gimme
eval $(gimme 1.9.1)

```

**Comment by hunchback** [comment]
```
[vagrant@dev check]$ rm -rf /home/vagrant/.gimme
[vagrant@dev check]$ eval $(gimme 1.9.1)
go version go1.9.1 linux/amd64
[vagrant@dev check]$ proteus proto -f /home/vagrant/src -p check
error scanning package "check": /home/vagrant/src/check/check.go:4:28: cannot convert ptr (variable of type *int) to /home/vagrant/.gimme/versions/go1.9.1.linux.amd64/src/unsafe.Pointer
[vagrant@dev check]$ cat check.go
package check
import "unsafe"
var ptr *int
var uptr1 = unsafe.Pointer(ptr)
[vagrant@dev check]$
```

**Comment by nplanel** [comment]
```
rm -rf ~/.skydive-build-tool
cd ~/src/github.com/skydive-project/skydive
make clean
touch flow/layers/layers.go
make flow/layers/generated.proto
 ~/.skydive-build-tool/proteus proto -f /home/vagrant/src -p check

```

**Comment by lebauce** [comment]
@hunchback We discussed with @tomerlange about this. This seem to be related to the use VirtualBox shared folders. If I remember correctly, these should not be used by default on Windows (https://github.com/skydive-project/skydive/blob/master/contrib/dev/Vagrantfile#L17). Any idea ? Thanks !

**Comment by hunchback** [comment]
> rm -rf ~/.skydive-build-tool cd ~/src/github.com/skydive-project/skydive make clean touch flow/layers/layers.go make flow/layers/generated.proto ~/.skydive-build-tool/proteus proto -f /home/vagrant/src -p check

did not help ...

**Comment by hunchback** [comment]
> @hunchback We discussed with @tomerlange about this. This seem to be related to the use VirtualBox shared folders. If I remember correctly, these should not be used by default on Windows (https://github.com/skydive-project/skydive/blob/master/contrib/dev/Vagrantfile#L17). Any idea ? Thanks !

I am not using shared folders but still have the issue ..

**Comment by lebauce** [comment]
@hunchback Please check in the VirtualBox GUI (Settings / Shared folders) that there is no shared folder.

**Comment by hunchback** [comment]
@lebauce - I have no shared folders (I setup without the skydive shared folder due to performance issues and later I deleted the ansible shared folders)

**Comment by hunchback** [comment]
@lebauce - yesterday @eranra discovered that this issue is solved when installing Go directly (and not vie gimme) as follows:

```
wget https://dl.google.com/go/go19.1.linux-amd64.tar.gz
tar -xvf go1.9.1.linux-amd64.tar.gz
sudo rm -rf /usr/local/go
sudo mv go /usr/local

cat <<EOF >>.bashrc
export GOROOT=/usr/local/go
export PATH=\$GOROOT/bin:\$PATH
EOF
```

do we want to change `scripts/ci/install-go.sh` (as for now devmode is broken)

**Comment by lebauce** [comment]
@hunchback The problem comes from the fact that GOROOT is inside GOPATH (check my last comment on the issue). There is a PR that tries to fix the devmode with modifying `scripts/ci/install-go.sh`

**Comment by hunchback** [comment]
ok, great, then this issue can be closed
