### ISSUE TITLE
Inheriting the host when setting up ownership links

### ISSUE THREAD

**Issue by ErwanAliasr1** [skydive-project/skydive#1430]
I'm in a case where nodes are inherited from each other like 
host -> OSD -> PG -> RBD
When I set the "host->OSD" ownership link, the representation is fine.

When I set the OSD->PG ownership link, the host isn't inherited meaning the PG is not tied to the host leading to flying PGs like in https://imgur.com/a/EQM8qnJ 

So the other option, is to add an ownership link between host->PG + 1 extra link OSD->PG which works but makes the visual output very complex to read like in https://imgur.com/a/abS2M5f

So I suggest than once we put an ownership link between two nodes, the host property should be inherited avoiding having an extra link to keep this new node beeing attached to this host.

**Comment by safchain** [comment]
Closing, new WebUI will handle this
https://github.com/skydive-project/skydive-ui
