### ISSUE TITLE
Avoid graphing breakage when node ID features a dot

### ISSUE THREAD

**Issue by ErwanAliasr1** [skydive-project/skydive#1431]
Calling p.graph.NewNode("plop.1"), metadata) is breaking the graphing because the node ID have a dot inside its name.
That was pretty long for me to consider that was the root cause of my visual issues.
Would be cool to warn that or even fix it on the fly ?

**Comment by sergeyglazyrindev** [comment]
hello @ErwanAliasr1 
Could you please send me a json with your topology ? So I can reproduce it locally.

**Comment by safchain** [comment]
ids are used as html/css id and `.` are not allowed which causes javascript error.

**Comment by sergeyglazyrindev** [comment]
Does that make sense to try to fix that ? To be honest it should be pretty rare situation....

**Comment by sergeyglazyrindev** [comment]
If we need to fix that, then we can assign to node some autoincremented id. and add an attribute data-id to node svg g element with real node id, that helps to be able to search by node id, if there's any need.... 
What do you think ?

**Comment by safchain** [comment]
Not sure we need to fix that, warning should be enough, otherwiser I would simply replace special characters by "_", it should enough. but will need to change some other thing accessing the ID

**Comment by sergeyglazyrindev** [comment]
I disagree with you, it's better to keep data as is, instead of doing strange transformations. For instance, we may get duplicated node ids, for example: if there would be two nodes with ids: a_a and a__a
I think what I proposed much cleaner... imho.

**Comment by safchain** [comment]
My point was just to replace css ID not real ID, but I missed the fact that one can provide non-uuid ID. Anyway I think warning should be enough. ID should be something simple no need to handle special characters. But If there is simple way to fix this I'm fine too :)

**Comment by safchain** [comment]
Closing, new WebUI will handle this
https://github.com/skydive-project/skydive-ui
