### ISSUE TITLE
Extend flowTable to include flow life cycle (new flow 'status')

### ISSUE THREAD

**Issue by eranra** [skydive-project/skydive#1437]
On entrance of new flow to table, set flow field (status) to indicate 'NEW'
On new updates to flow set status to indicate 'UPDATE' (and reuse current updateVersion to track progress)
On expiration set status to 'FINISH' and sub_status to indicate 'EXPIRED' ... can be one field "FINISH_EXPIRED "
On finish recognition (for example in TCP, later for more protocols) set status to 'FINISHED' and sub_status to indicate 'SUCCESSFUL' ... can be one field "FINISHED_SUCCESSFUL"

**Comment by safchain** [comment]
Fixed : #1532
