### ISSUE TITLE
add support for perApplication (protocol) flowTable expiration time out

### ISSUE THREAD

**Issue by eranra** [skydive-project/skydive#1438]
allow users to specific in configuration a list (dictionary) of application Types (protocols, e.g. DHCP,DNS) and time out expiration values for those protocols. Typically much lower than the general flowTable expiration value. This allows quicker removal of flows that are known to be short by nature from the flowTable and no need to wait for the long expiration for general flows.

**Comment by hunchback** [comment]
I would recommend you merge:
- https://github.com/skydive-project/skydive/issues/1436
https://github.com/skydive-project/skydive/issues/1437
https://github.com/skydive-project/skydive/issues/1438

**Comment by eranra** [comment]
They are separate enhancements / PR's so we can discuss all but each PR will close an issue :-)

**Comment by safchain** [comment]
Fixed
