### ISSUE TITLE
Add infra and master to daemonset

### ISSUE THREAD

**Issue by git001** [skydive-project/skydive#1446]
I followed the commands on https://github.com/skydive-project/skydive/tree/master/contrib/openshift and was easily able to run the agent on compute nodes.

I have tried to add node labels to add infra nodes to the picture but the infra nodes doesn't shows in the graphical output.

Any hint how I can add the infra and the master nodes to skydive?

```
oc label node infranode1.$GUID.internal tier=agent app=skydive --overwrite

 oc get po -o wide
NAME                       READY     STATUS    RESTARTS   AGE       IP              NODE                  NOMINATED NODE
skydive-agent-6kqc7        1/1       Running   0          12m       192.199.0.195   node2.$GUID.internal   <none>
skydive-agent-mrzrl        1/1       Running   0          12m       192.199.0.123   node3.$GUID.internal   <none>
skydive-agent-t9qzd        1/1       Running   0          12m       192.199.0.150   node1.$GUID.internal   <none>
skydive-analyzer-1-7nqf7   2/2       Running   0          12m       10.1.12.51      node2.$GUID.internal   <none>


oc get node
NAME                       STATUS    ROLES     AGE       VERSION
infranode1.$GUID.internal   Ready     infra     23h       v1.11.0+d4cacc0
infranode2.$GUID.internal   Ready     infra     23h       v1.11.0+d4cacc0
master1.$GUID.internal      Ready     master    23h       v1.11.0+d4cacc0
master2.$GUID.internal      Ready     master    23h       v1.11.0+d4cacc0
master3.$GUID.internal      Ready     master    23h       v1.11.0+d4cacc0
node1.$GUID.internal        Ready     compute   23h       v1.11.0+d4cacc0
node2.$GUID.internal        Ready     compute   23h       v1.11.0+d4cacc0
node3.$GUID.internal        Ready     compute   23h       v1.11.0+d4cacc0

```

**Comment by lusoheart** [comment]
Hi,
I succeeded in deploying the skydive agent to other nodes than compute ones.
Besides the nodeselector on the daemonSet, I replaced the default node selector on the project by using this command:

`oc patch namespace skydive -p '{"metadata": {"annotations": {"openshift.io/node-selector": ""}}}'`

I'll also redeploy the daemonset by 

- exporting it
- changing the node selector on the exported yaml with a label that matches all nodes
- deleting the daemonset from the project 
-  redeploying the daemonset from the modified yaml by using oc create -f command

Hope that this can help you.

**Comment by git001** [comment]
Hi @lusoheart if this is the recommend way then it's perfectly okay for me. I will create a PR to add it into the doc

**Comment by git001** [comment]
Closed with this commit https://github.com/skydive-project/skydive/pull/1465
