### ISSUE TITLE
zoom view readbility

### ISSUE THREAD

**Issue by theonlydoo** [skydive-project/skydive#1452]
on a production host I encoutered this initial view on a staging cluster:
![o6tgia1vik8d0jv33frtrclrp](https://user-images.githubusercontent.com/1903124/48276196-bd078e00-e447-11e8-8fd0-6f22ed27cd1e.png)

which seems quite normal

but 

the real fun begins when you unfold a single host:
![woaq8szkn2czdokmomubbyxcd](https://user-images.githubusercontent.com/1903124/48276190-b842da00-e447-11e8-9a8e-d6856082d45d.png)

And it gets better as you zoom in
![q3a1kdfaj3pbsigtbi46rg4ek](https://user-images.githubusercontent.com/1903124/48276286-ef18f000-e447-11e8-9e1e-259a63de5937.png)

**Comment by safchain** [comment]
@theonlydoo indeed funny :) can you please describe a bit your environment ? docker ? kubernetes ? number of container ? network virtualization solution ?

**Comment by theonlydoo** [comment]
environment: 
- k8s 
container count
- 15@20
network:
overlay network w/ bgp (quagga)

**Comment by sergeyglazyrindev** [comment]
it seems like it is a legal case for my simplified topology approach. this is typical case for complicated topologies. @theonlydoo , do you have any ideas how to make it better ? what would be better solution for you ?

**Comment by theonlydoo** [comment]
@sergeyglazyrindev thank's for asking, design is not my strong suit but I think a progressive view like this:

# step1 
![skydive_view_proposal-base_view](https://user-images.githubusercontent.com/1903124/48836336-c3b8ce00-ed82-11e8-929f-0355000c0978.png)
# step 2 
![skydive_view_proposal-clicked_view](https://user-images.githubusercontent.com/1903124/48836346-c9aeaf00-ed82-11e8-922d-adac90a6dd99.png)

# step 3 
![skydive_view_proposal-expanded_clicked_view](https://user-images.githubusercontent.com/1903124/48836354-d3381700-ed82-11e8-90d9-e36fdd939979.png)

might come in handy.

The main readability issue comes from the display density, if you allow each NIC to be a clickable item, it already reduces the display layout.

**Comment by safchain** [comment]
Closing, new WebUI will handle this
https://github.com/skydive-project/skydive-ui

**Comment by theonlydoo** [comment]
thanks!
