### ISSUE TITLE
UI: Edged length not symmetrical in collapsed view  

### ISSUE THREAD

**Issue by eranra** [skydive-project/skydive#1458]
e.g. When opening Skydive UI (default infrastructure view), showing only the hosts, collapsed. The length of edges between hosts is not symmetrical if there is different amount of objects under each host (very typical). Single edge can be totally out of range creating very strange visualization. 

![image](https://user-images.githubusercontent.com/3080696/48404772-b45dd300-e739-11e8-8df3-f13271ccf548.png)

**Comment by sergeyglazyrindev** [comment]
Hello @eranra 
Could you please send me your skydive topology in json ? I'll hardcode it in javascript and try to reproduce it locally.

**Comment by safchain** [comment]
I think that is because a collapsed node has a huge amount of node regarding the other. There is something to push the node away if crowded in the code. I guess we can check if collapsed or not to calculate the weight.

BTW There is a way to inject the topology with the python lib

**Comment by sergeyglazyrindev-samsung** [comment]
> I think that is because a collapsed node has a huge amount of node regarding the other. There is something to push the node away if crowded in the code. I guess we can check if collapsed or not to calculate the weight.
> 
> BTW There is a way to inject the topology with the python lib

yes, I do think so but I think in my implementation this issue should disappear. That's why I am interesting about samples of data where I can see this issue.

**Comment by safchain** [comment]
Fixed: #1495 
Please re-open if needed
