### ISSUE TITLE
need to new release for ICP

### ISSUE THREAD

**Issue by hunchback** [skydive-project/skydive#1501]
please bump the version

**Comment by lebauce** [comment]
While I understand this is important for you, ICP is a seperate project. You should be able to create a version without relying on upstream releasing a version. We can't create a new release each time some external project/company ask for it.

**Comment by lebauce** [comment]
@hunchback By the way, we already decided to create a new release (tag v0.21.0 is already pushed, deliverables are on theiru way)

**Comment by hunchback** [comment]
> While I understand this is important for you, ICP is a seperate project. You should be able to create a version without relying on upstream releasing a version. We can't create a new release each time some external project/company ask for it.

agreed - we shall use commit checksum in future
