### ISSUE TITLE
Customize Flows handled by subscribers

### ISSUE THREAD

**Issue by orozery** [skydive-project/skydive#1588]
We want to allow a general mechanism that flow subscribers will use that will allow them to:
1. Remove fields from the Flow structs being sent to the subscriber.
2. Filter flows being sent to the subscriber (e.g. subscriber will only get flows that have Flow.FinishType != NOT_FINISHED).

I see a couple of potential places where you could place this filter & struct transformation code:
1. On a specific subscriber, e.g. the object store subscriber. This will couple the mechanism to a specific subscriber, not allowing other subscribers to re-use it.
2. On the flow server, before calling SendFlows, apply transformation & filtering. Each subscriber should be able to customize the exact transformation & filtering. Can we make this part of the subscription protocol?
3. Write a general "transformation & filtering" subscriber that will apply those transformations, then send them (via a direct interface function call, not via websocket) to the "true" subscriber, such as object storage. The object store subscriber (or other subscribers that want to use this mechanism) should be re-implemented to match this interface, instead of subscribing to the flows server.

@eranra @safchain @andrekassis

**Comment by eranra** [comment]
@orozery - thanks for adding this issue. I think that there is no doubt that from performance and efficiency point of view option 2. is most compelling but the flip of that is that this option limits the capabilities and complicates the subscription process .... 

@safchain @lebauce @nplanel waiting for your perspective on this issue
