### ISSUE TITLE
Allow passing metadata when querying nodes on the graph

### ISSUE THREAD

**Issue by lebauce** [skydive-project/skydive#159]
When doing a g.V().Has("Name", "docker0"), all the nodes are retrieved from the graph.
We could modify the graph method "GetNodes(t *time.Time)" to "GetNodes(t *time.Time, m Metadata)

**Comment by lebauce** [comment]
http://softwarefactory-project.io/r/#/c/5205/

**Comment by safchain** [comment]
fixed http://softwarefactory-project.io/r/#/c/5205/
