### ISSUE TITLE
SSL Issues

### ISSUE THREAD

**Issue by andrekassis** [skydive-project/skydive#1592]
We have been experimenting with Skydive while securing the analyzer-agent connection over SSL and we found ourselves facing these following issues:
1. Even when the mode of operation is not all-in-one Skydive won't start with TLS support unless both certificates for the client and agent  are provided. E.g.:
tls:
  client_cert: /path/to/client_cert.pem
  client_key: /path/to/client_key.pem
  server_cert: /path/to/server_cert.pem
  server_key: /path/to/server_key.pem
  ca_cert: /path/to/ca.pem
Note that when Skydive is started as an agent, we only need a client_cert and vice versa...

2. In etc/skydive.yml.default There are examples of certificate file names. These names end with .crt. However, our tests have revealed that .crt format is not supported and that Skydive only manages to parse .pem certificates.

3. this is probably the most important issue. We found out that there is a serious bug in the current implementation of the TLS protocol, as we use a function to translate the domain name representing the analyzer into its underlying IP address before verifying the certificate's authenticity. 
However, when the analyzer is given by it's domain name and not a fixed IP, which is the common case for various reasons (+certificates are most likely to be generated with CNs that are domain names rather than IP addresses that change very often), the  authentication process will fail because the IP addess won't match the CN on the certificate which is the domain name. We found out that not translating the hostname into an IP and leaving this task for the DNS server to perform solves this issue and allows for both domain names and IP addresses for analyzers. I will be introducing a PR with a simple fix of my own very soon. Please let me know what you think.

Cheers
@eranra

**Comment by nplanel** [comment]
@eranra 

Basically, we running a script in our CI to validate the TLS, please have a look scripts/scale.sh

 1/ the root ca_cert is used as based to generate all the certificate (root CA)

 2/ crt is supported but it's mandatory for skydive to have extension defined like extendedKeyUsage = serverAuth,clientAuth for exemple
   put logging to Debug could help a bit, but obviously TLS will not return the missing argument(s)/parameter(s) to set :)

 3/ you need to define the [alt_names] section to assign valid IP/FQDN in your certificate

Nicolas

**Comment by safchain** [comment]
Any news on this or can this be closed ?
