### ISSUE TITLE
Python API: noderule_list and edgerule_list don't work

### ISSUE THREAD

**Issue by nbratman** [skydive-project/skydive#1596]
both throw exception because they handle the REST response incorrectly.
response is a dictionary with uuids as keys and the noderule/edgerule dictionary as value.
both noderule_list and edgerule_list iterate over the outer dictionary keys rather than the values

what I tried to do:
![image](https://user-images.githubusercontent.com/26632729/51243498-68264d80-198b-11e9-80fd-3d6d59914026.png)

what I received:
![image](https://user-images.githubusercontent.com/26632729/51243520-770d0000-198b-11e9-97d0-e102d095517d.png)

**Comment by masco-enovance** [comment]
Hi, thanks for reporting the bug. the fix is available here https://github.com/skydive-project/skydive/pull/1597

**Comment by safchain** [comment]
Closing it as the fix is merged. Thanks
