### ISSUE TITLE
Hawkular as Database 

### ISSUE THREAD

**Issue by nplanel** [skydive-project/skydive#162]
http://www.hawkular.org/ is a graph and Metrics database, we can tags the insert like with nodeUUID and layerPath for example.
Could be an easy integration with Grafana
Hawkular is supported by Red Hat,   Joel working on he is based at Marseille

**Comment by safchain** [comment]
Closing it as it doesn't relevant for Skydive and we have a pretty nice Grafana integration. If needed we will re-open it.
