### ISSUE TITLE
Flow subscriber un-marshaling error

### ISSUE THREAD

**Issue by orozery** [skydive-project/skydive#1625]
Looks like PR #1593 broke the object store flow subscriber (and maybe flow subscribers in general?)

When trying to run the subscriber I'm getting:
2019-01-28T10:52:08.717+0200    ERROR   subscriber/objectstore.go:43 (*Subscriber).OnStructMessage      ubuntu: Failed to unmarshal flows:  proto: illegal wireType 7

@safchain

**Comment by safchain** [comment]
@orozery Thanks for reporting this, I'll have a look

**Comment by nplanel** [comment]
$< has been replaced/removed : https://github.com/skydive-project/skydive/pull/1593/files#diff-b67911656ef5d18c4ae36cb6741b7965L215

**Comment by orozery** [comment]
> $< has been replaced/removed : https://github.com/skydive-project/skydive/pull/1593/files#diff-b67911656ef5d18c4ae36cb6741b7965L215

What does that mean?
