### ISSUE TITLE
Shell fixup and rework

### ISSUE THREAD

**Issue by nplanel** [skydive-project/skydive#164]
Need to rework the completion at the 2nd stage. (rewrite the entire line)
1. if I enter G.V then tab it's not completing, but works for G.F
2. case insensitive works for G but not for other steps

**Comment by lebauce** [comment]
We could also allow the execution of JavaScript in the shell as we'll soon have JavaScript alerts

**Comment by nplanel** [comment]
use ebnf grammar format
