### ISSUE TITLE
DNS extra fields

### ISSUE THREAD

**Issue by andrekassis** [skydive-project/skydive#1642]
Hi Guys,
Following #1622 and after some more advanced research, we have come to realize now that the process in which flows are created ignores the most important fields in the DNS protocol. We introduce a patch in a new PR #1641 were we extract these fields and append them to the flows. The extra data we've added so far is not enough as it only displays the query and the answer, ignoring the authorities and other important fields. We would like to know what other fields you think are worth displaying.
Cheers

**Comment by safchain** [comment]
Fixed: #1641
