### ISSUE TITLE
Add a containerd (container runtime) probe

### ISSUE THREAD

**Issue by hunchback** [skydive-project/skydive#1654]
containerd has been adopted by k8s 1.10 as the default runtime:
https://kubernetes.io/blog/2018/05/24/kubernetes-containerd-integration-goes-ga/

And is now becoming default on k8s cluster solutions (IKS, ICP and OpenShift):
https://console.bluemix.net/docs//containers/cs_versions.html

so the request is:

(1)
To add containerd along side runC and docker:
https://github.com/skydive-project/skydive/tree/master/topology/probes/docker
https://github.com/skydive-project/skydive/tree/master/topology/probes/runc

(2)
To extend probe interface to support other than `Stop` and `Start` also `Query` to would check if the host can support the probe such that we now can enable `docker`, `runc` and `containrd` but only one probe will actually be started - according to the target platform:
https://github.com/skydive-project/skydive/blob/master/probe/bundle.go#L23

(3)
Optionally add to CI automatic building of optimized OCI containers:
https://github.com/skydive-project/skydive/blob/master/scripts/ci/create-docker-image.sh

**Comment by safchain** [comment]
1 - runC is not enough ? it has been tested with containerd and cri-o with success. Please see https://github.com/skydive-project/skydive/issues/1391

2. it is bit hard to detect what is the runtime used. It seems to me that is a deployment thing and should be part of the configuration. Docker and runc probe should work properly together (as least from what I tested)

3. makes sense

**Comment by hunchback** [comment]
> 1 - runC is not enough ? it has been tested with containerd and cri-o with success. Please see #1391
ok, in that respect do we have ci tests which setup various runtime environments?  should this be added such that we have:

```
scripts/ci/install-docker.sh
scripts/ci/install-runc.sh
scripts/ci/install-containerd.sh
```

And:

```
scripts/ci/run-docker-tests.sh
scripts/ci/run-runc-tests.sh
scripts/ci/run-containerd-tests.sh
```

And then we are able on the ci to check that the runc probe covers containerd needs.

**Comment by hunchback** [comment]
> 2 - it is bit hard to detect what is the runtime used. It seems to me that is a deployment thing and should be part of the configuration. Docker and runc probe should work properly together (as least from what I tested)

when skydive is packaged (such as k8s yaml, helm chart or OpenShift) you use a pre-defined configuration. This configuration should be able to handle some variation on targets such as k8s ranging in version (1.9 using the docker runtime  / 1.10 using the containerd runtime) - while it is possible to expose a configuration parameter  - that is error prone - the better solution is query - such as for docker checking the `/var/run/docker.sock` exists ...

**Comment by safchain** [comment]
We do have a test for runC here: https://github.com/skydive-project/skydive/blob/master/tests/runc_test.go
As containerd is only using runC to start containers, I think the difference between containerd environment and podman/runc/etc. environments are almost only the path of the state files.

Checking docker socket is currently not a way to detect if docker is there or not. I saw a lot a differences between runC environment a cross distribution and the way the environment is deployed (ansible, etc.). Do you have an idea on how we could handle this ?

**Comment by lebauce** [comment]
> ok, in that respect do we have ci tests which setup various runtime environments? should this be added such that we have:
> 
> ```
> scripts/ci/install-docker.sh
> scripts/ci/install-runc.sh
> scripts/ci/install-containerd.sh
> ```

I don't understand. We don't need to have a dedicated script to have a package installed. We have ansible playbooks to setup on CI machines and `docker`, `runc` and installed using them.

> 
> And:
> 
> ```
> scripts/ci/run-docker-tests.sh
> scripts/ci/run-runc-tests.sh
> scripts/ci/run-containerd-tests.sh
> ```
> 
> And then we are able on the ci to check that the runc probe covers containerd needs.

In the same way that we don't have run-openvswitch-tests.sh, run-lxd-tests.sh, etc...., we don't need to have a dedicated script for a set a tests. The `-run` flag of `go test` can be used for this. In our case, we case tests like `TestDockerSimple`, `TestRuncSimple` that test Docker and runc support.

**Comment by hunchback** [comment]
> > ok, in that respect do we have ci tests which setup various runtime environments? should this be added such that we have:
> > ```
> > scripts/ci/install-docker.sh
> > scripts/ci/install-runc.sh
> > scripts/ci/install-containerd.sh
> > ```
> 
> I don't understand. We don't need to have a dedicated script to have a package installed. We have ansible playbooks to setup on CI machines and `docker`, `runc` are installed using them.
> 
> > And:
> > ```
> > scripts/ci/run-docker-tests.sh
> > scripts/ci/run-runc-tests.sh
> > scripts/ci/run-containerd-tests.sh
> > ```
> > And then we are able on the ci to check that the runc probe covers containerd needs.
> 
> In the same way that we don't have run-openvswitch-tests.sh, run-lxd-tests.sh, etc...., we don't need to have a dedicated script for a set a tests. The `-run` flag of `go test` can be used for this. In our case, we case tests like `TestDockerSimple`, `TestRuncSimple` that test Docker and runc support.

ok

**Comment by hunchback** [comment]
> We do have a test for runC here: https://github.com/skydive-project/skydive/blob/master/tests/runc_test.go
> As containerd is only using runC to start containers, I think the difference between containerd environment and podman/runc/etc. environments are almost only the path of the state files.
> 
> Checking docker socket is currently not a way to detect if docker is there or not. I saw a lot a differences between runC environment a cross distribution and the way the environment is deployed (ansible, etc.). Do you have an idea on how we could handle this ?

maybe by using a programmatic equivalent to: 

```
[vagrant@dev skydive]$ sudo systemctl is-active docker
active
```

**Comment by hunchback** [comment]
the main requirement has been met by the runC probe; automatic discovery (of which probes exist) is a much larger feature not being address for now.
