### ISSUE TITLE
Add native ovn probe without neutron

### ISSUE THREAD

**Issue by bwesemann** [skydive-project/skydive#1655]
is this possible? like ovs?

**Comment by safchain** [comment]
I would say everythin is possible :) The current ovs probe if working without neutron. What kind of information you would like to report ?

**Comment by safchain** [comment]
Ok thanks for the inputs. I put a label to track this and we will work on it

**Comment by bwesemann** [comment]
wow perfect!

**Comment by lebauce** [comment]
@bwesemann We just pushed a PR https://github.com/skydive-project/skydive/pull/1680 that adds  a basic OVN probe to Skydive. That would be really appreciated if you could give it a look.

**Comment by lebauce** [comment]
@bwesemann By the way, can you share the context of what you would like to do with Skydive and OVN ?

**Comment by bwesemann** [comment]
wow nice. 
can you please assist me?
is this right?
git clone https://github.com/lebauce/skydive
git checkout -b ovn-probe
git pull origin ovn-probe

**Comment by lebauce** [comment]
@bwesemann Sure. http://skydive.network/documentation/build#installation describes the process for Fedora and Ubuntu. We also are on IRC if you have any issue. Thanks

**Comment by bwesemann** [comment]
with the commands above i get the following error:

/usr/local/src/go/src/github.com/skydive-project# make
CC= GOARCH= go get github.com/kardianos/govendor
/usr/local/src/go/bin/govendor sync
patch -p0 < dpdk/dpdk.govendor.patch
patching file vendor/github.com/intel-go/yanff/low/low.go
rm -rf vendor/github.com/weaveworks/tcptracer-bpf/vendor/github.com/
mv /usr/local/src/go/.skydive-build-tool bin || true; ln -s vendor src || mv vendor src; cd src/gopkg.in/src-d/proteus.v1/cli/proteus; (unset GOARCH; unset CC; GOPATH=$GOPATH/src/github.com/skydive-project/skydive go install gopkg.in/src-d/proteus.v1/cli/proteus); cd -; mv bin /usr/local/src/go/.skydive-build-tool; unlink src || mv src vendor; proteus proto -f ${GOPATH}/src -p github.com/skydive-project/skydive/flow/layers
can't load package: package gopkg.in/src-d/proteus.v1/cli/proteus: cannot find package "gopkg.in/src-d/proteus.v1/cli/proteus" in any of:
        /usr/lib/go-1.10/src/gopkg.in/src-d/proteus.v1/cli/proteus (from $GOROOT)
        /usr/local/src/go/src/github.com/skydive-project/skydive/src/gopkg.in/src-d/proteus.v1/cli/proteus (from $GOPATH)
/usr/local/src/go/src/github.com/skydive-project
stat /usr/local/src/go/src/github.com/skydive-project/skydive/flow/layers: no such file or directory
Makefile:243: recipe for target 'flow/layers/generated.proto' failed
make: *** [flow/layers/generated.proto] Error 1

**Comment by lebauce** [comment]
@bwesemann What distribution are you using ?

**Comment by bwesemann** [comment]
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

**Comment by lebauce** [comment]
@bwesemann I just tried with a fresh ubuntu container `docker run -ti ubuntu:bionic` and copy pasted the commands of the documentation (without `sudo`). The `make` was successful. Is it a VirtualBox VM ? Could you try with a different $GOPATH (such as $HOME/go) ?

**Comment by bwesemann** [comment]
git clone https://github.com/skydive-project/skydive.git $GOPATH/src/github.com/skydive-project/skydive

thats working, but how do i get your pull request?
thanks

**Comment by lebauce** [comment]
```
cd $GOPATH/src/github.com/skydive-project/skydive
git remote add https://github.com/lebauce/skydive
git checkout lebauce/ovn-probe
```

**Comment by bwesemann** [comment]
i've got it.

thank you!

![ovn](https://user-images.githubusercontent.com/31445348/54287696-7321e680-45a6-11e9-8ef9-ed83d8cb81a5.png)

is it possible to draw a line between the vm port and logical switch port? and on the next step a link between the logical switches and router?

best regards

**Comment by lebauce** [comment]
@bwesemann The screenshot says it's version 0.18 (which is 6 months old) and I don't see any OVN objects (only OVS objects). Can you make sure you are on the right git branch ? (`git log`). Once the correct version is compiled, you also need to enable the probe on the analyzer (section `analyzer.topology.probes`)

**Comment by lebauce** [comment]
@bwesemann My bad, it says `Analyzer 0.18.0-5512d798ca97`, the commit `5512d798ca97` seems to be the right one but the `0.18.0` part is wrong. So there must be something wrong with the way we show the version.

Right now, the probe is really trivial : it collects the OVN logical switches, logical ports and ACL and create Skydive nodes for them. It also creates links between the logical switches and their ports (same for ACL)s.

It will be indeed very interesting to create a link between the OVS port and the OVN logical port. I will investigate this.

What do you mean by `between the logical switches and router` ? You mean a link between an OVN logical switch and its respective OVS bridges ?

**Comment by bwesemann** [comment]
i mean in ovn you can have logical routers as well. 
from south to north this means:
the logical switch have a logical switch port called 'intra-router-port' this one connects to a logical router called 'router1'.

on this router there are some routes defined on the logial router ports.
this router then is connected to another switch called 'transit' and this switch have a link to another router which is the external gateway router. On this router is snat configured. 

and the last one is a switch called 'external'. on this switch are the logical switch port mappings to the ovs external bridges -> l3 gateways.

additionally on another logical switch called 'dmz' is a l2 breakout defined. this is also a mapping to a ovs bridge.

**Comment by lebauce** [comment]
@bwesemann I reworked my PR to add a few things : more attributes for OVN objects, logical routers, links between logical switches and logical ports, links between the OVN port and the OVS interfaces.

Using the setup described here http://blog.spinhirne.com/2016/09/an-introduction-to-ovn-routing.html, you should get something like https://pasteboard.co/I88aEIt.png

I would really appreciate if you could give it a try

**Comment by bwesemann** [comment]
hi,
sorry for the late answer. i hope i can test it this or next week

**Comment by lebauce** [comment]
No problem. Thank you

**Comment by bwesemann** [comment]
![Screenshot_20190416_095411](https://user-images.githubusercontent.com/31445348/56192039-cec01380-602d-11e9-803c-26daed90291c.png)
this is a big step forward :)

can you add the following?
- link vm ovs port with ovn port
- link between the geneve/tunnel ports
- change the icons for ovn switch and router

let me know if you need any more info or help

best regards
Ben

**Comment by bwesemann** [comment]
and a link between the localnet port and the ovs port
maybe display the nat rules on the gateway router
and if somehow is possible display the current l3gateway

thanks

**Comment by bwesemann** [comment]
hi,

whats the status? do you need more infos or help?

br
ben

**Comment by bwesemann** [comment]
any news?

**Comment by bwesemann** [comment]
could you please give me an status update?

**Comment by lebauce** [comment]
@bwesemann I'm sorry for taking so long. Unfortunately, Red Hat decided to stop investing in Skydive so I can't give you any roadmap, sorry.

**Comment by lebauce** [comment]
An OVN probe was implemented and is being improved by @amorenoz
