### ISSUE TITLE
Tagging of Helm chart in IBM Cloud Kubernetes Service: solution tab

### ISSUE THREAD

**Issue by vwilburn** [skydive-project/skydive#1656]
I'm exploring the Solution tab for all the Helm charts. I'm seeing a mismatch when I use the `IBM Cloud Kubernetes Service` filter and the chart's readme. For example, the Skydive chart says it's only for ICP, but it shows up in the filtered view when I select `IBM Cloud Kubernetes Service`. 

https://console.bluemix.net/containers-kubernetes/solutions/helm-charts/ibm-charts/ibm-skydive-dev

**Comment by nplanel** [comment]
@eranra

**Comment by eranra** [comment]
@nplanel thanks
@vwilburn, I sent you mail + @hunchback should be in the loop

When this will resolve it will be good to float the information here (into this issue) before closing.

**Comment by hunchback** [comment]
@vmilburn - handled and will be addressed in our next release (regardless this is an IBM not a community issue) - you can close this ticket now. thanks!

**Comment by vwilburn** [comment]
@hunchback  Would you mind including the internal GH issue link for future reference?
