### ISSUE TITLE
Fabric from environment variable 

### ISSUE THREAD

**Issue by eranra** [skydive-project/skydive#1677]

**Comment by eranra** [comment]
When configuring fabric using SKYDIVE_ANALYZER_TOPOLOGY_FABRIC, for example "TOR1->*[Type=host]/eth0" the analyzer do not start and log "Fabric configuration should be a list of entries"

This started post the commit  https://github.com/skydive-project/skydive/commit/b762f2b4c23f16dd6ef29f35e1ca54724796607d#diff-8b4b9d729a1da4e230b1b3002a9485ca

@lebauce @hunchback

**Comment by eranra** [comment]
We tried:

SKYDIVE_ANALYZER_TOPOLOGY_FABRIC='{"item1":"TOR1->*[Type=host]/eth0"}' ~/go/bin/skydive 
analyzer

and 

SKYDIVE_ANALYZER_TOPOLOGY_FABRIC="[\"TOR1->*\[Type=host\]/eth0\"\]"  ~/go/bin/skydive analyzer

and got:

Failed to create analyzer: Fabric configuration should be a list of entries

**Comment by lebauce** [comment]
Addressed by https://github.com/skydive-project/skydive/pull/1713
