### ISSUE TITLE
how to add ovs oflow enable option in the k8s yaml file

### ISSUE THREAD

**Issue by winsopc** [skydive-project/skydive#1681]
I tested on my k8s with daemonset,  works fine after I added ovsdb probes,  but I cannot see the flows, I suspect the oflow bydefault is disable,  I only the vagrant file has enable it,  I wonder how to enable it in the yaml for k8s, anyone has idea?

**Comment by hunchback** [comment]
Please see the following example: https://github.com/skydive-project/skydive/blob/master/contrib/kubernetes/skydive.yaml

As skydive accepts environment variables as an alternative to configuration file the above example make use of SKYDIVE_AGENT_TOPOLOGY_PROBES 

And to enable probe ovsdb just append it to this env variable within the k8s yaml file

**Comment by lebauce** [comment]
So to enable the flows, you should define an environment variable named "SKYDIVE_OVS_OFLOW_ENABLE" with the value "true". @winsopc Could you please confirm that it works ? Thanks !
