### ISSUE TITLE
mirror interface not removed after capture deleted

### ISSUE THREAD

**Issue by wat101** [skydive-project/skydive#1708]
I created a capture between two VMs located on two hypervisors. As soon as I click "Start" button, there're 100 mirror interfaces created on the source hypervisor.  After I delete the capture, there're still 31 mirror interfaces left.  However, if I created a capture between 2 VMs on same hypervisor, only 2 mirror interfaced created, and both removed correctly after capture deleted.

The connection between 2 VMs on two hypervisors looks like below.

vm1 -- hypervisor1 -- tor1 -- spine -- tor2 -- hypervisor2  -- vm2

After capture created
```
# ip a | grep mir | wc -l
100
```
After capture deleted
```
# ip a | grep mir | wc -l
31
```
Skydive & OS version
```
# ./skydive version
./skydive github.com/skydive-project/skydive 0.21.0-c0dfd6ed04a7
# hostnamectl
   <...output omitted...>
  Operating System: Red Hat Cloud Infrastructure
       CPE OS Name: cpe:/o:redhat:enterprise_linux:7.6:GA:server
            Kernel: Linux 3.10.0-957.1.3.el7.x86_64
      Architecture: x86-64
```

**Comment by safchain** [comment]
addressed by #1719

**Comment by wat101** [comment]
I downloaded the latest binary, and tried to create a capture between 2 VMs on two hypervisors. Now I get below error message says from the small yellow triangle:

**This capture doesn't currently match any node** 

Please check there is a Layer 2 link in case of 2 nodes capture

```
#/bin/skydive version
/bin/skydive github.com/skydive-project/skydive 0.22.0-477be583e8e2
```

**Comment by safchain** [comment]
That is the expected behavior. By default a capture between two node from the web ui only follow L2 link and there is no L2 link between the VMs. It was a bug to allow this before. I would suggest to make two captures.

**Comment by lebauce** [comment]
Please reopen if the fix does not work as attended.
