### ISSUE TITLE
Dashboard - Can't see applications running on a single host

### ISSUE THREAD

**Issue by ahrennsiva** [skydive-project/skydive#1721]
I have an AWS EC2 instance on which I installed the All In One agent. Within this host, I'm running a Flask server, a proxy server (routes to Flask server), and another application which is used to send requests rapidly to the proxy server.

I want to see within my Skydive dashboard the Flow capture from my application sending requests to the Flask server (with the multihop path through the proxy server ideally), but at the moment none of these local applications on my EC2 instance are visible on my Skydive dashboard.

Are these meant to be automatically detected, or is there something I'm missing regarding making these localhost applications visible as nodes in the dashboard that I can monitor flows for?

**Comment by hunchback** [comment]
Skydive has no notion of "application", but if your services were containerized (docker, containerd or runC) then these would have an associated graph node.

If you decided to go that route then you need to enable agent probes: docker or runc (which also tracks containerd).
