### ISSUE TITLE
Questions about Skydive using OrientdDB

### ISSUE THREAD

**Issue by quangtamle** [skydive-project/skydive#1738]
Hi Everyone,

I deployed a small lab with Skydive and OrientdDB. I want Skydive to store its data in OrientDB, How can I do ??? Is there any idea ???

Thank you in advances

**Comment by lebauce** [comment]
@quangtamle Hi. To use OrientDB as a Skydive datastore for topology, you need to set the `analyzer.topology.backend` key to `orientdb` (https://github.com/skydive-project/skydive/blob/master/etc/skydive.yml.default#L82) and the `analyzer.flow.backend` key to `orientdb` (https://github.com/skydive-project/skydive/blob/master/etc/skydive.yml.default#L75)

**Comment by quangtamle** [comment]
Dear @lebauce 

Thank you for your instruction !!!

Now I can connect Skydive with OrientDB . I can see the traffic between them, then I log into the DB, I query for data but nothing there. Do you know what the problem is ????

**Comment by lebauce** [comment]
@quangtamle Would you mind copy/pasting your configuration file ? If it works correctly, you should see a database called "Skydive". Can you see it ?

**Comment by quangtamle** [comment]
Hi @lebauce 

I can query the information from the DB. The reason is I have to create the Skydive DB first before deploying Skydive, otherwise it didnt work.

By the way, is there any way to hide password in YALM or YML file ??? I mean password (of the DB) should not be in the plain text.

apiVersion: v1
kind: ConfigMap
metadata:
  name: skydive-analyzer-config-file
data:
  skydive.yml: |
    storage:
      myorientdb:
        driver: orientdb
        addr: http://172.28.128.3:2480
        database: Skydive
        username: root
        password: 123456

I prefer it is like *******

Thank you in advances

**Comment by lebauce** [comment]
@quangtamle If you use Kubernetes to deploy Skydive, you probably can use Secrets (https://kubernetes.io/docs/concepts/configuration/secret/) and not have the password in clear in the Kubernetes template. Now the password will still be stored in clear in the Skydive YAML because it has to be stored somewhere and we don't support any kind of keyring stuff.

**Comment by quangtamle** [comment]
Hi @lebauce ,

Thank you so much for your information !!! I will try it

**Comment by quangtamle** [comment]
Hi @lebauce ,

I try to use neo4j instead of orientdb but it didnt work. Is it supported by skydive????

Thank you in advances

**Comment by lebauce** [comment]
@quangtamle Sorry, this is not supported.

**Comment by quangtamle** [comment]
@lebauce it's fine, thank you !!!

**Comment by lebauce** [comment]
@quangtamle Do you think we can close this issue ?

**Comment by quangtamle** [comment]
Hi @lebauce , sorry, let me close it !!! Thank you
