### ISSUE TITLE
Type and BPFfilter are ignored on capture create

### ISSUE THREAD

**Issue by liranschour** [skydive-project/skydive#179]
On capture create the values of --type and --bpf are being ignored.
Need to verify and implement functionality.

**Comment by nplanel** [comment]
Should be fixed on master. 352e0f9682a1efa4b52dd64b4c9d7f10f8956dcd
Note : BPF filter works only for capture type pcap

**Comment by masco-enovance** [comment]
tested the 'type' input it is not ignored, for example if you give a wrong type you will get a error reply.
need to verify the 'bpfilter'.
