### ISSUE TITLE
export flows to external entities

### ISSUE THREAD

**Issue by hunchback** [skydive-project/skydive#1821]
NOTE: a topology exporter is out-of-scope for now

# Overview

We want to a set of components to facilitate the easy development (and deployment) or exporter.

What is an exporter? its' a component which takes information out of skydive and pushes it to an upstream system.

What does an exporter do? it setups the system (such as setting required flow captures), it listens to the flow events, it then transforms the information, formats the data and stores it to a target storage/queue.

# Use Cases

Security Advisor:
- capture: flows on all nodes
- transform: enrich flows structure; remove some fields
- format: json
- target: S3
- instances: single

VPC Logs:
- capture: tenant flows
- transform: 5-tuple (src-ip, dst-ip, src-port, dst-port, protocol)
- format: CVS
- store: S3 or Kafka
- instances: multi

# Architecture

We want to enable the simple creation of  capture-transform-format-store pipelines

- capture: define a capture with captureID
- subscribe: subscribe via WebSocket, optionally filer on server-side using the captureID
- filter: client side (using custom domain specific filtering not supported on server-side)
- classify: create different queues for different types of flows (egress, ingress, internal ..)
- batch: split the stream of flows (according to time windows, size of target object, etc)
- transform: from flow to a target structure
- encode: encode as JSON, CSV
- compress: GZIP or the likes 
- store: store batch events to target storage

**Comment by hunchback** [comment]
@eranra - please help with requirements

**Comment by safchain** [comment]
I'm currently on a mechanism to export/send flow/packet to an external system on the agent side. I will push a draft soon

**Comment by JasonKeirstead** [comment]
Hi is there any update on this work @safchain @hunchback

**Comment by safchain** [comment]
Yes there is, We added a way to export flows from agent to an external endpoint. Currently we support two protocol, ErspanII and NetFlow v5

https://github.com/skydive-project/skydive/commit/fe93d39c7a010229d2102e307f9c8fa0ffabd998#diff-e24b0d6fee86a1b5e1c7d595589ee728
https://github.com/skydive-project/skydive/commit/195194d64461f10aa480b78c236383f9486246ae#diff-7f6d241540cfd5c11544391064951df8

We need to document this. In order to use it, from the command line : 

Erspan
```
skydive client capture create --gremlin "G.V().Has('TID', 'bf5906d0-1270-50ad-4027-1db0d3a9bc78')" --target 172.10.10.1:0 --target-type erspanv1
```

NetFlow:
```
skydive client capture create --gremlin "G.V().Has('TID', 'bf5906d0-1270-50ad-4027-1db0d3a9bc78')" --target 172.10.10.1:5454 --target-type netflowv5
```

For an OVS bridge it will be like this :

sFlow
```
skydive client capture create --gremlin "G.V().Has('TID', 'bf5906d0-1270-50ad-4027-1db0d3a9bc78')" --target 172.10.10.1:5454 --type ovssflow
```

NetFlow
```
skydive client capture create --gremlin "G.V().Has('TID', 'bf5906d0-1270-50ad-4027-1db0d3a9bc78')" --target 172.10.10.1:5454 --type ovsnetflow
```

I let @hunchback explain what is going on on the flow subscriber/pipeline side

**Comment by JasonKeirstead** [comment]
Thanks @safchain, I browsed the PR.  

Could these be made pluggable somehow to make it easier to add custom exporters? Right now they are listed right in the code. Thoughts?

**Comment by hunchback** [comment]
@JasonKeirstead - there is an initial implementation of export pipeline infra in place. (its still missing some of the listed phases above such as capture - so you must setup a capture before operation and the pipeline will currently get all captured flows (so missing server-side filtering).

You may want to have a look at `contrib/pipelines/dummy` which is a trivial pipeline which listens to all flow events and outputs the flow content on screen.

As the pipelines are external to skydive you should be able to create your own pipeline following our examples.

**Comment by eranra** [comment]
Hi @JasonKeirstead for what we just talked on the phone about export of pure/raw packets using Skydive ... best will be to look on [1] http://skydive.network/tutorials/first-steps-7.html#keep-original-packets. 

From the text " ... that way Skydive acts as a distributed tcpdump ... " 

I will ask David to find more time to talk ... but this text should be useful for you (hopefully). 

What @hunchback [2] and @safchain [3] are working on is more of aggregation level code so you get an entry per flow ... and not getting all raw packets like in (1). [2] is from Analyzer level and [3] is from agent/single host level.

@safchain if you need to correct me on new things I am missing that you added with [3] Agent export capabilities (erspanv1/netflowv5) and are for complete raw packet export ?

**Comment by safchain** [comment]
@eranra I'm about to write a blog post but NetFlow is using internally a flow table so it is about flow while erspan is about raw packet within GRE packet

**Comment by eranra** [comment]
@safchain :+1:

**Comment by safchain** [comment]
@Jaganathancse @eranra to elaborate a bit more about what we call "raw packets", when you start a capture requesting for keeping "raw packets" it will attach the original packets (10 max) to the flow. As a flow is forwarded to the analyzer and then to the datastore they are part of the WebSocket communication. A subscriber to the Flow websocket endpoint will see them. Please note that it is possible to request them from the command line and to export them as a PCAP file.

**Comment by JasonKeirstead** [comment]
Is that maximum of 10 configurable to be a larger number?

**Comment by hunchback** [comment]
@safchain - where does the limit of 10 raw packets come from? at least at the command line level it appears to be configurable:

https://github.com/skydive-project/skydive/blob/cf84cc809785aed1bde85b2dcdff36c8b1f8b177/cmd/client/capture.go#L205

**Comment by safchain** [comment]
From here :
https://github.com/skydive-project/skydive/blob/cf84cc809785aed1bde85b2dcdff36c8b1f8b177/validator/validator.go#L221

There is  a limitation mainly to the memory used by the agent. That is because of the current implementation. These PR is a step forward to remove the limit 
https://github.com/skydive-project/skydive/pull/1893

**Comment by safchain** [comment]
@hunchback can we close this now ?
