### ISSUE TITLE
Analyser crash with k8s probe on Openshift

### ISSUE THREAD

**Issue by gant02** [skydive-project/skydive#1829]
Hello,

I try to use the k8s probe in the latest skydive version with an openshift Cluster in v3.9 and the analyser crash if I set the 'k8s' parameters for SKYDIVE_ANALYZER_TOPOLOGY_PROBES environment variable. (no problem with the analyser when I unset it).

Here is the message:

panic: runtime error: invalid memory address or nil pointer dereference
--
  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x14f6771]
  |  
  | goroutine 1 [running]:
  | github.com/skydive-project/skydive/topology/probes/k8s.newClusterProbe(0x29769c0, 0xc4204ffc30, 0xc420d92e40, 0x7, 0xc420b69530)
  | /root/go/src/github.com/skydive-project/skydive/topology/probes/k8s/cluster.go:69 +0x211
  | github.com/skydive-project/skydive/topology/probes/k8s.InitSubprobes(0xc420dfe9b0, 0x5, 0x5, 0xc420b693b0, 0x29769c0, 0xc4204ffc30, 0xc420d92e40, 0x31e2da0, 0x3)
  | /root/go/src/github.com/skydive-project/skydive/topology/probes/k8s/probe.go:182 +0x13e
  | github.com/skydive-project/skydive/topology/probes/k8s.NewK8sProbe(0xc420d92e40, 0x3, 0x31e2e7e, 0x3)
  | /root/go/src/github.com/skydive-project/skydive/topology/probes/k8s/k8s.go:84 +0x2b7
  | github.com/skydive-project/skydive/analyzer.NewTopologyProbeBundleFromConfig(0xc420d92e40, 0xc42013f8b0, 0x4, 0x4)
  | /root/go/src/github.com/skydive-project/skydive/analyzer/probes.go:59 +0x57d
  | github.com/skydive-project/skydive/analyzer.NewServerFromConfig(0xc420839160, 0x322c93b, 0x1f)
  | /root/go/src/github.com/skydive-project/skydive/analyzer/server.go:297 +0x1021
  | github.com/skydive-project/skydive/cmd/analyzer.glob..func1(0x5fafae0, 0xc420526e10, 0x0, 0x3)
  | /root/go/src/github.com/skydive-project/skydive/cmd/analyzer/analyzer.go:44 +0x127
  | github.com/skydive-project/skydive/vendor/github.com/spf13/cobra.(*Command).execute(0x5fafae0, 0xc42083e600, 0x3, 0x4, 0x5fafae0, 0xc42083e600)
  | /root/go/src/github.com/skydive-project/skydive/vendor/github.com/spf13/cobra/command.go:603 +0x234
  | github.com/skydive-project/skydive/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x5fb5200, 0x0, 0x5faf6a0, 0xc420749f58)
  | /root/go/src/github.com/skydive-project/skydive/vendor/github.com/spf13/cobra/command.go:689 +0x2d4
  | github.com/skydive-project/skydive/vendor/github.com/spf13/cobra.(*Command).Execute(0x5fb5200, 0xc420749f78, 0xc420128058)
  | /root/go/src/github.com/skydive-project/skydive/vendor/github.com/spf13/cobra/command.go:648 +0x2b
  | main.main()
  | /root/go/src/github.com/skydive-project/skydive/skydive.go:27 +0x2d

Thanks for your help !

Br,

**Comment by safchain** [comment]
@hunchback can you have a look at this one, seems to the cluster name change

**Comment by hunchback** [comment]
will check

**Comment by hunchback** [comment]
fixed in https://github.com/skydive-project/skydive/pull/1831

**Comment by gant02** [comment]
Solved, Thanks !
