### ISSUE TITLE
Use contextual menu on WebUI Graph

### ISSUE THREAD

**Issue by matrohon** [skydive-project/skydive#183]
Instead of having metadatas and actions (flow, generator) in the side pane, ti would be nice to have those info/action items in a pop-up window when clicking on a node of the graph

**Comment by eonpatapon** [comment]
Not a bad idea. What could be nice also maybe is to be able to open multiple node info "panel" that can be dragged around.

In fact we can imagine to remove completely the sidebar in this case

**Comment by matrohon** [comment]
yep, removing the side bar would be nice :)

The flow capture pane could be displayed below the graph, and flow details displayed in a popup window too, accessed by double clicking or right clicking a flow

**Comment by safchain** [comment]
Having a popup window correctly placed is not always easy especially if the window is wide, think about having nodes close to borders. For the side bar, I don't especially want to keep it like this but I would prefer to have a side bar than could be optional instead of a bottom bar as we all have wide screen.

In any case there is for sure a huge space for improvements !

What do you think of opening a gdoc to describe the idea maybe adding 'Gimp' base proposal it may be  easier than pushing wip code ?

**Comment by eonpatapon** [comment]
Sure, WIP code is only an experiment using vue.js

For example it demonstrate how easy it is to reuse UI components (I can use the same 'filter component' for topology and flows).

Another use case is for example the node selector component that can be used in the capture and injection forms.

Anyway, it's off-topic :-)

**Comment by safchain** [comment]
No problem WIP code is good for code design, so WIP showing how we can reuse component is nice. I was more suggesting a gdoc for "design" purpose.

**Comment by eonpatapon** [comment]
After thinking about the 'panel' I'm not sure it's a good idea either.

I don't know if it would be useful but I was more thinking to be able to view the details or flows of multiple nodes.

For example, you could right click on a node and select flows. In this case the flowtable of the node would be added to the sidebar (stacked). With this you could monitor the flows of multiple nodes "live". On top of that you add a form to be able to filter all displayed flow tables.

+1 for creating such document where we could brainstorm on new UI ideas

**Comment by safchain** [comment]
Hi, 

Just opened a document, feel free to request an access to it and to contribute. I proposed a first document structure where we can add use cases, framework and desgin proposal. I added a first very wip design as an example. 

https://docs.google.com/document/d/1MHKdQOBUTDbpFFftsu8pTmnTt57dMbNI7_0RFIJ0vU8/edit#

Thanks

**Comment by safchain** [comment]
Closing, new WebUI will handle this
https://github.com/skydive-project/skydive-ui
