### ISSUE TITLE
Display openstack metadata for instances?

### ISSUE THREAD

**Issue by mnbruce** [skydive-project/skydive#1830]
Maybe this is already possible and my config is wrong, but it would be very useful to be able to see openstack server metadata (if applicable) when selecting an instance vertex. 
The virsh uuid corresponds to the openstack server ID so it is possible to tie the two together.

e.g. the script below correlates the libvirt name, the uuid, and the openstack server name..

    #! /bin/bash
    IFS=$'\n'
    domainnames=($(virsh list))
    domainnames=("${domainnames[@]:2}")
    for domain in ${domainnames[@]}; do
            virshname=$(echo "$domain" | awk '{ print $2'} )
            # openstack and virsh share the uuid.
            uuid=$(virsh dominfo $virshname | grep UUID | awk '{ print $2 }')
            openstackname=$(openstack server list -f value -c ID -c Name | grep $uuid | awk '{print $2}')
            echo "$uuid: $virshname : $openstackname"
    done

Which generates output of the form..

    $ ./servernames.sh 
    9c64d122-b853-4be3-ad12-3f3a35366907: instance-00000003 : controller
    a3ee7794-fc1b-4017-885b-a83b1ec9e062: instance-00000067 : nconf
    909f6434-1101-49ef-9794-9de4627cb5dc: instance-00000069 : vta2_7Y68
    7b3a51e0-2c4b-44e9-b632-866fac10a579: instance-0000006a : agent2_7Y68
    37e0161f-cf8f-4ba1-8db0-50fdb097d4af: instance-0000006b : agent1_7Y68
    890c7146-5abb-4c9f-946c-5e0d69f1c98e: instance-00000068 : vta1_7Y68
    $

**Comment by safchain** [comment]
@mnbruce This is not currently directly possible but using the Neutron probe and the LibVirt probe you will get the vm-id on the interface of the VM.
