### ISSUE TITLE
Kubernetes deployment in crash loop

### ISSUE THREAD

**Issue by hwinkel** [skydive-project/skydive#1833]
The Kubernetes deployment mentioned in the lates blog article:

http://skydive.network/blog/k8s-probe.html

goes into a continues CrashBackoffLloop. seems the Pod containing the ES:5 and Analyzer deployment comes not up.

`
│ 2019-05-26T07:00:00.869Z    INFO    analyzer/storage.go:85 newFlowBackendFromConfig    skydive-analyzer-75784754d8-hgtmc: Using elasticsearch (driver ela │
│ sticsearch) as flow storage backend                                                                                                                       ││ panic: runtime error: invalid memory address or nil pointer dereference                                                                                   │
│ [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x14f6771]                                                                                  ││                                                                                                                                                           │
│ goroutine 1 [running]:                                                                                                                                    ││ github.com/skydive-project/skydive/topology/probes/k8s.newClusterProbe(0x29769c0, 0xc4203d47f0, 0xc420659500, 0x7, 0xc42098b530)                          │
│     /root/go/src/github.com/skydive-project/skydive/topology/probes/k8s/cluster.go:69 +0x211                                                              ││ github.com/skydive-project/skydive/topology/probes/k8s.InitSubprobes(0xc42037a010, 0x1, 0x1, 0xc42098b3b0, 0x29769c0, 0xc4203d47f0, 0xc420659500, 0x31e2d │
│ a0, 0x3)                                                                                                                                                  ││     /root/go/src/github.com/skydive-project/skydive/topology/probes/k8s/probe.go:182 +0x13e
`

I have tried this with lates version of minikube 1.10  ans a fresh 1.13 GKE Cluster
Both with v0.22 and v0.23of the deployment.

**Comment by hunchback** [comment]
fixed by https://github.com/skydive-project/skydive/pull/1831

**Comment by lebauce** [comment]
@hwinkel Could you please give the new image a try ? Thanks !

**Comment by hunchback** [comment]
I believe issue has been addressed
