### ISSUE TITLE
ui: medium landscape topology getting Disconnected/Connect

### ISSUE THREAD

**Issue by hunchback** [skydive-project/skydive#1834]
On a medium sized multi ICP cluster landscape (with k8s and physical artifacts) the UI topology view either does not come-up or it does but we get a series of Disconnect/Connect messages on the right hand side of the screen.

**Comment by hunchback** [comment]
![image](https://user-images.githubusercontent.com/2760739/58383288-80fbdb00-7fdd-11e9-9896-7829be1a8809.png)

**Comment by safchain** [comment]
did you try to increase this : 
https://github.com/skydive-project/skydive/blob/master/etc/skydive.yml.default#L29-L32

**Comment by eranra** [comment]
Hi @safchain I did several tests with that, and it **does not work**. Maybe something I am doing wrong.

I ran: `helm install ibm-charts/ibm-skydive-dev --name=skydive-mcm --namespace=default --set env[0].name="SKYDIVE_HTTP_WS_PING_DELAY" --set-string env[0].value="20" --set env[1].name="SKYDIVE_HTTP_WS_PONG_TIMEOUT" --set-string env[1].value="120" --set image.tag=$SKYDIVE_IMAGE_TAG --tls`

this creates the  SKYDIVE_HTTP_WS_PING_DELAY environment variable and the SKYDIVE_HTTP_WS_PONG_TIMEOUT environment variable with the updated parameters ... I still see disconnects ... I checked the disconnects ... it 'feels' / looks like every 10 seconds +- ... 

Not sure what's next :?:

**Comment by safchain** [comment]
Can we close this one ? It seems that we fixed the issue with the filtering fix ?

**Comment by eranra** [comment]
@safchain YES ... it was solved ... thanks for the help/support :-)
