### ISSUE TITLE
Authenticate to Openstack with READ ONLY attributes

### ISSUE THREAD

**Issue by matrohon** [skydive-project/skydive#184]
Currently, Skydive is using cloud admin credentials to get datas from Openstack/Neutron.
Skydive should not be granted such permissions for obvious security reason.

**Comment by matrohon** [comment]
One possible way to enhance the situation would be to create a dedicated service tenant for skydive, and update the neutron policy file accordingly.

**Comment by lebauce** [comment]
Skydive doesn't make any modification to OpenStack. Creating a dedicated service tenant for Skydive is possible and is a deployment matter.
