### ISSUE TITLE
Flow websocket client do not stream flows when capture is eBPF

### ISSUE THREAD

**Issue by liranschour** [skydive-project/skydive#1848]
Flow websocket (URI path /ws/subscriber/flow) does not stream flows when capture type == ebpf.
Only on deletion of the ebpf capture, all flows are being transferred to the websocket client.

This behavior happens only for ebpf capture type.

**Comment by hunchback** [comment]
@nplanel / @safchain - can you look into this? this may be on the critical path soon

**Comment by safchain** [comment]
@hunchback I just submitted a fix for that
https://github.com/skydive-project/skydive/pull/1946

If it seems correct for you feel free to merge it

**Comment by hunchback** [comment]
@liranschour - fix has been merged - closing
