### ISSUE TITLE
Port 8081 In Use

### ISSUE THREAD

**Issue by cliffburdick** [skydive-project/skydive#1855]
Hi, I'm trying to deploy to a brand new Kubernetes cluster where there should be nothing running on 8081 on any node, but I get this when deploying the yaml:

```
2019-06-08T03:58:05.069Z        INFO    agent/agent.go:41 glob..func1   comp008: Skydive Agent 0.23.0-4679daac9aca starting...
2019-06-08T03:58:05.069Z        ERROR   agent/agent.go:45 glob..func1   comp008: Can't start Skydive agent: Failed to listen on 127.0.0.1:8081: listen tcp 127.0.0.1:8081: bind: address already in use
```

I haven't modified the stock yaml at all. Is this a bug, or is it possibly mapping to a different host port?

Edit: It seems nginx is using that port. Changing the port in the yaml didn't work. Is there a way to change the agent's port?

**Comment by hunchback** [comment]
you can try replacing 8081 with 18081:

```
wget https://raw.githubusercontent.com/skydive-project/skydive/master/contrib/kubernetes/skydive.yaml | sed -e 's/8081/10801/' | kubectl apply -f -
```

**Comment by cliffburdick** [comment]
@hunchback I tried that to no avail. It still tries to open 8081.

**Comment by lebauce** [comment]
@cliffburdick Besides changing all `8081` references to `18081`, you need to add an environment variable here https://github.com/skydive-project/skydive/blob/master/contrib/kubernetes/skydive.yaml#L156, named `SKYDIVE_AGENT_LISTEN` with the value `127.0.0.1:18081`

**Comment by cliffburdick** [comment]
Thanks @lebauce. I'll give that a try.

**Comment by hunchback** [comment]
I created a PR to make all ports explicit and configurable (via sed): https://github.com/skydive-project/skydive/pull/1861

**Comment by hunchback** [comment]
@cliffburdick - any further updates ?

**Comment by cliffburdick** [comment]
@hunchback that worked. Thanks! Not sure what happened the first time.
