### ISSUE TITLE
Evaluate germlin capture when start the Agent

### ISSUE THREAD

**Issue by nplanel** [skydive-project/skydive#186]
If you start a new Agent (or restart for example), the gremlin capture like g.V().Has("Type", "veth") will not be evaluated during startup of the Agent.
So no capture probe will be launched.

**Comment by safchain** [comment]
Yes, and the agent seems to be blocked somewhere

**Comment by lebauce** [comment]
I can not reproduce the bug. Could you try again on master ?

**Comment by kdorfman** [comment]
I've reproduced this today.

**Comment by kdorfman** [comment]
probably resolved by https://softwarefactory-project.io/r/#/c/6094/
