### ISSUE TITLE
 Document address could not be opened

### ISSUE THREAD

**Issue by RunningXJ** [skydive-project/skydive#1863]

**Comment by safchain** [comment]
Not sure to understand. Can you please elaborate ?

**Comment by RunningXJ** [comment]
i got it! it's https

**Comment by safchain** [comment]
I assume this is the Skydive WebUI you tried to open ? How did you deploy it ? what is your confirguration file ? how did you generate the certificate ? Anything that could help me to reproduce. Thanks
