### ISSUE TITLE
OVS openflow rules - Actions goto_table-type not parsed in UI

### ISSUE THREAD

**Issue by manuvaldi** [skydive-project/skydive#1864]
When I use ovsdb probe and click in rules in the UI, actions "goto_table" are not parsed.
Example:

```# ovs-ofctl -OOpenFlow11 dump-flows br-fabric | grep "table=1,"

cookie=0x0, duration=78742.348s, table=1, n_packets=745, n_bytes=45978, priority=149,in_port=37,dl_vlan=1008 actions=pop_vlan,load:0x3f0->NXM_NX_REG0[],load:0x2->NXM_NX_REG4[],load:0x2->NXM_NX_REG5[],load:0x3->NXM_NX_REG6[],write_metadata:0x100/0x100,goto_table:2
 cookie=0x0, duration=78741.861s, table=1, n_packets=1954, n_bytes=118590, priority=149,in_port=37,dl_vlan=1352 actions=pop_vlan,load:0x548->NXM_NX_REG0[],load:0x3->NXM_NX_REG4[],load:0x4->NXM_NX_REG5[],load:0x3->NXM_NX_REG6[],write_metadata:0x100/0x100,goto_table:2
 cookie=0x0, duration=78742.345s, table=1, n_packets=2701, n_bytes=164240, priority=149,in_port=37,dl_vlan=1393 actions=pop_vlan,load:0x571->NXM_NX_REG0[],load:0x4->NXM_NX_REG4[],load:0x3->NXM_NX_REG5[],load:0x2->NXM_NX_REG6[],write_metadata:0x100/0x100,goto_table:2
 cookie=0x0, duration=15530.552s, table=1, n_packets=15383, n_bytes=1528174, priority=149,in_port=37,dl_vlan=1000 actions=pop_vlan,load:0x3e8->NXM_NX_REG0[],load:0x1->NXM_NX_REG4[],load:0x1->NXM_NX_REG5[],load:0x1->NXM_NX_REG6[],write_metadata:0x100/0x100,goto_table:2
 cookie=0x0, duration=78742.349s, table=1, n_packets=356, n_bytes=19183, priority=140,in_port=53,dl_src=fa:16:3e:27:53:6c actions=load:0x3f0->NXM_NX_REG0[],load:0x2->NXM_NX_REG4[],load:0x2->NXM_NX_REG5[],load:0x3->NXM_NX_REG6[],goto_table:2
 cookie=0x0, duration=78741.862s, table=1, n_packets=359, n_bytes=19421, priority=140,in_port=52,dl_src=fa:16:3e:94:b6:20 actions=load:0x548->NXM_NX_REG0[],load:0x3->NXM_NX_REG4[],load:0x4->NXM_NX_REG5[],load:0x3->NXM_NX_REG6[],goto_table:2
 cookie=0x0, duration=15530.553s, table=1, n_packets=15429, n_bytes=1455132, priority=140,in_port=65,dl_src=fa:16:3e:d4:c4:61 actions=load:0x3e8->NXM_NX_REG0[],load:0x1->NXM_NX_REG4[],load:0x1->NXM_NX_REG5[],load:0x1->NXM_NX_REG6[],goto_table:2
```

![image](https://user-images.githubusercontent.com/10829687/59435491-00671800-8dee-11e9-9b1a-f4fb72da69fc.png)

Other example:
```
# ovs-ofctl -OOpenFlow11 dump-flows br-fabric | grep "table=6,"

 cookie=0x0, duration=79004.949s, table=6, n_packets=2, n_bytes=204, priority=150,ip,reg6=0x3 actions=load:0x80000006->NXM_NX_REG0[],write_metadata:0x3/0x1ff,goto_table:9
 cookie=0x0, duration=79004.933s, table=6, n_packets=0, n_bytes=0, priority=150,ip,reg6=0x2 actions=load:0x80000004->NXM_NX_REG0[],write_metadata:0x3/0x1ff,goto_table:9
```
![image](https://user-images.githubusercontent.com/10829687/59435694-710e3480-8dee-11e9-9b54-71a5d791541b.png)

agent config (skydive.yml)
```
agent:
  topology:
    probes:
      - ovsdb
      - neutron

ovs:
  oflow:
    enable: true
    native: true
    openflow_versions:
      - OpenFlow13

analyzer:
  listen: 0.0.0.0:8082
```
Tested with docker images
- skydive/skydive:latest (2019-06-13) - 0.23.0-4679daac9aca
- skydive/skydive:0.23.0

**Comment by lebauce** [comment]
@manuvaldi Indeed, we did not report `goto_table` instruction (but only the `resubmit` actions that is OVS specific). I just pushed a PR that adds a `GotoTable` attribute to the metadata. Any chance that you  could give it a try ? Thanks !

**Comment by lebauce** [comment]
@manuvaldi By the way, the GotoTable does not appear in the "actions" column of the Web UI but you should be able to jump to the table with a link in the "summary" column

**Comment by manuvaldi** [comment]
Hi @lebauce, I have seen your commit related (https://github.com/skydive-project/skydive/commit/f51b61fb0967b4bd93be95616865d53eeb160790). Seem to print out actions gototable now. Thanks a lot!!

![image](https://user-images.githubusercontent.com/10829687/59601127-6cee5980-9103-11e9-8023-0a4788c3424f.png)

Just one thing, there seem to be a problem when there is only 1 action. A ban icon appears before the link:

```
# ovs-ofctl -OOpenFlow13 dump-flows br-int  | grep "table=9"

 cookie=0x0, duration=1451370.585s, table=9, n_packets=0, n_bytes=0, priority=8243,metadata=0x200/0x200 actions=goto_table:10
 cookie=0x0, duration=1451370.585s, table=9, n_packets=0, n_bytes=0, priority=8242,metadata=0x100/0x100 actions=drop
 cookie=0x0, duration=1451370.585s, table=9, n_packets=0, n_bytes=0, priority=10,icmp6,icmp_type=136,icmp_code=0 actions=goto_table:10
 cookie=0x0, duration=1451370.585s, table=9, n_packets=0, n_bytes=0, priority=10,icmp6,icmp_type=135,icmp_code=0 actions=goto_table:10
 cookie=0x0, duration=1451370.585s, table=9, n_packets=0, n_bytes=0, priority=10,arp actions=goto_table:10

```
![image](https://user-images.githubusercontent.com/10829687/59601210-acb54100-9103-11e9-8cff-52a62c72cba5.png)

Also, I have seen other action that it's not parsed. Action-> output:<port> . This is an example:

```
# ovs-ofctl -OOpenFlow13 dump-flows br-int  | grep "table=10"

 cookie=0x8000000000000008, duration=1451567.330s, table=10, n_packets=0, n_bytes=0, priority=10,icmp,metadata=0x3/0xff,icmp_type=11 actions=CONTROLLER:65535
 cookie=0x8000000000000008, duration=1451567.330s, table=10, n_packets=0, n_bytes=0, priority=10,icmp,metadata=0x3/0xff,icmp_type=12 actions=CONTROLLER:65535
 cookie=0x8000000000000008, duration=1451567.330s, table=10, n_packets=0, n_bytes=0, priority=10,icmp,metadata=0x3/0xff,icmp_type=3 actions=CONTROLLER:65535
 cookie=0x0, duration=1451567.330s, table=10, n_packets=0, n_bytes=0, priority=1,metadata=0/0xff actions=output:NXM_NX_REG7[]
 cookie=0x0, duration=1451567.330s, table=10, n_packets=0, n_bytes=0, priority=1,metadata=0x3/0xff actions=output:NXM_NX_REG7[]
```
![image](https://user-images.githubusercontent.com/10829687/59601419-3402b480-9104-11e9-913a-c563dd7d2bde.png)

(Maybe you prefer a new issue for that)
Thanks for your work

**Comment by lebauce** [comment]
@manuvaldi Thank you for trying the fix. Regarding the wrong "drop" action" : we were adding a "drop" action - that don't really exist in the rule itself but it is added by the ovs-ofctl command line - when the action list was empty. I changed this behaviour to add it only if there is no action, no write action and no goto_table.

For the "???" characters, we were not handling the output port "controller". This should now be fixed.

I pushed a PR with the fixes : https://github.com/skydive-project/skydive/pull/1874
Could you please give it a try ? Thanks !

**Comment by manuvaldi** [comment]
it looks like pretty well @lebauce 

![image](https://user-images.githubusercontent.com/10829687/59910192-b8f61280-9411-11e9-97cf-312783bc388e.png)

![image](https://user-images.githubusercontent.com/10829687/59910199-bdbac680-9411-11e9-8f00-c9cf90ba1f57.png)

Thanks a lot!

**Comment by safchain** [comment]
@manuvaldi Thanks for the feedback, just merged

**Comment by safchain** [comment]
Closing it as merged, thanks again @manuvaldi
