### ISSUE TITLE
When I execute the make operation error, can you help me see it?

### ISSUE THREAD

**Issue by RunningXJ** [skydive-project/skydive#1866]
The following is the error message.

 Remotes failed for:
	Failed for "golang.org/x/crypto/bcrypt" (failed to ping remote repo): unrecognized import path "golang.org/x/crypto/bcrypt"
	Failed for "golang.org/x/crypto/blowfish" (failed to ping remote repo): unrecognized import path "golang.org/x/crypto/blowfish"
	Failed for "golang.org/x/crypto/cast5" (failed to ping remote repo): unrecognized import path "golang.org/x/crypto/cast5"
	Failed for "golang.org/x/crypto/curve25519" (failed to ping remote repo): unrecognized import path "golang.org/x/crypto/curve25519"
......................

Makefile:550: recipe for target 'govendor' failed
make: *** [govendor] Error 2

**Comment by safchain** [comment]
Can you please describe a bit your golang setup ? OS Version ? did you follow this documentation : http://skydive.network/documentation/build 
thanks

**Comment by RunningXJ** [comment]
thanks! I slove it! I download binary
