### ISSUE TITLE
Websocket client sends TextMessage even for binary payloads

### ISSUE THREAD

**Issue by dubek** [skydive-project/skydive#1873]
The Websocket protocol distinguishes between text data frames and binary data frames:

```
5.6.  Data Frames
   Data frames (e.g., non-control frames) are identified by opcodes
   where the most significant bit of the opcode is 0.  Currently defined
   opcodes for data frames include 0x1 (Text), 0x2 (Binary).  Opcodes
   0x3-0x7 are reserved for further non-control frames yet to be
   defined.
```
(see https://tools.ietf.org/html/rfc6455#section-5.6)

However, Skydive's Websocket client always sends messages as TextMessage, even though it sometimes sends binary payloads (protobuf-encoded messages):

https://github.com/skydive-project/skydive/blob/master/websocket/client.go#L283

(also the comment of the `write` method uses the wrong method name.)

I discovered this when I tried to replace analyzer with my own Websocket server (Node.js-based); the protobuf messages were delivered as text and then my server tried to decode them as UTF-8.

I assume that sometimes Skydive does send text messages (for example when delivering JSON payloads to subscribers).

On the websocket receiving end it seems like Skydive handles all incoming messages as RawMessage; not sure if it's OK or not.

https://github.com/skydive-project/skydive/blob/master/websocket/client.go#L326

**Comment by safchain** [comment]
Hi, thanks for reporting this, it seems to be a remaining piece of code before we partially move to protobuf. I guess now it should always be binary.

**Comment by lebauce** [comment]
Addressed by https://github.com/skydive-project/skydive/pull/1879.
@dubek Could you please check if it fixes the problem ? Thanks !

**Comment by dubek** [comment]
Indeed the issue is solved with the latest Skydive. I now get binary payloads when receiving messages from the agent (protobuf) if I "replace" the analyzer, but I still get text payloads (JSON) when subscribing to Skydive's analyzer's `/ws/subscriber/flow` websocket, as expected.

Thanks!

**Comment by lebauce** [comment]
Thanks for testing !
