### ISSUE TITLE
UI OVS rules viewer - bad behaviour

### ISSUE THREAD

**Issue by manuvaldi** [skydive-project/skydive#1890]
In the UI, when you click in rules of a OVS bridge. If you dive into other table different than table 0, it comes back to table 0 suddently. This behaviour is constant.

I'm testing with docker images

Las version tested: 0.23.0-6af6f6fbda73

Last version without this behaviour: 0.22.0-f536c665db40
First version with this behaviour: 0.22.0-70ba4ca52b22

**Comment by safchain** [comment]
Thanks for reporting this issue. Indeed the view is reset when we receive event from ovs. This PR #1892
 should fix the problem.

**Comment by manuvaldi** [comment]
Cool!. I look forward to see it. Thanks one more time

**Comment by safchain** [comment]
Closing it for now as a fix has been merged and is now part of a release. Feel free to re-open if needed. Thanks again for supporting Skydive :)
