### ISSUE TITLE
Wrong use of hashing in probe/ebpf/flow.c

### ISSUE THREAD

**Issue by dubek** [skydive-project/skydive#1897]
In `probe/ebpf/flow.c` (and `flow-gre.c`) Skydive uses FNV hash in order to create a unique per-flow key which is used as the key for the flow table exposed to the agent.

However, it seems that in various places in the code there are problematic updates of the hash value. For example, in function `fill_transport` we have:

```c
        __u64 hash_src = 0;
        update_hash_half(&hash_src, layer->port_src);

        __u64 hash_dst = 0;
        update_hash_half(&hash_dst, layer->port_dst);
...
        layer->_hash = FNV_BASIS ^ hash_src ^ hash_dst;
```

Few problems here:

1. According to the FNV [algorithm](https://en.wikipedia.org/wiki/Fowler%E2%80%93Noll%E2%80%93Vo_hash_function#FNV-1a_hash), we should initialize the hash value to `FNV_BASIS` and not to zero (for `hash_src` and `hash_dst`).
2. When calculating the transport hash we xor `hash_src` and `hash_dst`, but their order is not important - both sides will get the same value. Is that on purpose? Supposedly we can have one flow between 1.2.3.4:1000 <-> 5.6.7.8:2000 and another flow between 1.2.3.4:2000 <-> 5.6.7.8:1000 and they should not have identical keys.

In `fill_network` we have:

```c
        layer->_hash = FNV_BASIS ^ hash_src ^ hash_dst ^ netproto ^ transproto;
```

Here we xor non-hash values `netproto` and `transproto` to the hash values. But those are well-known values (0x0800 for IPv4 and 6 for TCP); not sure how that affects the hash value.

In `fill_flow` we have:

```c
        flow->key = flow->link_layer._hash ^ flow->network_layer._hash ^
                flow->transport_layer._hash ^ flow->icmp_layer._hash;
```

But each of those `._hash` values is `FNV_BASIS` xored with something, so we basically xor FNV_BASIS to itself 4 times and cancel it out completely.

I think the use of the hash values should be reviewed; stuff that is made on purpose (for example to allow exchange of src/dst addresses and ports) should be made explicit; and basically should use `update_hash_*` functions instead of XORing whenever applicable.

**Comment by safchain** [comment]
@dubek Thanks for reporting this. @nplanel submitted a WIP #1898 to fix this.

**Comment by dubek** [comment]
Thanks, I'll take a look next week.

**Comment by safchain** [comment]
Fixed now
