### ISSUE TITLE
Problem with "make docker-image"

### ISSUE THREAD

**Issue by quangtamle** [skydive-project/skydive#1901]
Hello everyone,

I want to make a docker-image of skydive and i use "make docker-image" then I have this problem:

make[1]: Leaving directory '/home/tamlq/go/src/github.com/skydive-project/skydive'
cp $GOPATH/bin/skydive contrib/docker/skydive.$(uname -m)
cp: cannot stat '/home/tamlq/go/bin/skydive': No such file or directory
make: *** [Makefile:631: docker-image] Error 1

I look into the Makefile and I found out that when "make docker-image" running, it will trigger ["static"](https://github.com/skydive-project/skydive/blob/master/Makefile#L423) which trigger "skydive.clean". "skydive.clean" will delete the /home/tamlq/go/bin/skydive. That's why it can not copy this file.

After i delete "skydive.clean" in the ["static"](https://github.com/skydive-project/skydive/blob/master/Makefile#L423), everything works well.

Thus, I wonder what i am doing is whether right or wrong ????

Thank you in advances

**Comment by safchain** [comment]
I just tested using master branch and it worked. I suspect you have a compilation error in `static` mode.

please test with `make static`

BTW the Makefile targets order is as follow:

`make docker-image` -> `docker-image` -> `static` -> `skydive.clean` -> `compile.static`

So the build is after the `clean` one

**Comment by quangtamle** [comment]
Thank you @safchain !!!
you're right ! I missed libc++ but after i install libc++, i meet another problem. Could you help me take a look at it ???

![image](https://user-images.githubusercontent.com/43220759/60959730-04ad2500-a309-11e9-8fe5-fb3728a1b489.png)

Thank you in advances

**Comment by safchain** [comment]
What distribution are you using ? Just to be sure you know we build a skydive version each commit
https://hub.docker.com/r/skydive/skydive/tags

Cross compiling could help you too in resolving the dependencies issues. Please take a look at the script we use in order to build docker images in our CI.

https://github.com/skydive-project/skydive/blob/master/scripts/ci/create-docker-image.sh

**Comment by quangtamle** [comment]
My distribution is Ubuntu 18.10. I followed "create-docker-image.sh" and I faced some problems:

![image](https://user-images.githubusercontent.com/43220759/60981511-c3cc0500-a336-11e9-885c-1834fcb2c8df.png)
I dont know why it can not install [libxml2-dev](https://github.com/skydive-project/skydive/blob/master/contrib/docker/Dockerfile.compile#L16) then I try to change into only libxml2 like in this [dockerfile](https://github.com/skydive-project/skydive/blob/master/contrib/docker/Dockerfile#L5) it can install libxml2 but after that there is another problem coming up
![image](https://user-images.githubusercontent.com/43220759/60981777-41901080-a337-11e9-854a-d84435bf8db6.png)

I am really confused. Do I miss something ???

Thank you so much

**Comment by safchain** [comment]
We just merged a fix, 
https://github.com/skydive-project/skydive/commit/bf59cb88b053be5039d11f394d7e0846fac30ae5
something change yesterday it seems. Can you give a try ?

**Comment by quangtamle** [comment]
Hi @safchain 
With the new skydive, i tried "create docker image" in CircleCI and it worked.

Thank you so much
