### ISSUE TITLE
secadvisor fails to connect with latest build

### ISSUE THREAD

**Issue by KalmanMeth** [skydive-project/skydive#1921]
@hunchback @safchain 
contrib/pipelines/secadvisor/main.go was changed in commit 77a90a68c668d75577004c306c9758982b965763 to use cfg := viper.New() calling then to LoadConfig() instead of calling to InitConfig() and building on top of regular skydive config.
secadvisor uses the skydive client interface (via analyzers: xxxx:8082 in the secadvisor.yml) to lookup information about various types of objects.
With the latest change, fields defined in secadvisor.yml are not added to the default config parameters, and the secadvisor is then unable to find the analyzer. This results in the analyzer address being empty when performing the object lookup, and then getting "connection refused".

**Comment by KalmanMeth** [comment]
Suggested fix: Restore call to InitConfig, and in the call to NewSubscriberFromConfig change the paramter to:  NewSubscriberFromConfig

        if err := config.InitConfig("file", []string{defaultCfgFile}); err != nil {
                logging.GetLogger().Errorf("Failed to initialize config: %s", err)
                os.Exit(1)
        }

        if err := config.InitLogging(); err != nil {
                logging.GetLogger().Errorf("Failed to initialize logging system: %s", err)
                os.Exit(1)
        }

        s, err := NewSubscriberFromConfig(config.GetConfig().Viper)

**Comment by safchain** [comment]
I don't think we should use the skydive config parser to parse the secadvisor config file. If some default values are not filled then it should be done in the secadvisor side. There log of Skydive default things that are unrelated to secadvisor. Going to have a look at what is missing...

**Comment by safchain** [comment]
the `analyzers` param is missing in the default config file:
https://github.com/skydive-project/skydive/blob/master/contrib/pipelines/secadvisor/secadvisor.yml.default

**Comment by safchain** [comment]
here a potential fix: #1922, please tell me if correct or not

**Comment by KalmanMeth** [comment]
I had added the analyzers parameter into my config file, it was found by the code, but it was not merged into the global config file. Then when secadvisor tried to connect to the analyzer, the address was not found.

**Comment by hunchback** [comment]
> I don't think we should use the skydive config parser to parse the secadvisor config file. If some default values are not filled then it should be done in the secadvisor side. There log of Skydive default things that are unrelated to secadvisor. Going to have a look at what is missing...

@safchain - i think we do want to use the defaults in skydive.yml as secadvisor (and other pipelines) make use of skydive modules (such as for creating a REST Client to the analyzer) these modules assume skydive default configuration values, thus we should restore this behavior.

**Comment by hunchback** [comment]
> the `analyzers` param is missing in the default config file:
> https://github.com/skydive-project/skydive/blob/master/contrib/pipelines/secadvisor/secadvisor.yml.default

@KalmanMeth was using PR https://github.com/skydive-project/skydive/pull/1914 which has the analyzers parameter set.

**Comment by safchain** [comment]
@hunchback there is a lot of unrelated thing in the config file of skydive, relocation, agent things, storage... why using something for only an endpoint address

**Comment by safchain** [comment]
@hunchback moreover what about adding secadvisor defaults ? you will have to put default in the common.config file ?

**Comment by hunchback** [comment]
> @hunchback there is a lot of unrelated thing in the config file of skydive, relocation, agent things, storage... why using something for only an endpoint address

Currently the pipeline makes use of:
- host_id (for websocket client id)
- analyzers (for REST client to access analyzer)
Suggesting that pipelines will need more skydive configuration parameters as they evolve and depend or additional skydive modules ... I would hate to duplicate parameters (and defaults and relocation) in pipeline codebase.

So

**Comment by hunchback** [comment]
> @hunchback moreover what about adding secadvisor defaults ? you will have to put default in the common.config file ?

I agree and will address this within pipelines/core (if needed I will generalize some of the functions in config).

**Comment by hunchback** [comment]
@KalmanMeth - I have updated/fixed PR 
https://github.com/skydive-project/skydive/pull/1914
Please try.

**Comment by safchain** [comment]
currently you are using 2 parameters only for REST client, 90% of the defaults are useless and will remain useless (agent probes, etc.). From my point of view a subscriber should be as much as possible decoupled from Skydive. I do not see the point of keeping using something for hypothetical future usage. That said, that is in contrib, you can use the Skydive default if you want

**Comment by hunchback** [comment]
@safchain - the problem is that the Skydive code takes these parameters implicitly from the default skydive configuration; and while we may set only 'host_id' we are making use of default of 'http.ws.queue_size' :

```
// NewWSClient creates a Client based on the configuration
func NewWSClient(clientType common.ServiceType, url *url.URL, opts websocket.ClientOpts) (*websocket.Client, error) {
        host := GetString("host_id")                                                                           // overridden:  ""

        // override some of the options with config value
        opts.QueueSize = GetInt("http.ws.queue_size")                                             // default: 10000
        opts.WriteCompression = GetBool("http.ws.enable_write_compression")    // default: true
        tlsConfig, err := GetTLSClientConfig(true)
        if err != nil {
                return nil, err
        }
        opts.TLSConfig = tlsConfig

        return websocket.NewClient(host, clientType, url, opts), nil
}
```

**Comment by KalmanMeth** [comment]
@hunchback The updates work for me.
