### ISSUE TITLE
Documentation: Add blog post on performance evaluation with ebpf

### ISSUE THREAD

**Issue by eranra** [skydive-project/skydive#1924]
Need to add to skydive.network (or a different public facing location) documentation based on the information that @andrekassis and @safchain created that is currently available here: 

https://github.com/skydive-project/skydive.network/blob/8197fe853c6020b33a8b962ad3a14ec5bec64073/documentation/skydive-with-ebpf.md

**Comment by safchain** [comment]
Just rebased the blog post and merged it
