### ISSUE TITLE
pipeline: building skydive dependencies

### ISSUE THREAD

**Issue by hunchback** [skydive-project/skydive#1930]
currently to build a pipeline one need to run:

```
cd $GOPATH/src/github.com/skydive-project/skydive
make
make -C contrib/pipelines/secadvisor
```

Note that there we can't skip the `make` as the required skydive modules require running of:
- easyjson
- common.Getter code generation
- etc.

So currently if we would want to main a pipeline outside of skydive we would have to build skydive and include some of the generated files ... is there an alternative to this?

For example we could maintain a non-optimized standard build option:
- standard json rather than easyjson
- common.Getter code using reflection
- etc

**Comment by hunchback** [comment]
@eranra / @liranschour - please elaborate ...

**Comment by safchain** [comment]
`make contrib.objectstore` handle dependencies

**Comment by safchain** [comment]
easyjson files should be easy to generate with go generate. For protobuf files it seems less obvious we need to investigate a bit on this...
