### ISSUE TITLE
make-docker-image build error

### ISSUE THREAD

**Issue by idan-anner** [skydive-project/skydive#1953]
Im trying to compile a skydive docker image and am getting the following error
![image](https://user-images.githubusercontent.com/53993257/62832099-33812880-bc32-11e9-8fde-ad052a228123.png)

**Comment by safchain** [comment]
Hi, it looks like a network issue... `failure resolving....`. What is the command line used ?
BTW our last automatic build can be found here:
https://cloud.docker.com/u/skydive/repository/docker/skydive/skydive
and is generated with this script :
https://github.com/skydive-project/skydive/blob/master/scripts/ci/create-docker-image.sh

**Comment by idan-anner** [comment]
sudo scripts/ci/create-docker-image.sh

**Comment by hunchback** [comment]
@idan-anner - why are you using `sudo` ?

**Comment by idan-anner** [comment]
On my previous VM docker required sudo, this one doesnt, so sudo isnt necessary I suppose. Same result with or without it

**Comment by hunchback** [comment]
I ran on your machine - on docker I am getting the failure:

```
Step 7/14 : RUN apt-get -y update     && apt-get -y install software-properties-common     && add-apt-repository -y ppa:ubuntu-toolchain-r/ppa     && apt-get -y update     && apt-get -y install git make flex bison wget unzip golang libpcap0.8-dev npm          clang llvm zlib1g-dev liblzma-dev libc++-dev libc-dev linux-libc-dev libxml2-dev libvirt-dev     && rm -rf /var/lib/apt/lists/*
 ---> Running in 68ad1614b880
Err:1 http://security.ubuntu.com/ubuntu bionic-security InRelease
  Temporary failure resolving 'security.ubuntu.com'
Err:2 http://archive.ubuntu.com/ubuntu bionic InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Reading package lists...
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease  Temporary failure resolving 'security.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

While when I attempt to ping from your host - it works:

```
aidan@dmz-064:~/go/src/github.com/skydive-project/skydive$ ping security.ubuntu.com
PING security.ubuntu.com (91.189.91.23) 56(84) bytes of data.
64 bytes from economy.canonical.com (91.189.91.23): icmp_seq=1 ttl=51 time=130 ms
64 bytes from economy.canonical.com (91.189.91.23): icmp_seq=2 ttl=51 time=131 ms
64 bytes from economy.canonical.com (91.189.91.23): icmp_seq=3 ttl=51 time=130 ms
```

**Comment by hunchback** [comment]
@idan-anner - this may be related - https://forums.docker.com/t/cant-access-internet-after-installing-docker-in-a-fresh-ubuntu-18-04-machine/53416 - please check that your docker enables you to create a container and ping the internet from it (`ping 8.8.8.8` and `ping www.kernel.org` should work).

Address this first *before* attempting to build the skydive docker image

**Comment by nplanel** [comment]
@hunchback @idan-anner your docker network is not setup properly or some host iptables rules drop the container's packets

**Comment by hunchback** [comment]
yup - I see:

```
aidan@dmz-064:~/go/src/github.com/skydive-project/skydive$ docker run --rm -it arunvelsriram/utils bash
Unable to find image 'arunvelsriram/utils:latest' locally
latest: Pulling from arunvelsriram/utils
5b7339215d1d: Pull complete
14ca88e9f672: Pull complete
a31c3b1caad4: Pull complete
b054a26005b7: Pull complete
7c3d6c01ecda: Pull complete
3f7e9ce38e46: Pull complete
f32893bb62f2: Pull complete
9163d2407a75: Pull complete
Digest: sha256:c2c8cb9a5e8e25d644b19d756c458ac9375a5c652b099a21a54e9b88c4951a8a
Status: Downloaded newer image for arunvelsriram/utils:latest
root@73c46e6d3f67:/# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
^C
--- 8.8.8.8 ping statistics ---
9 packets transmitted, 0 received, 100% packet loss, time 8007ms

root@73c46e6d3f67:/#
```

**Comment by hunchback** [comment]
@idan-anner - please handle

**Comment by idan-anner** [comment]
The docker issue is fixed as far as I can tell, but am now getting the following error:
![image](https://user-images.githubusercontent.com/53993257/62832855-a2b04a00-bc3d-11e9-986d-aff73c883aeb.png)

**Comment by safchain** [comment]
Weird you build is using an ppa repo that we removed few weeks ago..
https://github.com/skydive-project/skydive/commit/bf59cb88b053be5039d11f394d7e0846fac30ae5#diff-17cf6e2f8ffdc014050de54a72876254

Can you check that you have a up-to-date skydive master branch and that you don't have ppa repo somewhere is the Dockerfile

**Comment by hunchback** [comment]
you can use cherry-pick if you want to continue using an older skydive base version:

```
git cherry-pick bf59cb88b053be5039d11f394d7e0846fac30ae5
```

**Comment by hunchback** [comment]
AFAIK issue has been resolved
