### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by eranra** [skydive-project/skydive#1959]
Hi @masco and @nplanel 

@masco the pull request from @nplanel and specifically the change to vendoring.json is breaking our build process look on: https://github.com/skydive-project/skydive/pull/1928/files#diff-bd290170e2912d3e8694db1a151066e5R2248

We are getting ```/home/daily_build/community/go/bin/govendor sync
\ # cd /home/daily_build/community/go/.cache/govendor/github.com/newtools/ebpf; git reset --hard 6469cf35d94268595c26d9ec4476df86e841f101
fatal: Could not parse object '6469cf35d94268595c26d9ec4476df86e841f101'.
\ # cd /home/daily_build/community/go/.cache/govendor/github.com/newtools/ebpf; git reset --hard 6469cf35d94268595c26d9ec4476df86e841f101
fatal: Could not parse object '6469cf35d94268595c26d9ec4476df86e841f101'.
\ # cd /home/daily_build/community/go/.cache/govendor/github.com/newtools/ebpf; git reset --hard 6469cf35d94268595c26d9ec4476df86e841f101
fatal: Could not parse object '6469cf35d94268595c26d9ec4476df86e841f101'.
Error: Remotes failed for:
	Failed for "github.com/newtools/ebpf" (failed to clone repo): exit status 128
	Failed for "github.com/newtools/ebpf/asm" (failed to sync repo to 6469cf35d94268595c26d9ec4476df86e841f101): exit status 128```

It looks like we need to change the ref commit from '6469cf35d94268595c26d9ec4476df86e841f101' to something else (maybe '8b7eaed02eb990819777ce4d627d593cecff5725')

**Comment by masco** [comment]
https://github.com/skydive-project/skydive/pull/1960

**Comment by hunchback** [comment]
fixed ... closing
