### ISSUE TITLE
413 error in security advisor exporter log

### ISSUE THREAD

**Issue by sa-cloud** [skydive-project/skydive#1972]
I use helm to install the skydive latest version on an k8s cluster v1.13 with the configuration below:

image:
repository: cognetive/skydive
tag: 2019.09.02___08.41

connector image:
registry.ng.bluemix.net/secadvisor_dev/skydive-secadvisor:12

env:
    - name: SKYDIVE_LOGGING_LEVEL
      value: "INFO"

    # Maximum number of flows per object
    - name: SKYDIVE_PIPELINE_STORE_S3_MAX_FLOWS_PER_OBJECT
      value: "60000"

    - name: SKYDIVE_PIPELINE_STORE_S3_MAX_SECONDS_PER_OBJECT
      value: "60"

    - name: SKYDIVE_PIPELINE_STORE_S3_MAX_FLOW_ARRAY_SIZE
      value: "100000"

    - name: SKYDIVE_PIPELINE_STORE_S3_MAX_SECONDS_PER_STREAM
      value: "86400"

    # Flows to be updated every 30 seconds (thus, every 60 seconds to defender)
    - name: SKYDIVE_FLOW_UPDATE
      value: "30"

    # ANALYZER_STARTUP_CAPTURE_GREMLIN invoke at startup capturing in selected nodes
    - name: SKYDIVE_ANALYZER_STARTUP_CAPTURE_GREMLIN
      value: "G.V().has('Name', NE('lo'))"

    - name: SKYDIVE_ANALYZER_STARTUP_CAPTURE_BPF
      value: "not (tcp dst port 8082 or tcp dst port 9000)"

    - name: SKYDIVEX_AGENT_CAPTURE_SYN
      value: "True"

    # DEFAULT_LAYER_KEY_MODE - the layers used to identify a unique flow.
    - name: SKYDIVE_FLOW_DEFAULT_LAYER_KEY_MODE
      value: "L3"

    - name: SKYDIVE_ANALYZER_STARTUP_CAPTURE_TYPE
      value: "pcap"

    - name: SKYDIVE_AGENT_CAPTURE_SYN
      value: "True"

I observed a repeating error in the connector log with status code 413 - payload too large. It repeated for 'internal' stream object. The rest of streams kept sending objects with no errors.
After a while I saw the kubernetes evicted the analyzer pod (event: "The node was low on resource: memory. Container skydive-sa-connector was using 1752916Ki, which exceeds its request of 0.") and a new pod was started. The error did not appear and objects were written to minio in all streams.

**Comment by hunchback** [comment]
@sa-cloud / @dubek - you reported to issues - regarding the 413 - please explain how was this log observed? also please copy to here the exact sequence of log messages

**Comment by dubek** [comment]
The HTTP 413 (Payload too large) error from Minio is due to a Kubernetes Ingress in front of that Minio instance that limits uploads to 1 MB.

However, this revealed a bug in the exporters (specifically in the store-to-S3 mechanism) that doesn't recover well from object store errors, and keeps growing in memory (until evicted by Kubernetes due to high memory usage). Supposedly there are mechanisms in place for such a scenario (`max_flow_array_size`) but they don't seem to do their job. Looking into this.

**Comment by safchain** [comment]
Closing it as flow exporter has been moved to a dedicated repo, feel free to open a new issue there if still relevant
