### ISSUE TITLE
Be able to do G.Flows().Has('Network', '...') that matches A and B

### ISSUE THREAD

**Issue by safchain** [skydive-project/skydive#200]
Sometimes we want the select a flow based on a IP or mac but not knowing if it is A or B, so it makes sense to have a way to match both ways.

**Comment by nlewo** [comment]
We could also do the same for Transport.

**Comment by safchain** [comment]
Sure make sense for all the layers

**Comment by eonpatapon** [comment]
Maybe reuse within for the key also:

```G.Flows().Has(within('Network.A', 'Network.B'), '...')```

**Comment by masco-enovance** [comment]
https://softwarefactory-project.io/r/#/c/6145/
