### ISSUE TITLE
How do manually add nodes/autodiscover nodes on my LAN and add them to the topology view?

### ISSUE THREAD

**Issue by pirate** [skydive-project/skydive#2000]
This is definitely a n00b question, but I've been quite confused while trying to follow the skydive tutorials so I figured I'd ask here in case the response can be used to improve the documentation.

I'm trying to use skydive to visualize the connections between a few servers I have in my LAN at home (and eventually a handful of remote servers and remote NATs).

I've installed skydive and have the web UI running, and I've created a few packet captures with:
```bash
./skydive client capture create --gremlin "G.V().Has('Name', 'eth0')" --type pcap
```

But the topology doesn't seem to update, it still only shows the single host node and none of the connections to the other servers.  How can I manually add nodes or set it up to auto-discover nodes on the LAN?  The documentation doesn't seem to provide any examples on this common use case, and the examples in `scripts/` seem to be all manually setting up brand new networks instead of visualizing the existing network.

![image](https://user-images.githubusercontent.com/511499/64896181-87719980-d644-11e9-8efc-dc7a6bd39411.png)

**Comment by safchain** [comment]
Many possibilities : 

1 - using the config file : https://github.com/skydive-project/skydive/blob/master/etc/skydive.yml.default#L84-L107

2 - using the CLI : http://skydive.network/blog/topology-rules.html

3 - using ansible : http://skydive.network/blog/ansible-library.html

4 - Python client lib : http://skydive.network/documentation/api-python

**Comment by pirate** [comment]
Ahh I had no idea that Skydive was expected to run on *every* node in the network.  I thought based on the guides http://skydive.network/tutorials/first-steps-3.html that it was supposed to autodiscover nodes based on traffic captures from a single node, with the option to add more nodes later to collect topology info from remote network segments.

**Comment by safchain** [comment]
Skydive discovers interfaces, containers, bridges, etc using mostly kernel API not using traffic in order to reduce as much as possible the impact of the monitoring. On top of the topology you can decide to capture packets in order to do traffic analysis. That said it is possible based on the traffic to build a topology, please have a look at : 
http://skydive.network/blog/flow-matrix.html

**Comment by safchain** [comment]
Closing for now, feel free to re-open if needed
