### ISSUE TITLE
Gremlin parser for completion

### ISSUE THREAD

**Issue by nlewo** [skydive-project/skydive#201]
To bring completion, we need to parse a Gremlin expression.
The parser should be able to parse partial gremlin expression in order to suggest completion terms.

Morevover, the AST generated by this parser could be use by the graph traversal functions.

**Comment by safchain** [comment]
Hi,

can you describe a bit how you plan to leverage the AST. It seems to me that an AST is not the best thing to use for completion. It's the result of the parser evaluation and in case of gremlin the AST will be close to what we have now: a list.

 A BNF parser will be maybe better ?

**Comment by lebauce** [comment]
Yes, it sounds more like a grammar. Maybe we could use https://godoc.org/golang.org/x/exp/ebnf

**Comment by nlewo** [comment]
I'm not sure we need to redefine the grammar since it is already done in `traversal_parser.go`.
Maybe it would be sufficient to improve the error handling in order to also return the set of expected values. These values could then be used to propose a completion list.

**Comment by nlewo** [comment]
I added the wip review https://softwarefactory-project.io/r/#/c/6255/1

**Comment by choleraehyq** [comment]
Hi @nlewo , is there any update about this?

**Comment by nlewo** [comment]
@choleraehyq No, but I finally made it in a python client https://github.com/nlewo/skydive-shell !

**Comment by lebauce** [comment]
Closing because of the availability of the python client and completion is provided in the Skydive CLI shell
