### ISSUE TITLE
Sflow counters

### ISSUE THREAD

**Issue by jtaleric** [skydive-project/skydive#204]
It would be awesome to capture the counters from sflow ( http://sflow.org/sflow_version_5.txt ). I wanted to use skydive to capture sflow from my ToRs and monitor the interfaces.

**Comment by lebauce** [comment]
https://github.com/google/gopacket does not support it yet

**Comment by dvandra** [comment]
> https://github.com/google/gopacket does not support it yet 

Is it supporting now?

**Comment by safchain** [comment]
Fixed: #1539
