### ISSUE TITLE
Conflicting web socket hostname: bad handshake

### ISSUE THREAD

**Issue by Sparika** [skydive-project/skydive#2044]
**My situation is as follows:**
I have a Kubernetes cluster running on a baremetal host. I'm deploying skydive using the example service in the documentation. However, I would like to also collect the topology from the baremetal host by deploying a Skydive agent on it. The k8s agent is running runc and docker probes, but it appears to have no visibility on the baremetal resources.

**Observed issue:**
In addition to the k8s deployment, when running `SKYDIVE_ANALYZERS=localhost:30273 ./skydive agent -c skydive.baremetal.yaml` I get a bad-handshake error:
```
2019-10-04T07:51:21.989Z        ERROR   websocket/client.go:569 (*Client).Start.func1   ubuntu-host: Unable to create a WebSocket connection ws://127.0.0.1:30273/ws/agent/topology : websocket: bad handshake
```

If I do `kubectl delete pod skydive-agent-g58c7`, the baremetal agent then manage to connect. I believe the two agent have conflicting web-socket X-Host-ID as both k8s and baremetal agent seems to have the same hostname.

skydive/websocket/client.go: 491
```
// Connect to the server
func (c *Client) Connect() error {
	var err error
	endpoint := c.URL.String()
	headers := http.Header{
		"X-Host-ID":             {c.Host},
		"Origin":                {endpoint},
		"X-Client-Type":         {c.ServiceType.String()},
		"X-Client-Protocol":     {c.ClientProtocol.String()},
		"X-Websocket-Namespace": {WildcardNamespace},
	}
```

**Expected:**
I would have expected to be able to deploy the baremetal agent in addition to the k8s agent. 

However, I may have a wrong expectation here. Could you clarify whether there would be a way to have visibility on baremetal topology from the k8s agent or if I should only deploy a skydive agent on the baremetal host? 

Thanks for the help

**Comment by safchain** [comment]
Hi,

Do you mean that you deployed Skydive using this ? 
https://github.com/skydive-project/skydive/tree/master/contrib/kubernetes

Skydive agent are started using a daemonset so you should see baremetal entities + containers/namespaces, etc...

Agents are identified by there host_id and as to be unique per agent
https://github.com/skydive-project/skydive/blob/master/etc/skydive.yml.default#L4

do your baremetal machines have the same hostname ?

Thanks

**Comment by Sparika** [comment]
Thanks for the quick response. For the moment, I only have one baremetal machine, but its hostname is both used by the agent running on it and the one launched by the kubernetes daemonset.

Indeed, I missed the host ID parameter in the configuration file. And then I had one additional probe (ovsdb) running in the baremetal agent which let me think it had more visibility on the host. 

So my issue is resolved.

**Comment by safchain** [comment]
Thanks, just a side note :) we are working a new version of the WebUI so in a short term we will provide a better topology view.
