### ISSUE TITLE
System get flooded with openvswitch mount points after restarting skydive agent container

### ISSUE THREAD

**Issue by tu-pm** [skydive-project/skydive#2069]
I'm reporting a bug.

**Version**: 0.22
**Deployment environment**: Skydive cluster running inside Docker containers as part of kolla-ansible deployment
**Description**: The total number of mount points to `/run/openvswitch` grows exponentially each time the `skydive-agent` container restarts

```
[root@server214 ~]# cat /proc/mounts | grep /run/openvswitch |wc -l
31
[root@server214 ~]# docker restart skydive_agent                                                                                                      
skydive_agent
[root@server214 ~]# cat /proc/mounts | grep /run/openvswitch |wc -l
63
[root@server214 ~]# docker restart skydive_agent                                                                                                      
skydive_agent
[root@server214 ~]# cat /proc/mounts | grep /run/openvswitch |wc -l
127
```

**Comment by safchain** [comment]
Hi,

It seems to be more related to kolla images than Skydive itself. I would suggest to open a bug here: https://launchpad.net/kolla.

Thanks

**Comment by tu-pm** [comment]
Yeah, silly me, closing.
