### ISSUE TITLE
addmulticast bug

### ISSUE THREAD

**Issue by qinze118** [skydive-project/skydive#2087]
when I used lldp probe capture the packets but It doesn't  work. I tried change your code then It works fine! the version of my system is centos(7 or 6.4).
Old code:
	var sockaddr syscall.RawSockaddr
	// RawSockaddr.Data is []int8 on amd64 and []uint8 on ppc64le
	switch data := interface{}(sockaddr.Data).(type) {
	case [14]int8:
		for i, n := range mac {
			data[i] = int8(n)
		}
	case [14]uint8:
		for i, n := range mac {
			data[i] = uint8(n)
		}
	}

New code:
   	sockaddr := syscall.RawSockaddr{}
	for i,n := range mac {
		sockaddr.Data[i] = int8(n)
	}

**Comment by safchain** [comment]
hi @qinze118 do you plan to submit a PR ?

**Comment by qinze118** [comment]
h1 @safchain I submitted

**Comment by safchain** [comment]
Fixed: https://github.com/skydive-project/skydive/commit/d9d804ddf0b67c99e1f3b3b4e987655b8f6f94cd
