### ISSUE TITLE
Pcap capture button isn't visible

### ISSUE THREAD

**Issue by TommyHwang** [skydive-project/skydive#2095]
Hi.

I installed skydive using kubernetes yaml.

![pcap](https://user-images.githubusercontent.com/20712117/68018313-2bd69a80-fcdc-11e9-8a96-2b80fb9f3249.png)

When I clicked my flow, I found that RawPacketsCaptured is 0 and there is no download button.

![image](https://user-images.githubusercontent.com/20712117/68018565-c8993800-fcdc-11e9-9641-b72662122bba.png)

Is there any condition for pcap capture?

**Comment by masco** [comment]
Hi, You need to mention how many numbers of raw packets you want to capture while creating/starting the capture.
by default, it is zero so you won't get any raw packets unless you specify it explicitly.
you can find the number of raw packets options in 'advance options' sections while creating capture.

**Comment by TommyHwang** [comment]
> Hi, You need to mention how many numbers of raw packets you want to capture while creating/starting the capture.
> by default, it is zero so you won't get any raw packets unless you specify it explicitly.
> you can find the number of raw packets options in 'advance options' sections while creating capture.

Thank you. But I can't find number option in Advanced Option menu.

Is there any version issue about it?

![image](https://user-images.githubusercontent.com/20712117/68021082-d1d9d300-fce3-11e9-886e-2d404c9fecd7.png)

**Comment by masco** [comment]
can you set the permission for rawpackets in the rbac policy and try
https://github.com/skydive-project/skydive/blob/master/rbac/policy.csv

**Comment by safchain** [comment]
@masco I don't think this is the main problem, the if statement in the vuejs component doesn't seem to be correct. 

https://github.com/skydive-project/skydive/blob/master/statics/js/components/capture-form.js#L89

About to submit a fix

**Comment by safchain** [comment]
here the PR: 
https://github.com/skydive-project/skydive/pull/2097

**Comment by TommyHwang** [comment]
> Hi, You need to mention how many numbers of raw packets you want to capture while creating/starting the capture.
> by default, it is zero so you won't get any raw packets unless you specify it explicitly.
> you can find the number of raw packets options in 'advance options' sections while creating capture.

Hi. Thank you for your help and I have a question.

I'm using image named skydive/skydive:master in Docker hub.
I entered in skydive-analyzer container in skydive-analyzer pod using exec command,
But I couldn't find any js file or configuration file.

How can I fix it?

**Comment by safchain** [comment]
The config should be here `/etc/skydive.yml`
https://github.com/skydive-project/skydive/blob/master/contrib/docker/Dockerfile#L8

Otherwise you can override config variable through environment variable lilke

`SKYDIVE_ANALYZER_LISTEN=0.0.0.0:8082` for this line 
https://github.com/skydive-project/skydive/blob/master/etc/skydive.yml.default#L49

meaning prefixing with `SKYDIVE_`, adding `_` per sub key in capital letter

**Comment by TommyHwang** [comment]
> The config should be here `/etc/skydive.yml`
> https://github.com/skydive-project/skydive/blob/master/contrib/docker/Dockerfile#L8
> 
> Otherwise you can override config variable through environment variable lilke
> 
> `SKYDIVE_ANALYZER_LISTEN=0.0.0.0:8082` for this line
> https://github.com/skydive-project/skydive/blob/master/etc/skydive.yml.default#L49
> 
> meaning prefixing with `SKYDIVE_`, adding `_` per sub key in capital letter

Thank you for your help, I got full advanced option menu. As you replied, the permission might have caused the hide of menu.
