### ISSUE TITLE
How to change port 8082 in 'http://localhost:8082' to others?

### ISSUE THREAD

**Issue by jibanli** [skydive-project/skydive#2115]
When opening a browser to http://localhost:8082 to access the analyzer Web UI,  I find that port 8081 and 8082 are occupied using the command 'netstat -tulpn' in the terminal.

I want to know how to change the port 8081 and 8081 to other ports like 6xxx or 7xxx?

**Comment by TommyHwang** [comment]
I think you can change your port through change your skydive.yml.
Please see below links:
https://github.com/skydive-project/skydive/blob/master/etc/skydive.yml.default#L179
https://github.com/skydive-project/skydive/blob/master/etc/skydive.yml.default#L182

**Comment by TommyHwang** [comment]
> When opening a browser to http://localhost:8082 to access the analyzer Web UI, I find that port 8081 and 8082 are occupied using the command 'netstat -tulpn' in the terminal.
> 
> I want to know how to change the port 8081 and 8081 to other ports like 6xxx or 7xxx?

I think you can change your port through change your skydive.yml.
Please see below links:
https://github.com/skydive-project/skydive/blob/master/etc/skydive.yml.default#L179
https://github.com/skydive-project/skydive/blob/master/etc/skydive.yml.default#L182

**Comment by safchain** [comment]
Closing this one as @TommyHwang  gave the right answer, thanks
