### ISSUE TITLE
Native aarch64, ppc64le, s390x support?

### ISSUE THREAD

**Issue by hrw** [skydive-project/skydive#2121]
Travis CI supports aarch64, ppc64le, s390x now so maybe it is time to switch and generate binaries for all archs?

Would probably require bumping protoc version to something newer with binaries for all those architectues (3.11.1 has them).

**Comment by safchain** [comment]
This is not directly binary but docker image for these arch are generated : 
https://hub.docker.com/r/skydive/skydive/tags

It is generated by this script by the CI :
https://github.com/skydive-project/skydive-ci/blob/master/scripts/create-docker-image.sh

**Comment by hrw** [comment]
In OpenStack Kolla we use that binary for own images :D 
Anyway if some user will want to run it on non-x86 then they will have an option.

Thanks.
