### ISSUE TITLE
Does Packets captured by ebpf.go through the protocol stack?

### ISSUE THREAD

**Issue by marshalWS** [skydive-project/skydive#2123]
Does Packets captured by ebpf.go through the protocol stack?
That is to say,  packets captured by ebpf.go  before or after  skb?

**Comment by nplanel** [comment]
We bind the bpf program to socket_info on raw_socket
So basically we hooked on all packets in/out of the network stack.

If you looking for better performance for monitoring only, you can use/setup Skdyive DPDK probe, binded to your NIC.

More info on ebpf : https://blogs.oracle.com/linux/notes-on-bpf-1

**Comment by marshalWS** [comment]
> We bind the bpf program to socket_info on raw_socket
> So basically we hooked on all packets in/out of the network stack.
> 
> If you looking for better performance for monitoring only, you can use/setup Skdyive DPDK probe, binded to your NIC.
> 
> More info on ebpf : https://blogs.oracle.com/linux/notes-on-bpf-1

thanks，i got  it.

**Comment by marshalWS** [comment]
> We bind the bpf program to socket_info on raw_socket
> So basically we hooked on all packets in/out of the network stack.
> 
> If you looking for better performance for monitoring only, you can use/setup Skdyive DPDK probe, binded to your NIC.
> 
> More info on ebpf : https://blogs.oracle.com/linux/notes-on-bpf-1

thanks，i get it.

**Comment by safchain** [comment]
Closing it for now, feel free to re-open if needed
