### ISSUE TITLE
Autorest dependency causes build to fail

### ISSUE THREAD

**Issue by sempervictus** [skydive-project/skydive#2125]
```
skydive(master)$ make
fatal: Couldn't JIT the PCRE2 pattern '//go:generate', got '-48'

fatal: Couldn't JIT the PCRE2 pattern '//go:generate', got '-48'

fatal: Couldn't JIT the PCRE2 pattern '//go:generate', got '-48'

go mod download
go: github.com/networkservicemesh/networkservicemesh/controlplane/api@v0.2.0 requires
	github.com/networkservicemesh/networkservicemesh/pkg@v0.2.0 requires
	github.com/spiffe/spire@v0.0.0-20190515205011-c8123525fba8 requires
	contrib.go.opencensus.io/exporter/ocagent@v0.4.6 requires
	github.com/census-instrumentation/opencensus-proto@v0.1.0-0.20181214143942-ba49f56771b8: invalid pseudo-version: version before v0.1.0 would have negative patch number
make: *** [Makefile:154: moddownload] Error 1
```

Looks like [we arent the first to be bitten by this](https://www.gitmemory.com/issue/Azure/go-autorest/449/520897732). Anyone else seeing the problem? I'm on Arch, so golang is `go version go1.13.5 linux/amd64`.
The PCRE failures are odd - i threw pax in softmode and still seeing that, but i doubt its related given what MSFT said in their[ github issue](https://github.com/Azure/go-autorest/issues/449)

**Comment by safchain** [comment]
Hi, thanks for reporting this issue. I just submitted a fix:
https://github.com/skydive-project/skydive/pull/2124/commits/c5c30ceb888fa9dd2d6a2825c1fff6f4b872074b

**Comment by sempervictus** [comment]
Thank you, adding diff to my PKGBUILD and testing

**Comment by sempervictus** [comment]
Confirm that it works.
What's weird is that the PKGBUILD process pulls from master, but this commit was not showing up yet, i had to explicitly add it via `#commit=c5c30ceb888fa9dd2d6a2825c1fff6f4b872074b` notation in the `source` section. Might just be lag on GH side.

**Comment by safchain** [comment]
The commit is part of a PR that is not merge yet. 

For the /tmp use I think that is a Go thing, I do not see specific thing that we do in the build process. Did you try to set the TMPDIR env variable ?

**Comment by safchain** [comment]
The fix has been merged. part of master now.
