### ISSUE TITLE
RawPacketsCaptured Download button is not worked

### ISSUE THREAD

**Issue by TommyHwang** [skydive-project/skydive#2131]
Hi.

I'm using Skydive in on-premise environment.

And I just found that RawPacketsCaptured Download button is not worked.

![image](https://user-images.githubusercontent.com/20712117/71704499-1f76d700-2e1e-11ea-8eba-ede1108994ad.png)

![image](https://user-images.githubusercontent.com/20712117/71704516-31587a00-2e1e-11ea-91ac-8deae02c3f69.png)

I tried to write "self.$downloadRawPackets(flow.UUID);" below "var links = {};", and it worked.

So it seems that onClick event is not registered.

Is there any additional setup for that? Or is it a ui configuration problem?

Raw packets limit in advanced capture option was 10.

**Comment by lebauce** [comment]
Sorry for taking SO LONG to answer. Should be fixed by https://github.com/skydive-project/skydive/pull/2355
