### ISSUE TITLE
EBPF TCP flags start times always 0

### ISSUE THREAD

**Issue by tyguik** [skydive-project/skydive#2136]
I wanted to get the tcp flags times when using Ebpf but it is always return 0 and after some digging I discovered that in ebpf/common.h there is a function that suppose to init the flags times but the line 
`__u64 tm = flow->last;` in the function inits tm with 0 every time.
As a work around I change the func to init tm with 1 and then I can get an indication that the flag was raised because that all I needed but I there is a way to understand why flow->last dont work I think that would sold the issue.

**Comment by safchain** [comment]
I submitted a fix, can you give it a try
#2151

**Comment by tyguik** [comment]
Still doesn't work :(

**Comment by safchain** [comment]
would you be able to send a PR ? or can you point me the exact line ?

**Comment by tyguik** [comment]
I tried to upload a new branch but I don't have permissions.
I just move line 242 to be above line 230 in ebpf/flow.c

**Comment by safchain** [comment]
could you try this one :
https://github.com/skydive-project/skydive/pull/2153

**Comment by safchain** [comment]
Closing it, please re-open if needed
