### ISSUE TITLE
Skydive Crashes when using ebpf mode after a while 

### ISSUE THREAD

**Issue by liatush1988** [skydive-project/skydive#2141]
Hi,
When running Skydive with ebpf mode, Skydive crashes after a while due to nil pointer reference. 
This is the log:
skydive[50717]:panic: runtime error: invalid memory address or nil pointer dereference
skydive[50717]:[signal SIGSEGV: segmentation violation code=0x1 (...)
skydive[50717]: skydive/src/github.com/skydive-project/skydive/flow.isABPacket
skydive/src/github.com/skydive-project/skydive/flow/ebpf.go:302

**Comment by safchain** [comment]
Thanks for reporting this, I'm going to have a look

**Comment by safchain** [comment]
I submitted a fix, can you give it a try
#2136

**Comment by safchain** [comment]
Closing it, please re-open if needed
