### ISSUE TITLE
Make graph element persistent by default

### ISSUE THREAD

**Issue by safchain** [skydive-project/skydive#2204]
- [ ] Add pod entry in etcd with a kind of TTL in order to trigger a del host graph
- [ ] Remove clean up mechanism in storage on start in order to make graph element persistent by default
- [ ] re-inject non deleted graph element from storage on start using the storage master election
- [ ] add CLI/API mechanism to delete graph element based on a gremlin expression

**Comment by lebauce** [comment]
https://github.com/skydive-project/skydive/pull/2221
