### ISSUE TITLE
Go client for skydive APIs 

### ISSUE THREAD

**Issue by adrianlzt** [skydive-project/skydive#2212]
I am trying to use the skydive lib as the client to connect to the APIs, as do the python skydive-client.

The ``go get`` command fails to download skydive:
```
✦ ➜ go mod init test.com/skydive
go: creating new go.mod: module test.com/skydive
✦ ➜ go get github.com/skydive-project/skydive
go: github.com/skydive-project/skydive upgrade => v0.26.0
go get: github.com/skydive-project/skydive@v0.26.0 requires
        k8s.io/api@v0.0.0: reading k8s.io/api/go.mod at revision v0.0.0: unknown revision v0.0.0
```

Once this working. Which client should be used?

[Websocket](https://pkg.go.dev/github.com/skydive-project/skydive@v0.26.0/websocket?tab=doc)?

[API REST](https://pkg.go.dev/github.com/skydive-project/skydive@v0.26.0/api/client?tab=doc) client? This one looks appropiate, but it is not clear where to put the config.

**Comment by adrianlzt** [comment]
Is it possible to modify the topology using the REST API?

**Comment by lebauce** [comment]
It's now possible thanks to this PR : https://github.com/skydive-project/skydive/pull/2139

You should be able to use PUT on /api/node and /api/edge

**Comment by lebauce** [comment]
We do not rely use the REST API from Go in Skydive (we mostly use WebSocket) except in our tests : https://github.com/skydive-project/skydive/blob/master/tests/tests.go#L487

**Comment by adrianlzt** [comment]
Ok great.
I leave the issue open as it is still not possible to use github.com/skydive-project/skydive as a module

**Comment by lebauce** [comment]
Now that `graffiti` is completely separated into its own go module with its own go.mod, you should be able to `go get` it. If so, could we close this one ?
