### ISSUE TITLE
what is the skydive release mechanism

### ISSUE THREAD

**Issue by ajaykumar7-ibm** [skydive-project/skydive#2220]
Can somebody help me to understand the release mechanism of skydive. How does it happen?
Any helpful doc?
We have some requirements. Need this information.

**Comment by lebauce** [comment]
When the team decides a new version is ready, we create a tag. Then we manually trigger this CI job : https://github.com/skydive-project/skydive-ci/blob/master/jenkins/deliverables.yml#L1-L44
It builds the docker images, RPM, binaries, create the Github release and upload the release artifacts.

**Comment by safchain** [comment]
Closing it for now, don't hesitate to re-open if needed
