### ISSUE TITLE
Question about Skydive using Neo4j

### ISSUE THREAD

**Issue by quangtamle** [skydive-project/skydive#2239]
Hello everyone,

As far as I am concerned, Skydive does not support Neo4j. I am curious why it does not support Neo4j in the beginning.

If I want to implement a module (plugin) to use Neo4j, is there any problems? or what should I focus on when I do the implementation?

Thank you in advance

**Comment by safchain** [comment]
We did support Neo4j but we decided to remove the support for multiple reasons. It was not enough fast regarding the number of update we wanted to handle, we needed an event based graph and we wanted to add the history support. That is some of the reasons why at that time we decided to not support it anymore. You can have a look at the Gremlin backend we were using:
https://github.com/skydive-project/skydive/blob/5d629e372314825f3540610938af16703279d73c/topology/graph/gremlin.go

**Comment by safchain** [comment]
Closing it for now, feel free to re-open if needed
