### ISSUE TITLE
Elasticsearch backend: missing disable_sniffing in default config

### ISSUE THREAD

**Issue by adrianlzt** [skydive-project/skydive#2246]
In this [commit](https://github.com/skydive-project/skydive/commit/36982a150371cd553357fd6c36ac682c76b52f36) the option ``disable_sniffing`` was added, but not included in the default [config file](https://github.com/skydive-project/skydive/blob/9fdfbd87045ae9f4fd85330e3574c7e4e61c0279/etc/skydive.yml.default#L384)

**Comment by lebauce** [comment]
Fixed
