### ISSUE TITLE
cmd basic authorization bug

### ISSUE THREAD

**Issue by znscn** [skydive-project/skydive#2247]
First I enable api auth with basic backend, then use cmd to create a capture with TTL, the client reports error: 

>    "2020-07-06T18:25:56.107+0800    ERROR   client/client.go:64 exitOnError ubu1804: Failed to create capture, 401 Unauthorized: 401 Unauthorized"

   for example:  

> skydive client capture create --username admin --password admin --analyzer 192.168.1.1:8082 --gremlin "G.V().Has('Name', 'tap1974bfbf-32', 'Type', 'tun')" --ttl 60000

The patch to fix it.
```
diff --git a/graffiti/http/client.go b/graffiti/http/client.go
index f179ea52..b3626a00 100644
--- a/graffiti/http/client.go
+++ b/graffiti/http/client.go
@@ -94,13 +94,14 @@ func (c *RestClient) Request(method, path string, body io.Reader, header http.He
 		return nil, err
 	}
 
+	if header != nil {
+		req.Header = header
+	}
+
 	if c.authOpts != nil {
 		SetAuthHeaders(&req.Header, c.authOpts)
 	}
 
-	if header != nil {
-		req.Header = header
-	}
 	if req.Header.Get("Content-Type") == "" {
 		req.Header.Set("Content-Type", "application/json")
 	}
```

**Comment by lebauce** [comment]
Sorry, I completely missed this one. Thank you for reporting the issue and providing the fix !

https://github.com/skydive-project/skydive/pull/2279
