### ISSUE TITLE
Flows gremlin step Limit() has no impact when after Sort().Dedup()

### ISSUE THREAD

**Issue by kdorfman** [skydive-project/skydive#225]
To reproduce, compare:
skydive client topology query --gremlin="G.V().Flows().Limit(1)"
vs.
skydive client topology query --gremlin="G.V().Flows().Dedup().Limit(1)"
skydive client topology query --gremlin="G.V().Flows().Sort().Limit(1)"
skydive client topology query --gremlin="G.V().Flows().Sort().Dedup().Limit(1)"

**Comment by masco-enovance** [comment]
https://softwarefactory-project.io/r/#/c/6933/
