### ISSUE TITLE
Unable to install using go get

### ISSUE THREAD

**Issue by micruzz82** [skydive-project/skydive#2253]
When I try to install using go get, I get the following error:

go get github.com/skydive-project/skydive
package github.com/networkservicemesh/networkservicemesh/controlplane/api/local/connection: cannot find package "github.com/networkservicemesh/networkservicemesh/controlplane/api/local/connection" in any of:
        /root/.go/src/github.com/networkservicemesh/networkservicemesh/controlplane/api/local/connection (from $GOROOT)
        /root/go/src/github.com/networkservicemesh/networkservicemesh/controlplane/api/local/connection (from $GOPATH)
package github.com/networkservicemesh/networkservicemesh/controlplane/api/remote/connection: cannot find package "github.com/networkservicemesh/networkservicemesh/controlplane/api/remote/connection" in any of:
        /root/.go/src/github.com/networkservicemesh/networkservicemesh/controlplane/api/remote/connection (from $GOROOT)
        /root/go/src/github.com/networkservicemesh/networkservicemesh/controlplane/api/remote/connection (from $GOPATH)

Any advise on what I need to do?

Thanks in advance.

**Comment by safchain** [comment]
Currently we don't support `go get` to build Skydive as it doesn't rely only on go. Please have a look at this documentation
http://skydive.network/documentation/build

**Comment by micruzz82** [comment]
Thank you for this. I have used manual install.
