### ISSUE TITLE
Unable to download the pcap file after capture from agent

### ISSUE THREAD

**Issue by micruzz82** [skydive-project/skydive#2254]
I have run a capture between 2 nodes however when I go to download the pcap nothing happens. I have checked issue: https://github.com/skydive-project/skydive/issues/805 however I don't have a firewall in between the 2 hosts as they are in the same subnet.

![image](https://user-images.githubusercontent.com/24628054/87250873-df914c00-c45f-11ea-9025-9c42061db68d.png)

Any advice on what I need to do to allow the pcap file to be able to download it.

Thanks for your help.

**Comment by nk-akun** [comment]
I also met the same problem, have you solved it?

**Comment by lebauce** [comment]
Sorry for taking so long to answer. Should be fixed by https://github.com/skydive-project/skydive/pull/2355
