### ISSUE TITLE
How can i use rest api through postman?

### ISSUE THREAD

**Issue by Gzure** [skydive-project/skydive#226]
I want to get http://localhost:8082/api/topology,but it need a token.I don't know how can i get a token

**Comment by safchain** [comment]
Hi,

you can either use basic auth on each request : 

curl -u username:password http://localhost:8082/api/topology

or 

get a auth token using the login endpoint, the token is returned as cookie(authtok)
curl -v -XPOST http://localhost:8082/login --data "username=safchain&password=toto

then use it : 

curl -v --cookie "authtok=c2FmY2hhaW46dG90bw==" http://localhost:8082/api/topology

**Comment by safchain** [comment]
Closing this one, will re-open it if needed
