### ISSUE TITLE
ovn probe: Probe fails to start when there are too many objects

### ISSUE THREAD

**Issue by amorenoz** [skydive-project/skydive#2275]
When enabling the ovn probe on a cluster, it can potentially deadlock on initialization.

The reason seems to be that the probe [first creates the go-ovn.Client](
https://github.com/skydive-project/skydive/blob/f8ce980a15d54d3ecdcbe48570c3a322a53193d6/topology/probes/ovn/ovn.go#L475), and then[ creates the goroutine that processes the callbacks](https://github.com/skydive-project/skydive/blob/f8ce980a15d54d3ecdcbe48570c3a322a53193d6/topology/probes/ovn/ovn.go#L516).
However, the go-ovn Client constructor, [will internally try to populate the initial cache](https://github.com/eBay/go-ovn/blob/da67e9744ec05bf817ef2de7128971f235b921c3/client.go#L243) which can trigger a potentially large number of callbacks. Since the processing goroutine has not been created yet, if the number of callbacks exceed 50 [(the size of the buffered event channel)](https://github.com/skydive-project/skydive/blob/f8ce980a15d54d3ecdcbe48570c3a322a53193d6/topology/probes/ovn/ovn.go#L544), the main thread will never return from the go-ovn Client constructor.

In my testing, the issue disappears by moving the creation of the event-processing go-routine to the top of the function (before calling go-ovn.NewClient).

I'd happily send a PR with that fix if it's considered a viable solution, or try to implement any alternative approach that is suggested.

**Comment by amorenoz** [comment]
@lebauce This issue is still happening.

**Comment by lebauce** [comment]
Really fixed by https://github.com/skydive-project/skydive/pull/2288
