### ISSUE TITLE
ovs: patch interfaces are not connected to ovsports

### ISSUE THREAD

**Issue by amorenoz** [skydive-project/skydive#2292]
In openvswitch, the object relationship is: Bridge -> Port -> Interface, for example:
```
ovs-vsctl show 
cca2fe68-daa6-49f5-8e51-b1a8e5f333ee
    Bridge br-local
        Port br-local
            Interface br-local
                type: internal
        Port patch-lnet-node_local_switch-to-br-int
            Interface patch-lnet-node_local_switch-to-br-int
                type: patch
                options: {peer=patch-br-int-to-lnet-node_local_switch}
        Port ovn-k8s-gw0
            Interface ovn-k8s-gw0
                type: internal
```

I would expect this relationship to be translated into gremlin so, "ovsport" Nodes should have edges going to the different kind of interfaces like:
Edges:
"ovsbridge" -> "ovsport"
"ovsport" -> "veth"
"ovsport"->"patch"
"ovsport"->"geneve"

While this holds true for geneve and veth: e.g:
```

$ skydive client query "G.V().Has('Type', 'geneve').In().Values('Type').Dedup()"
[
        "ovsport",
        "ovsbridge",
        "host"
]
.$ skydive client query "G.V().Has('Type', 'veth').In().Values('Type').Dedup()"
[
        "ovsport",
        "host",
        "veth",
        "netns"
]

```
It's not true for "patch" interfaces:
```
$ skydive client query "G.V().Has('Type', 'patch').In().Values('Type').Dedup()"
[
        "ovsbridge",
        "patch"
]

$ skydive client query "G.V().Has('Type', 'ovsport').Out().Values('Type').Dedup()"
[
        "internal",
        "geneve",
        "veth"
]
```

Glancing over the code this it doesn't seem to be the intended behaviour, so I'd say is a bug.

**Comment by lebauce** [comment]
On my test setup, I do have some ovsport -> patch link so that may be a race issue. Could you please send a dump of the topology `skydive client topology export` ?

I'm also wondering if the issue could be related (fixed ?) by https://github.com/skydive-project/skydive/pull/2294

**Comment by safchain** [comment]
There is indeed an issue the port of the patch interface is not created, at least on my setup, I have a reproducer. I'll try to fix this.

**Comment by safchain** [comment]
The patch pointed by @lebauce fixed the issue on my side.

**Comment by amorenoz** [comment]
@safchain, @lebauce 
PR  #2294 does solve the issue:
```
$ skydive client query "G.V().Has('Type', 'ovsport').Out().Values('Type').Dedup()"
[
        "patch",
        "internal",
        "veth",
        "geneve"
]
$ skydive client query "G.V().Has('Type', 'patch').Out().Values('Type').Dedup()"
[
        "patch"
]

$ skydive client query "G.V().Has('Type', 'patch').In().Values('Type').Dedup()"
[
        "patch",
        "ovsbridge",
        "ovsport"
]

```

**Comment by amorenoz** [comment]
Thanks!
