### ISSUE TITLE
released binary not printing the version version properly

### ISSUE THREAD

**Issue by amorenoz** [skydive-project/skydive#2309]
The lastest release (as of Dec 15 2020) does not print the version properly.

## How to reproduce:
```
$ curl -Lo - https://github.com/skydive-project/skydive-binaries/raw/jenkins-builds/skydive-latest.gz 2>/dev/null | gzip -d > skydive && chmod +x skydive && ./skydive version
./skydive github.com/skydive-project/skydive 
```
I was expecting a version or git commit to be printed

**Comment by lebauce** [comment]
The bug was due to shallow cloning the git repository. Should be fixed now
