### ISSUE TITLE
allinone does not support changing the analyzer port

### ISSUE THREAD

**Issue by tmmorin** [skydive-project/skydive#231]
The following configuration does not work with "skydive allinone -c <config>":

```
analyzer:
  # address and port for the analyzer API, Format: addr:port.
  # Default addr is 127.0.0.1
  listen: 0.0.0.0:8087

analyzers:
  - 127.0.0.1:8087
```

Error:

`2017-03-16T11:36:53.22+01:00 fullstack-00:agent wsclient.go:125 http (*WSAsyncClient).connect > ERRO 09c Unable to create a WebSocket connection ws://127.0.0.1:8082/ws : Authentication failed: dial tcp 127.0.0.1:8082: getsockopt: connection refused`

The agent is still trying to connect on port 8082 although the analyzer is running on port 8087.

The culprit is this line in allinone.go: https://github.com/skydive-project/skydive/blob/e6cdba914d8ceac319c56d4619c3836be8f2adb9/cmd/allinone.go#L83

Changing the port to 8087 at this line solves the issue, but of course a good fix would consist in parsing the config and use the configured port.

**Comment by lebauce** [comment]
https://softwarefactory-project.io/r/7202
