### ISSUE TITLE
0.27.0 binary release panic

### ISSUE THREAD

**Issue by adrianlzt** [skydive-project/skydive#2329]
If I try to run the [v0.27.0 skydive binary release](https://github.com/skydive-project/skydive/releases/download/v0.27.0/skydive) (md5sum 522a8b32891a9b0cc268c4aac4590d4a, downloaded twice) give a fatal error:
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe5 pc=0x7faba2758e84]
```
[Full error](https://github.com/skydive-project/skydive/files/5841382/skydive_faltal_error.txt)

I am usign kernel 5.10.8-arch1-1.

If I build locally from the v0.27.0 tag it runs correctly.

**Comment by carroarmato0** [comment]
Can confirm, getting the same issue.
5.8.0-41-generic #46-Ubuntu

**Comment by lebauce** [comment]
Not sure this is related to the kernel version but more to glibc. I did try on Ubuntu with the same kernel as you @carroarmato0 and I did not have the issue. Were you using Focal ? I pushed this PR to address the problem though : https://github.com/skydive-project/skydive/pull/2339

**Comment by carroarmato0** [comment]
> Not sure this is related to the kernel version but more to glibc. I did try on Ubuntu with the same kernel as you @carroarmato0 and I did not have the issue. Were you using Focal ? I pushed this PR to address the problem though : #2339

I'm using 20.10
I ended up building from the tag myself just like @adrianlzt

**Comment by lebauce** [comment]
I did try on 20.10 and had the same issue but you were faster to answer :-)
I confirm that the fix I pushed solves the issue

**Comment by adrianlzt** [comment]
Should we leave this open for reference until next binary release?

**Comment by lebauce** [comment]
Yes, good point. The binaries at https://github.com/skydive-project/skydive-binaries/ should be already be fixed though
