### ISSUE TITLE
Collapsed display doesn't persist when playing with the time slider

### ISSUE THREAD

**Issue by matrohon** [skydive-project/skydive#233]
after collapsing a node, if the user gets back with the time slider, the UI doesn't persist the fact that the node was collapsed. The node is expanded. However the collapse/expand button switcher at the bottom left of the UI proposes to expand the node.

**Comment by matrohon** [comment]
![untitled](https://cloud.githubusercontent.com/assets/1970121/24296886/2a0e8d40-10a1-11e7-87f3-c6391bb03e4b.png)

**Comment by safchain** [comment]
Closing, new WebUI will handle this
https://github.com/skydive-project/skydive-ui
