### ISSUE TITLE
etcd: set default values for wal and snap files

### ISSUE THREAD

**Issue by adrianlzt** [skydive-project/skydive#2337]
etcd configures a [default value](https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/configuration.md#--max-snapshots) of 5 snap files and 5 wal files.

I think is safer to have those defaults than having zero on those values and fill the disk with wal and snap files.

**Comment by lebauce** [comment]
Fixed by https://github.com/skydive-project/skydive/pull/2340
