### ISSUE TITLE
replace etcd with k8s apiserver backed by etcd

### ISSUE THREAD

**Issue by hunchback** [skydive-project/skydive#2344]
would it be possible to replace etcd with the k8s etcd (which is accessed via the apiserver)?

could we use k8s CRDs to define the captures (and other etcd backed resources)?

would this provide benefits in the multi-cluster use case?

**Comment by lebauce** [comment]
It's probably feasible. That being said, we would still need to support etcd for non k8s deployments so it means more maintenance for a small team so I don't see this happening anytime soon :-(
