### ISSUE TITLE
Use types and modules for skydive front_end

### ISSUE THREAD

**Issue by pierrecregut** [skydive-project/skydive#236]
To make it easier for newbies to add new panels and filters on nodes, use typescript and webpack to make explicit the contracts between the different parts of the ui:
- use webpack to make es2015 modules available with explicit import/export.
- use typescript with types enforced. Use class syntax.
- use npm to handle external dependencies.
- use vue-class-component to have explicit types in vues and use require to separate the template part from the logic

An experimental branch 'typescript_frontend' is visible on the fork pierrecregut/skydive.
For example it is easier to understand 
- where and how the Graph class is used between the websocket and the TopologyLayout, 
- what are the models really used as datasources by d3.js and how they are related to the graph model
- when an id or an object is used by a method
- what kind of this context is expected
Code refactoring should also be easier as the typesystem will catch a lot of the errors when an element is moved. 

The experiment uses a simplified version of ducksoupdev/vue-webpack-typescript as a template for the front_end that contains all the javascript/html code. It generates a front_end/statics file that will be used in place of statics for go-bindata.
There is room for improvement : typescript doc generation, unit tests, etc. that can be added back from the original template. 
Because we use typescript, code generated is es5 compliant (option is tsconfig) and modules are translated by webpack.

**Comment by eonpatapon** [comment]
I started some work to move on webpack and es2015 modules.

As for typescript, I've never used it but I've read some good things about it. On the other end I'm not sure it would make things easier for newbies.

I will look at your branch, thanks!

**Comment by safchain** [comment]
Closing, new WebUI will handle this
https://github.com/skydive-project/skydive-ui
