### ISSUE TITLE
Slack invite link broken

### ISSUE THREAD

**Issue by adrianlzt** [skydive-project/skydive#2362]
The link https://slack.skydive.network is broken.

It is in the readme to join the slack channel. Not needed any more?

**Comment by safchain** [comment]
Hello, this is due to a little DC problem(fire), we are waiting to know if we can recover the machine or if we will have to reintall

**Comment by adrianlzt** [comment]
Uops, the ovh fire. Ok. Anyways, I think the cert was expired.
