### ISSUE TITLE
Work plan: ui: display bandwidth on L2 edges

### ISSUE THREAD

**Issue by kdorfman** [skydive-project/skydive#237]
1. Merge basic functionality: https://softwarefactory-project.io/r/#/c/7085/
2. Since each client (WebUI user) may have different requirements to bandwidth display (different configurations) need to add separate tab/button in WebUI to be able to config:
- bandwidth_source (netlink/flows)
- bandwidth_update_rate (depends on source)
- analyzer.bandwidth_threshold (relative/absolute)
- thresholds (active/warning/alert) - depends on type of threshold
3. Store user configurations from 2 in local storage
4. Next steps: need to keep User profile in Analyzer ETCD.

**Comment by safchain** [comment]
Closing it as dedicated issues for each topic have been created
