### ISSUE TITLE
skydive binaries require glibc version？

### ISSUE THREAD

**Issue by lhuang001** [skydive-project/skydive#2377]
I try to build a skydive binary on my server, but found some warnning. Does it mean skydive binary requires glibc version?
if my guess is true, is there any way to build a pure static binary?
thanks for your help:)
![skydive_issue](https://user-images.githubusercontent.com/21240907/122856683-c79d9a00-d349-11eb-821c-3bdcffeffb00.png)

**Comment by lebauce** [comment]
It seems you are building the binary with `make static` right ? There is no easy way to build a completely static version of a Go binary that makes use of some features. So you need indeed to have glibc installed, but as the symbols used are pretty old and stable, an old version of glibc should work

**Comment by lhuang001** [comment]
thanks for your replay. I finally resolved this probelm by switching server os from debian to ubuntu.

**Comment by lebauce** [comment]
@lhuang001 Thank you for your answer
