### ISSUE TITLE
go.sum is present in the repo and in .gitignore

### ISSUE THREAD

**Issue by adrianlzt** [skydive-project/skydive#2384]
This [commit](https://github.com/skydive-project/skydive/commit/2f8232bb70ab084041b952c510e30428f79a6792) added ``go.sum`` to the ``.gitignore`` file (2021/2/1). @hunchback error?

The ``go.sum`` file was deleted [here](https://github.com/skydive-project/skydive/commit/ed4e0d9cb8b4a6b396edd55a1298303888737d5e#diff-3295df7234525439d778f1b282d146a4f1ff6b415248aaac074e8042d9f42d63) by @lebauce (2019/11/12) and added back [here](https://github.com/skydive-project/skydive/commit/29551c6b46f3c2ac52038623eea252e9d2219a0d#diff-3295df7234525439d778f1b282d146a4f1ff6b415248aaac074e8042d9f42d63) by @amorenoz (2021/07/15).

So, with or without?

**Comment by lebauce** [comment]
Theoretically, go.sum should be part of this repository but I still having troubles understanding why the content differs from one machine to an other, causing the go-fmt test to fail so I ended up removing it. Now that Go modules are a bit more stable, we should probably add it back

**Comment by lebauce** [comment]
This is now fixed. go.sum is tracked by Git and removed from .gitignore
