### ISSUE TITLE
Add new view section for my custom graph added with cli

### ISSUE THREAD

**Issue by lucianolacurcia** [skydive-project/skydive#2396]
Hi, I want to ask if it's possible to crete a new view tab on the UI just for nodes/edges added programmatically with the CLI api. (Or for a subgraph of the main graph)
There is any example? 

Thanks!

**Comment by lebauce** [comment]
Hi. We recently introduced a new UI (https://github.com/skydive-project/skydive-ui) and just released version 0.28.0 with this new UI bundled by default : you should see a "UI Version 2 Beta" link at the top right of the "standard" UI.

With the new Web UI, it should be easier to filter on specific metadata for the nodes/edges created using the CLI. It's pretty easy to specify new default filter in the UI, but maybe @safchain will know better than me.

 If you use the command line, the "@Origin" field should start with `cli.` so you could write a Gremlin query : G.V().Has("@Origin", Regex("cli.*")), if you use the API, it will start with `api.` if you did not specify any origin.

Hope this helps

**Comment by lucianolacurcia** [comment]
Thanks for the fast reply!
Actually, I am trying to use just "graffiti" as a graph viz tool (independently of skydive), I followed the [guide](https://github.com/skydive-project/skydive/tree/master/graffiti#quick-start) for getting both servers up and running, (the graffiti hub and the skydive-ui server) but I am getting an error on the UI "not connected".
![image](https://user-images.githubusercontent.com/11810076/129810030-725a3084-d8ff-460d-927d-0bd790694be0.png)
Here the two commands running:
![image](https://user-images.githubusercontent.com/11810076/129810096-d0059d42-e658-441f-a474-100a1b6baf1e.png)

Also I would want to use the legacy version of the UI, is there any option for choosing the old UI instead of the new one for use independently of skydive as standalone graffiti?

**Comment by lebauce** [comment]
@lucianolacurcia I seems to be because the UI tries to connect to the wrong port. If you click on the icon at the top right and click on "Logout", a form where you'll be able to specify the Graffiti hub endpoint : specify http://localhost:8082 and click on "Sign In"

**Comment by lebauce** [comment]
Regarding the use of the old UI with Graffiti, I'm afraid there is no easy way to do it :-/

**Comment by lebauce** [comment]
Closing the issue. Feel free to reopen it if you think that is an issue. Thanks
