### ISSUE TITLE
do skydive on docker not support VMs

### ISSUE THREAD

**Issue by songku** [skydive-project/skydive#2405]
I am a layman for network analyzing.
I have read your document on http://skydive.network/documentation/ ,but I didn't find any useful information for my purpose.
I want to watch the network topology on my win11 and it's interation with VMs in VMware workstation.I have built the skydive project through docker compose well.
I lanched two virtual machines through my personal VMware workstation,and I started the skydive project on my win11's Docker .I can well saw the topology on localhost:8082.
However,there are just the machines and veths created by docker,such as skydive-analyzer-1,elasticsearch-1 and skydive-agent-1.I can't see my PC's network status even with my VMs.Does it work well?
I mean,is skydive not supported for VMware workstation and win11's ?

**Comment by lebauce** [comment]
Hello @songku 
Skydive only supports Linux for now, sorry. Patches are welcome though :-)

**Comment by songku** [comment]
> Hello @songku Skydive only supports Linux for now, sorry. Patches are welcome though :-)

Thank you very much for your reply.
