### ISSUE TITLE
when make install there occurs could not determine kind of name for C.sizeof_struct_tpacket3_hdr

### ISSUE THREAD

**Issue by liliangfree** [skydive-project/skydive#244]
when i make install ，there have some problems：
# github.com/skydive-project/skydive/vendor/github.com/google/gopacket/afpacket
could not determine kind of name for C.sizeof_struct_tpacket3_hdr
# github.com/skydive-project/skydive/flow/probes/afpacket
could not determine kind of name for C.PACKET_FANOUT
make: *** [skydive-bash-completion.sh] Error 2

help there have someone help me

**Comment by safchain** [comment]
Hi, 

It seems a dependency issue.

could tell us what is the distribution used and if you could give us the full output as well. 

Thanks.

**Comment by liliangfree** [comment]
![image](https://cloud.githubusercontent.com/assets/5870167/25160526/1f8ff280-24e9-11e7-9faa-1e1c33268770.png)

this is output,for a new user,thank you very much for helping me. @safchain

**Comment by safchain** [comment]
@liliangfree thanks for the capture. Could you give me the distribution you are using please ?

**Comment by liliangfree** [comment]
dear Sylvain Afchain:
    i use skydive 0.10 and base go 1.8.1 and elasticsearch-5.3.0 and protoc-3.2.0 ,and when i make install skydive ,it occurs that error@safchain
Best regards

**Comment by safchain** [comment]
@liliangfree thanks for these information, can you provide the OS version debian, ubuntu, fedora, etc

**Comment by liliangfree** [comment]
@safchain thanks for your help,the OS is centos 6.5

**Comment by safchain** [comment]
Hi @liliangfree, 

It's related to this issue : https://github.com/google/gopacket/issues/149. So need a more recent kernel..

**Comment by liliangfree** [comment]
ok。thank you
