### ISSUE TITLE
Long time 

### ISSUE THREAD

**Issue by eranra** [skydive-project/skydive#2442]
@lebauce What's up?

**Comment by lebauce** [comment]
Hello @eranra !
Hope you're fine, happy to hear from you again.
Mostly doing the bare minimal in terms of maintenance of Skydive :-)

**Comment by eranra** [comment]
@lebauce I see that --- a lot of e-mails on your work to re-organize and remove rust from the code.
Are we expecting new users to pick up the code?

( You are probably aware that we moved to work on https://github.com/netobserv with RH and with a very similar vision to some of the capabilities that exist in Skydive)

**Comment by eranra** [comment]
:-)
