### ISSUE TITLE
Installation of skydive network analyzer

### ISSUE THREAD

**Issue by alliyaan** [skydive-project/skydive#248]
Sir I am beginner I need complete skydive installation tutorial with all supporting software I hope, it solves all issues that anyone face 
Sir plz help...!

**Comment by masco-enovance** [comment]
follow this link http://skydive-project.github.io/skydive/getting-started/install/
if you face any problem ping in "skydive-project" channel @freenode IM

**Comment by alliyaan** [comment]
masco-enovance i don't relay know how to use linux sir plz help me (i am Microsoft user).i just view my whole network.and gradually learn this analyzer. i hope you wills understand.

**Comment by safchain** [comment]
By default Skydive doesn't rely on any dependency. If you're not familiar with linux and you just want to see how Skydive works I would suggest to download the last stable binary and use the all-in-one mode which will start everything for you, please see http://skydive-project.github.io/skydive/getting-started/install/#all-in-one

For a more complete deployment you can use the vagrant file present in the repository : https://github.com/skydive-project/skydive/tree/master/contrib/vagrant. It will deploy an analyzer + 2 agents.

If you want to deploy Skydive by hand you will need to deploy Elasticsearch which is the only real dependency to have all the Skydive features. Then deploy the Skydive binary on the "Analyzer" host and on the hosts you want to monitor (Agents). Modify the config file (https://github.com/skydive-project/skydive/blob/master/etc/skydive.yml.default) accordingly to set :

- analyzers addresses : https://github.com/skydive-project/skydive/blob/master/etc/skydive.yml.default#L89
- etcd address : same as the analyzer one : https://github.com/skydive-project/skydive/blob/master/etc/skydive.yml.default#L211
- elasticsearch address : https://github.com/skydive-project/skydive/blob/master/etc/skydive.yml.default#L165 
- elasticsearch as storage : https://github.com/skydive-project/skydive/blob/master/etc/skydive.yml.default#L180, https://github.com/skydive-project/skydive/blob/master/etc/skydive.yml.default#L50

Hope this will help you
