### ISSUE TITLE
Add a way to add external metadata on existing node

### ISSUE THREAD

**Issue by safchain** [skydive-project/skydive#249]
The goal is to be able to add metadata on an existing node either with the config file or the API. It could be to identify a node/interface depending on the host for example, I may want to start a capture on physical interfaces on different host not having the same name.

**Comment by safchain** [comment]
- Need to handle agent restart
- Need to handle agent graph element update
- Need to handle delete metadata operation
- Need to extra metadata to a sub map to protect probe metadata against delete

**Comment by masco-enovance** [comment]
https://softwarefactory-project.io/r/#/c/8483/

**Comment by safchain** [comment]
Fixed #270
