### ISSUE TITLE
how can I get the original package(such as pcap package) for further analysis? 

### ISSUE THREAD

**Issue by BenDerPan** [skydive-project/skydive#253]
how can I get the original package(such as pcap package) for further analysis, such as analyse http,ftp...protocols?

**Comment by safchain** [comment]
Hi, 
I guess you meant packet :)

So currently we are not keeping the original packet but that something we are going to address soon probably adding samples to flows.

**Comment by BenDerPan** [comment]
yes,it's packet 👍 
That's must be a good news, I tried ,and failed. :)

**Comment by safchain** [comment]
@BenDerPan Hi, now fixed by #299
