### ISSUE TITLE
Activate all capture, no need to have them in the config file

### ISSUE THREAD

**Issue by safchain** [skydive-project/skydive#254]
We can remove the probe section for flow in the config file, activating all of them by default. We should just rely on topology. 

For the ovssflow we should add a optional parameter for the capture creation allowing to specify the ovsdb endpoint. So that we can use ovssflow for external ovsdb compliant switch.

**Comment by masco-enovance** [comment]
https://github.com/skydive-project/skydive/issues/174 is not the same?
