### ISSUE TITLE
external flows enhancer

### ISSUE THREAD

**Issue by nplanel** [skydive-project/skydive#307]
Have a external flows enhancer
integrate tool like : 
 - prelude
 - ndpi

A simple way to enhance the flows without carry about packets processing

**Comment by lebauce** [comment]
For nDPI, we could have a flow enhancer that calls the nDPI in C add metadata to the flow.

**Comment by nplanel** [comment]
the idea was to have a fast implementation and resuse the ndpi's flowtable
Technically doing the Skydive agent in C and sending flow protobuf to analyzer
