### ISSUE TITLE
Interfaces without a host

### ISSUE THREAD

**Issue by carroarmato0** [skydive-project/skydive#313]
Skydive 0.11.0

Sometimes in the UI, interfaces appear without being part of a host.

![screenshot from 2017-07-19 17-35-45](https://user-images.githubusercontent.com/1828645/28375825-d961ac38-6ca8-11e7-90f9-5907b7c9973e.png)

**Comment by safchain** [comment]
It is a known issue of the 0.11, It should be fixed in master, so will be available in the next release (soon)

**Comment by carroarmato0** [comment]
Great! :)

**Comment by safchain** [comment]
I close it, feel free to re-open it if the issue is still present in the master branch
