### ISSUE TITLE
feature:topology: add user information for tap interfaces

### ISSUE THREAD

**Issue by ji-xuepeng** [skydive-project/skydive#338]
As a end user, he may want to know the relations between the virtual machines and virtual ports(tap interface for example) from the topology.  This will provide a great convenience for the user.

**Comment by safchain** [comment]
@ji-xuepeng can you elaborate a bit on this, what kind of information ? currently if you have an agent on the hypervisor and another one within the VM you should have a link between the tap of the hypervisor and the interface within the VM ? is it not what you get or do you think about something else ?

**Comment by ji-xuepeng** [comment]
@safchain I just want a VM's UUID will be displayed in the topoloyg shown in GUI. Thus, when I want to diagnose a VM, I will know which virtual interface belongs to the VM. I can do it through the following steps, but it's tedious.

1. Find virtual interfaces used by VM‘s UUID on the hypervisor.
root@ub1604-01:/# virsh domiflist 933c8f9a-09da-4955-aee7-04ad78a9de33
Interface  Type       Source     Model       MAC
-------------------------------------------------------
tap58aa8eea-a5 bridge     qbr58aa8eea-a5 virtio      fa:16:3e:a4:82:f8
2. Do diagnostic tests on the virtual interface through the skydive GUI

If a VM's UUID is displayed in the topology shown in skydive GUI, I can easily find the virtual interface which is used by the VM before making a diagnosis test.

**Comment by safchain** [comment]
@ji-xuepeng if using openstack you already have the VM UUID reported on the tap thanks to the Neutron probe. It needs to be activated with the config file.

**Comment by ji-xuepeng** [comment]
Yes,we can get the VM UUID from the metadata info of the port. But I think it is not convenient enough for users. the user must click ports one by one on topology diagram to  find which port belongs to the VM. Whether we can add the VM'image icon in the topology diagram, and associate the ports which belong to the VM with the VM'image icon?

**Comment by safchain** [comment]
Right I do understand now your point :) Yes we can change the icon another thing is we could add a select mechanism on the right panel

**Comment by lebauce** [comment]
You can now put filters in the WebUI so that Skydive would highlight the tap for a specific VM UUID.
