### ISSUE TITLE
ofrule: not always reporting flow rules

### ISSUE THREAD

**Issue by safchain** [skydive-project/skydive#367]
The ovs_of probe is not always seing the rule added, ex:

 sudo ovs-ofctl dump-flows br-int
NXST_FLOW reply (xid=0x4):
 cookie=0x0, duration=208.642s, table=0, n_packets=17, n_bytes=1342, idle_age=146, priority=0 actions=NORMAL
 cookie=0x0, duration=140.523s, table=0, n_packets=3, n_bytes=210, idle_age=69, priority=76 actions=resubmit(,1)
 cookie=0x0, duration=203.160s, table=2, n_packets=0, n_bytes=0, idle_age=203, priority=76 actions=resubmit(,1)

skydive client topology query --gremlin 'G.V().Has("Type", "ofrule")'
[
  {
    "CreatedAt": 1502273673587,
    "Host": "HOHO1",
    "ID": "7bbdda63-d002-46e2-4683-baed777fac57",
    "Metadata": {
      "Type": "ofrule",
      "UUID": "51d2af52-7e24-5dc3-56b4-1c1bf632d07c",
      "actions": "resubmit(;1)",
      "cookie": "0x0",
      "filters": "priority=76",
      "priority": 76,
      "table": 2
    },
    "Revision": 1,
    "UpdatedAt": 1502273673587
  },
  {
    "CreatedAt": 1502273673578,
    "Host": "HOHO1",
    "ID": "2383efb1-4734-4000-6653-4bbab8b7dd56",
    "Metadata": {
      "Type": "ofrule",
      "UUID": "09156e65-2c95-5b76-6bcd-25cba055b474",
      "actions": "resubmit(;1)",
      "cookie": "0x0",
      "filters": "priority=76",
      "priority": 76,
      "table": 0
    },
    "Revision": 1,
    "UpdatedAt": 1502273673578
  }
]

**Comment by pierrecregut** [comment]
Yes, there is a bug. But it occurs only when a rule is exactly masking another one: ie, same table, cookie and filters but different priorities. Monitor does not report priorities. When we list rules, we try to be smart. I will change the code to be less smart and use UUID including priorities for ADD and DELETE to add or prune rules on the bridge.
