### ISSUE TITLE
Makefile:104: recipe for target 'govendor' failed make: *** [govendor] Error 127

### ISSUE THREAD

**Issue by alliyaan** [skydive-project/skydive#396]
$ sudo mkdir -p $GOPATH/src/github.com/skydive-project
$ sudo git clone https://github.com/skydive-project/skydive.git $GOPATH/src/github.com/skydive-project/skydive
$ cd $GOPATH/src/github.com/skydive-project/skydive
$ sudo make install
go get github.com/kardianos/govendor
/bin/govendor sync
make: /bin/govendor: Command not found
Makefile:104: recipe for target 'govendor' failed
make: *** [govendor] Error 127
help ..!

**Comment by safchain** [comment]
Hi,

is $GOPATH/bin in your $PATH ?

**Comment by safchain** [comment]
BTW we provide static binary for each release and docket images for each commit. This could be a good start if you just wanted to test skydive without compiling it

**Comment by alliyaan** [comment]
PATH="/usr/local/go/bin:$PATH"
PATH="/home/ali/Go/src/github.com/skydive-project/skydive:$PATH"
export GOPATH=$HOME/Go
export GOPATH=$HOME/src/github.com/skydive-project/skydive

Is this a right way?

**Comment by alliyaan** [comment]
Please make 10 to 15 mins of speed video for all this?

**Comment by nplanel** [comment]
in your .bashrc you should have something like this : 

export GOPATH=$HOME/Go
export PATH="$PATH:$GOPATH/bin"

If you install go in /usr/local/go (if you not using the go package provided by your linux distribution)
export PATH="/usr/local/go/bin:$PATH"


This setup is independent of Skydive, it's the go environment installation, you can find information [here](https://golang.org/doc/install)
