### ISSUE TITLE
plz upload a complete installation & implementation of skydive & its database and all basic pre-recruit 

### ISSUE THREAD

**Issue by alliyaan** [skydive-project/skydive#399]
Dependencies#
Go >= 1.5
Elasticsearch >= 2.0
libpcap
libxml2
protoc >= 3.0

i really want to learn about skydive installation implementation troubleshooting managing network & all other feature ...
i hope you will make informative tutorial for beginners
please tag me if you can...!

**Comment by safchain** [comment]
Hi, 

Yes we are going to provide more information. That said did you check the quick [start guide](http://skydive-project.github.io/skydive/getting-started/install/), there are some way to quickly deploy skydive with all the dependencies (docker compose, vagrant, devstack, kubernetes, all-in-one binary) ?

**Comment by alliyaan** [comment]
Thanks sir...! 
But i want a video lacture . If you able to do that.
My first praffence is video lacture and second praffence binary script. Cause i m beginner...!

**Comment by alliyaan** [comment]
Thanks sir...! 
But i want a video lacture . If you able to do that.
My first praffence is video lacture and second praffence binary script. Cause i m beginner...!(i don't know proper command)
