### ISSUE TITLE
Too many sub-ports show in the topology by default now

### ISSUE THREAD

**Issue by jonnary** [skydive-project/skydive#402]
Too many sub-ports show in the topology by default, for example a Pf port eth0 has many sub-ports(eth0.1,eth0.2...), we show all this ports now.
I  think we can only show Host---Pf---VM/Container in a host node by default.
And When we click a VM, it show a chain Host---Pf---vSwitch---(qvo\qbr\tap)---VM/Container.
Also we can may this configurable.

**Comment by nplanel** [comment]
UI patches are under way to organize the topology display, like #398
