### ISSUE TITLE
how to add a local ci system for skydive

### ISSUE THREAD

**Issue by jonnary** [skydive-project/skydive#410]
For skydive develop, how to do unit/function/api test and  how to add a local ci system.

**Comment by lebauce** [comment]
https://github.com/skydive-project/skydive/blob/master/CONTRIBUTING.md has a section to describe how to run unit and functional tests

**Comment by jonnary** [comment]
Thanks, lebauce.
And if you have any suggestion or link about skydive CI system.

**Comment by safchain** [comment]
Everything you need to create a jenkins bases ci is there:
https://github.com/skydive-project/skydive/tree/master/scripts/ci

basically:

Ansible playbooks to deploy master/slave jenkins are there:
https://github.com/skydive-project/skydive/tree/master/scripts/ci/ansible

Jobs (jenkins job builder) we are using are here:
https://github.com/skydive-project/skydive/tree/master/scripts/ci/jobs

**Comment by jonnary** [comment]
Great, thanks safchain. I will try to deploy it.

**Comment by safchain** [comment]
Closing it for now. Please re-open it if needed
