### ISSUE TITLE
UI: cutting names of nodes in a more graceful way

### ISSUE THREAD

**Issue by vperelmax** [skydive-project/skydive#411]
In the current version, when a node has too long name, only first 10 characters are written.
In some cases it is not obvious that the name was cut (and for example, a few nodes with different names on the graph will appear with the "same" name because their prefix is the same).
We should find way to make such name cutting more explicit for users.
Examples for solutions: 
1) putting "..." as the last character in names that were cut
2) adding to such nodes tooltips with the whole name
3) reducing fonts???

**Comment by safchain** [comment]
ok for 1 and 2, not sure for reducing font it could be hard to read something if smaller

**Comment by masco-enovance** [comment]
implemented option 1 and merged with master. https://github.com/skydive-project/skydive/pull/421
