### ISSUE TITLE
Add Gremlin Union step

### ISSUE THREAD

**Issue by eranra** [skydive-project/skydive#426]
In order to allowed support for even simple use cases, for example get all nodes connected to a single node and the node itself (i.e. myself + all nodes surrounding me one edge away) there is a need to add the union step to Gremlin.

So for example in this case, it will be possible to execute::
G.V().**union**(Has('Name', 'host1'),Has('Name', 'host1').Out())

**Comment by safchain** [comment]
G.V().Has('Name', within('host1, 'host2').Out() should work

**Comment by safchain** [comment]
G.V().Has('Name', within('host1, 'host2')).Out()

**Comment by eranra** [comment]
I tried this ::

G.V().Has('Name', within('kube-dal10-crc4d48704bff84452b2a7ad78340377aa-w3.cloud.ibm', 'kube-dal10-crc4d48704bff84452b2a7ad78340377aa-w3.cloud.ibm')).Out()


On the demo env, but it;'s not working ... to explain ... I want to see the host iteslf, and all the connected interfaces etc components one edge away ... so I have only one host not two ... in your example you explained how to see two hosts, this is not what I'm trying to solve.

**Comment by safchain** [comment]
sorry I mis-read your comment. So maybe this could be used:

G.V().Has('Name', 'host1').OutE().BothV ? but you will need this #416

**Comment by eranra** [comment]
Should work ... I need to check ... I ran::
G.V().Has('Name', 'kube-dal10-crc4d48704bff84452b2a7ad78340377aa-w3.cloud.ibm').OutE().OutV()
and 
G.V().Has('Name', 'kube-dal10-crc4d48704bff84452b2a7ad78340377aa-w3.cloud.ibm').OutE().InV()

and both looks good ... so I assume you are correct and BothV() will solve (maybe need also to add the dedup stage). In any event I think that the flexibility we will get with Union will be useful forward and the syntax will be more understandable.

BTW; There is another option which is to extend InV and outV to include also the node itself  ... this might be another nice alternative.

**Comment by eranra** [comment]
Waiting for #416 to see this working.

**Comment by safchain** [comment]
We will add the as/select steps to address the union

**Comment by safchain** [comment]
Closing it for now as select/as has been added and handles the use cases
