### ISSUE TITLE
ShortestPathTo returns list of lists and not list of nodes (as documented) - this causes panic in new topology filter code

### ISSUE THREAD

**Issue by eranra** [skydive-project/skydive#427]
According to documentation, the ShortestPathTo step should return " ... This step returns a list of all the nodes traversed. ... " but in reality it returns list of those list. 

For example when executing ShortestPathTo (in this example to the same node) you get list of lists:

`/usr/bin/skydive` client topology query --gremlin "G.V().Has('TID', '37651ae9-ae94-5bd1-652e-abf99609781b').ShortestPathTo(Metadata('TID', `'37651ae9-ae94-5bd1-652e-abf99609781b'))"`

**[
  [
    {**
      "CreatedAt": 1504457657356,
      "Host": "kube-dal10-crc4d48704bff84452b2a7ad78340377aa-w3.cloud.ibm",
      "ID": "c38fb80b-9f70-4e9e-4acb-e9ec58b4cba4",
      "Metadata": {

...

but when executing without ShortestPathTo (this is the expected / normal behavior) you get regular list :

 `/usr/bin/skydive` client topology query --gremlin "G.V().Has('TID', `'37651ae9-ae94-5bd1-652e-abf99609781b')"`

[
  {
    "CreatedAt": 1504457657356,
    "Host": "kube-dal10-crc4d48704bff84452b2a7ad78340377aa-w3.cloud.ibm",
    "ID": "c38fb80b-9f70-4e9e-4acb-e9ec58b4cba4",
    "Metadata": {
      "Capture": {
        "PacketsDropped": 0,
        "PacketsIfDropped": 0,
        "PacketsReceived": 48
      },
...

**Comment by safchain** [comment]
The current behavior is correct (I think) and the documentation is not correct. You can select multiple nodes for both source and destination nodes leading to have multiple shortestpath. This is the case if you use something than TID

**Comment by safchain** [comment]
Maybe we could force the user to select only one source and one destination node so that we can ensure to return one path.

**Comment by eranra** [comment]
K, so I will ask Lera to fix the filtering code to support the general case (i.e. list of lists) and the documentation. For now I do not see a reason to add specific new step. Actually the more needed step would probably be to have all the paths and not just shortestPath.

**Comment by lebauce** [comment]
@eranra Can we close this one ?

**Comment by eranra** [comment]
Yes :-)
