### ISSUE TITLE
Red capture icons do not disappear after deleting capture 

### ISSUE THREAD

**Issue by eranra** [skydive-project/skydive#429]
In some case, when staring capture on an interface, and removing (not consistent) the node level red capture icon do not disappear.  Restarting the UI does not help, so one can assume this is a backend (go) bug. 

screenshot attached 

![image](https://user-images.githubusercontent.com/3080696/30261355-e9b0e5c6-96d4-11e7-9688-bd5b09ef921c.png)

**Comment by safchain** [comment]
Yes probably a backend issue ? are you able to reproduce it ? do you have analyzer/agent log ?

**Comment by eranra** [comment]
https://cognetiveyz.sl.haifa.il.ibm.com
user: demo
password: demo1234
open the exploration module and expend the view

If you want to restart the Analyzer, just hit "Restart Exploration module" in the troubleshooting section (this solves the issue until you start capturing and stop capturing again)

Logs are harder to get, but if you direct me to what part of the log (Analyzer / Agent ???) I can grep the needed lines ... just need direction what to look for ?

**Comment by safchain** [comment]
maybe grep on "ERROR" will give us some clues

**Comment by eranra** [comment]
(1) Update: I see now that this is cross Analyzer reboots, so I assume this is somewhere in the Agents code and not in the Analyzer. 
(2) Update: I see flow data in the GUI, so the agents really continue to prob, get flows and send to the Analyzer.

It seems to me now, that this this is somehow connected to listening (or not) to etcd changes

**Comment by eranra** [comment]
I restarted the agents (just to see if this is agents problem) and I can't simulate this again ... now it works perfect. I will keep this issue open for a while and if this will not happen again will close the issue.

**Comment by lebauce** [comment]
@eranra Any news on this one ?

**Comment by eranra** [comment]
No news, other than the fact that this still exists. I didn't had time to drill down but I am very confident that this is connected to the process of restarting of the Analyzer and destroying the local etcd server and when the clients re-connect to a new instance of the server / etcd they do not 'forget' the old capture ... need to go into the code ...

**Comment by safchain** [comment]
so it is more clear now and the reason of this bug is pretty simple. There is no sync mechanism between the agent and the analyzer for the captures. So if you delete etcd and the agent are disconnected from the analyzers there is no way for them to know that they have to delete their captures. We need to add a Sync mechanism.

**Comment by eranra** [comment]
Ok, this explains :-)

Would adding somehow 'start from scratch' / 'delete all existing recordings' when an agent is disconnected from etcd make sense ?

**Comment by safchain** [comment]
Yes adding a sync mechanism when an agent reconnects to an analyzer makes sense. Adding works with current code but it is not a sync.
