### ISSUE TITLE
Regex not working with "At" Step within Gremlin request

### ISSUE THREAD

**Issue by noisynoise** [skydive-project/skydive#431]
Using Skydive v0.12.0, Regex seems to not work when used within a Gremlin request with an "At" step : 

For example, the following is  working : 
```
G.At(1505134262,21600).Flows().Has('Network.A', '192.168.130.5').Metrics()
```

but the same with a Regex has an empty answer : 
```
G.At(1505134262,21600).Flows().Has('Network.A', Regex('^192.168.130.*')).Metrics()
```

**Comment by safchain** [comment]
Thanks for reporting this. Confirmed

**Comment by safchain** [comment]
So it is probably due to the anchor that you used in the Regex. Elasticsearch doesn't support them as it is always anchored. I'm going to make the behavior consistent between all the backend raising.
