### ISSUE TITLE
Unsyncrhonized access to map of probes on agent

### ISSUE THREAD

**Issue by rkhachatryan** [skydive-project/skydive#434]
When registering a new probe we are checking if it already exists. If not, lock is acquired and probe is added. For example:
* https://github.com/skydive-project/skydive/blob/b5d858dabfdf75d3da1dad6d61e84d6e3aba642b/flow/ondemand/server/server.go#L103
* https://github.com/skydive-project/skydive/blob/b5d858dabfdf75d3da1dad6d61e84d6e3aba642b/flow/probes/gopacket.go#L291
* https://github.com/skydive-project/skydive/blob/b5d858dabfdf75d3da1dad6d61e84d6e3aba642b/flow/probes/sflow.go#L78

But if after check but before lock the same probe will be added by another goroutine then we'll end up with two probes running (or fatal error with go race detector).
This may happen if several WS clients (as per "analyzers" config param) simultaneously send "onDemand.CaptureStart" message for the same node/type (because all WS clients have the same OnDemandProbeServer per namespace and run in parallel).

Solution may be to simply add second check after the lock is acquired.

**Comment by safchain** [comment]
Right the access to the activeProbes map is not protected correctly but I'm a bit concern about your simultaneously WSClient. This shouldn't happen as there is a master election and only one analyzer should send the message

https://github.com/skydive-project/skydive/blob/master/flow/ondemand/client/client.go#L246

Can you give us the way you trigger this error. Are you using the same Etcd for all the analayzers ?

**Comment by rkhachatryan** [comment]
I was just reading the code, it wasn't triggered. You are right, I didn't check client.go.

**Comment by safchain** [comment]
ok cool, I going to fix the map access anyway
