### ISSUE TITLE
Possible channel overflow in FlowTable and PcapFeeder and interleaving of query replies

### ISSUE THREAD

**Issue by rkhachatryan** [skydive-project/skydive#435]
When querying FlowTable if timout occurs then reply channel never gets cleared: https://github.com/skydive-project/skydive/blob/b5d858dabfdf75d3da1dad6d61e84d6e3aba642b/flow/table.go#L316

Therefore 
* the next query will get previous result
* and if the total number of timeouts will reach buffer size then reply channel will become full

Now, if reply channel is full then next query will block FlowTable.run goroutine:
https://github.com/skydive-project/skydive/blob/b5d858dabfdf75d3da1dad6d61e84d6e3aba642b/flow/table.go#L403

Now, when flow table goroutine is blocked it stops consume packets from tables PacketsChan. This channel subsequently will be overflowed as well and now Table Feeder will be blocked trying to insert new packet into table.packetsChan:
https://github.com/skydive-project/skydive/blob/b5d858dabfdf75d3da1dad6d61e84d6e3aba642b/flow/pcap.go#L124

So now skydive isn't reading packets from pcap socket (which may lead to further problems).

Channels overflow scenario is a bit pessimistic and is likely to happen either in the very long run or if timeout or channel size will be decreased.

Please correct me if I'm wrong

**Comment by safchain** [comment]
The timeout is only there to check is a flow table is being stop while querying.

https://github.com/skydive-project/skydive/blob/b5d858dabfdf75d3da1dad6d61e84d6e3aba642b/flow/table.go#L320

In that case the Query end up and the chans will be close by the flow table

https://github.com/skydive-project/skydive/blob/b5d858dabfdf75d3da1dad6d61e84d6e3aba642b/flow/table.go#L428

Do you have any reproducible error ?

**Comment by rkhachatryan** [comment]
Oh, missed this check, sorry:) 
No, as I mentioned in #434 I was just reading the code.

**Comment by rkhachatryan** [comment]
I think it still makes sence to add timeout in PcapTableFeeder.feedFlowTable (to handle situation when packets consumed too slow).

**Comment by safchain** [comment]
I don't think this is needed as PcapTableFeeder is used to fill a flow table from a file so it can wait.

**Comment by safchain** [comment]
Closing it for now, please feel free to re-open it if needed.
