### ISSUE TITLE
No such file or directory: textflag.h ///////////////////make: *** [govendor] Error 2

### ISSUE THREAD

**Issue by devgnu9** [skydive-project/skydive#448]
Hello community, I have a problem while installing the system, I hope you can help me to resolve this issue
When i'm on the directory of the system and type #make install shows me this

go get github.com/kardianos/govendor
golang.org/x/sys/unix
src/golang.org/x/sys/unix/asm_linux_amd64.s:8 6a: No such file or directory: textflag.h
Makefile:106: recipe for target 'govendor' failed
make: *** [govendor] Error 2

**Comment by devgnu9** [comment]
I tried to run the next command (go get -u github.com/kardianos/govendor) but keep showing me the same error

**Comment by nplanel** [comment]
textflag.h is part of your golang installation (in GOROOT)
You should reinstall your golang binaries : https://golang.org/doc/install

**Comment by safchain** [comment]
As @nplanel explained it is a Go environnent issue, closing it as not related to Skydive
