### ISSUE TITLE
inject packet cannot work

### ISSUE THREAD

**Issue by ke-king** [skydive-project/skydive#452]
I have a all-in-one openstack with ovs newtwork type, and I create two vm. I want to inject icmp packer from vm1 to vm2, but cannot dump packert anywhere. My environment is below:

[root@master ~]# openstack server list
+--------------------------------------+------+--------+-------------+--------+------------+
| ID                                   | Name | Status | Networks    | Image  | Flavor     |
+--------------------------------------+------+--------+-------------+--------+------------+
| c3c1ce30-9bed-4c40-878b-3290cf7a163c | vm2  | ACTIVE | net=1.2.3.7 | cirros | test.large |
| b28e2c81-8a93-48a6-9417-5613e64578f4 | vm1  | ACTIVE | net=1.2.3.9 | cirros | test.large |
+--------------------------------------+------+--------+-------------+--------+------------+
[root@master ~]# openstack port list
+--------------------------------------+------+-------------------+------------------------------------------------------------------------+--------+
| ID                                   | Name | MAC Address       | Fixed IP Addresses                                                     | Status |
+--------------------------------------+------+-------------------+------------------------------------------------------------------------+--------+
| 0e16fea7-2356-4c6b-9f39-e4a3e3ed7f6f |      | fa:16:3e:21:ab:f9 | ip_address='1.2.3.2', subnet_id='0d1edcc4-aef5-478e-a321-68d4638db8a6' | ACTIVE |
| 2d650cd7-5ef3-4e84-9989-caf844d590bb |      | fa:16:3e:aa:33:98 | ip_address='1.2.3.7', subnet_id='0d1edcc4-aef5-478e-a321-68d4638db8a6' | ACTIVE |
| 3d5517cd-b460-46ef-9b2b-d38dfc6dc959 |      | fa:16:3e:55:ba:f8 | ip_address='1.2.3.9', subnet_id='0d1edcc4-aef5-478e-a321-68d4638db8a6' | ACTIVE |
+--------------------------------------+------+-------------------+------------------------------------------------------------------------+--------+

I use skydive client to inject packet:
[root@master ~]#  ./skydive client inject-packet --dst="G.V().Has('Name', 'tap3d5517cd-b4')" --src="G.V().Has('Name', 'tap2d650cd7-5e')" --type="icmp4" --srcIP="1.2.3.7/24" --dstIP="1.2.3.9/24" --count=15 -c /etc/kolla/skydive-agent/skydive.conf  
{
  "Src": "G.V().Has('Name', 'tap2d650cd7-5e')",
  "Dst": "G.V().Has('Name', 'tap3d5517cd-b4')",
  "SrcIP": "1.2.3.7/24",
  "DstIP": "1.2.3.9/24",
  "SrcMAC": "fe:16:3e:aa:33:98",
  "DstMAC": "fe:16:3e:55:ba:f8",
  "SrcPort": 0,
  "DstPort": 0,
  "Type": "icmp4",
  "Payload": "",
  "TrackingID": "",
  "ID": 0,
  "Count": 15,
  "Interval": 1000
}

is there any error? thank you

**Comment by lebauce** [comment]
@ke-king Could you please test if the problem still occurs with the latest version of Skydive ? Thanks !

**Comment by ke-king** [comment]
the latest version can work, thanks!
