### ISSUE TITLE
Wrong count of packets with opencontrail / afpacket

### ISSUE THREAD

**Issue by eonpatapon** [skydive-project/skydive#461]
With a single ping flow I can see that ABPackets and ABBytes are increasing in a non linear manner. The BAPackets is fine (+1 per second, like the ping does).

The capture is made on the VM tap interface.

At some point we are dropping incoming packets via a security group so nothing is reaching the VM tap but ABPackets/ABBytes is still increasing (not as fast, but still).

I can provide a devstack with this issue if someone is willing/able to debug this issue.

**Comment by eonpatapon** [comment]
This is the kind of metrics I get with a single ping:
```
    "Metric": {
      "ABBytes": 665518,
      "ABPackets": 6791,
      "BABytes": 58114,
      "BAPackets": 593
    },
```

**Comment by eonpatapon** [comment]
Fun fact: ABPackets is increasing strangely after the 9 first packets

**Comment by safchain** [comment]
@eonpatapon which type of capture are using afpacket (default) or pcap ? thx

**Comment by eonpatapon** [comment]
afpacket, I will make a test with pcap

**Comment by eonpatapon** [comment]
Ok, so with pcap it works properly
