### ISSUE TITLE
communication: in environment with a few agents, some agents cannot re-connect  

### ISSUE THREAD

**Issue by vperelmax** [skydive-project/skydive#532]
We see numerous following errors:
http/wsserver.go:75 (*WSServer).serveMessages ...host_id error, connection from XXX(YYY) conflicts with another one
This causes problems as the agents stop sending their data/flow logs.

A few possible hypothesis: 
1) maybe at disconnect agents don't disconnect gracefully and their entry remains in the tables of existing speakers
2) while in the code we try to disable connection of a few speakers with the same ID for comparison we test only if they come from the same host. Maybe we should check a pair <HostName, Port>

**Comment by safchain** [comment]
fixed: #538
