### ISSUE TITLE
Collapse different interfaces related to a single VM instance in OpenStack

### ISSUE THREAD

**Issue by l-anna** [skydive-project/skydive#617]
I have an OpenStack installation with Neutron/ML2. I have 25 VMs per compute node. 
In skydive GUI each VM is represented by 4  different interfaces: veth, veth, bridge, tun.
![image](https://user-images.githubusercontent.com/24270124/33269975-25e73548-d38b-11e7-8220-9d84976bde9b.png)
This makes the picture very hard to read. as you can see in the attached figure.
It would be very helpful to collapse all these interfaces to a single instance (VM) in the GUI and being expanded only when needed.

**Comment by sergeyglazyrindev** [comment]
When this changeset will be merged
https://github.com/skydive-project/skydive/pull/1443
I'll start working on contributing our simplified app topology and then you may be able to see app topology in hierarchied view, each app is a separated VM. I think what you propose now doesn't solve the problem properly.... it solves only part of the problem.

**Comment by safchain** [comment]
Closing, new WebUI will handle this
https://github.com/skydive-project/skydive-ui
Feel free to create feature requests there
