### ISSUE TITLE
python sample doesn't work

### ISSUE THREAD

**Issue by matrohon** [skydive-project/skydive#629]
Recent changes broke the sample provided in contrib//python/api/samples/inject-nodes1.py.

Using it with an correct TOR name instead of the provided in the example leads to no link created between the port and the TOR, and the following log in the analyzer : 

```
INFO    http/wsserver.go:55 defaultIncomerHandler       analyzer-1: New WebSocket Connection from [::1]:35818 : URI path /ws/publisher
DEBUG   analyzer/topology_publisher_endpoint.go:53 (*TopologyPublisherEndpoint).OnDisconnected  analyzer-1: Authoritative client unregistered, delete resources host-test
```

**Comment by safchain** [comment]
Confirmed, since split endpoints, working on it
