### ISSUE TITLE
Streaming API for flows

### ISSUE THREAD

**Issue by eonpatapon** [skydive-project/skydive#631]
It would be great if a client could listen for flows updates via WS.

Some captures are running, the client subscribes to flows with the analyzer, then the analyzer can forward flow information from agents directly to the subscribed client.

Not sure to what exactly the client will subscribe:
 * a capture UUID
 * a gremlin expression
 * ...

This feature can be useful for the webui (no more polling), but also for creating live dashboards in other tools.

**Comment by safchain** [comment]
Fixed: #1470
