### ISSUE TITLE
error during installation

### ISSUE THREAD

**Issue by Masber** [skydive-project/skydive#644]
Dear skydive team,

I would like to use skydive in order to troubleshoot my openstack environment but I have some troubles during installation.

these are the output from my make install command:

```
[root@openstack-deployment skydive]# make install
3896f2a04008
go get github.com/kardianos/govendor
/root/go/bin/govendor sync
patch -p0 < dpdk/dpdk.govendor.patch
patching file vendor/github.com/intel-go/yanff/low/low.go
go get github.com/golang/protobuf/proto
go get github.com/golang/protobuf/protoc-gen-go
go get github.com/jteeuwen/go-bindata/...
protoc --go_out . flow/flow.proto flow/set.proto flow/request.proto
protoc --go_out . filters/filters.proto
# always export flow.ParentUUID as we need to store this information to know
# if it's a Outer or Inner packet.
sed -e 's/ParentUUID\(.*\),omitempty\(.*\)/ParentUUID\1\2/' -e 's/int64\(.*\),omitempty\(.*\)/int64\1\2/' -i flow/flow.pb.go
# do not export LastRawPackets used internally
sed -e 's/json:"LastRawPackets,omitempty"/json:"-"/g' -i flow/flow.pb.go
# add flowState to flow generated struct
sed -e 's/type Flow struct {/type Flow struct {\n\tXXX_state flowState `json:"-"`/' -i flow/flow.pb.go
go-bindata  -nometadata -o statics/bindata.go -pkg=statics -ignore=bindata.go statics/* statics/css/images/* statics/js/vendor/* statics/js/components/*
gofmt -w -s statics/bindata.go
make -C contrib/snort
make[1]: Entering directory `/root/go/src/github.com/skydive-project/skydive/contrib/snort'
govendor build snortSkydive.go
unexpected directory layout:
        import path: github.com/google/gopacket
        root: /root/go/src
        dir: /root/go/src/github.com/skydive-project/skydive/vendor/github.com/google/gopacket
        expand root: /root/go/src
        expand dir: /root/go/src/github.com/skydive-project/skydive/vendor/github.com/google/gopacket
        separator: /
Error: exit status 1
make[1]: *** [snortSkydive] Error 2
make[1]: Leaving directory `/root/go/src/github.com/skydive-project/skydive/contrib/snort'
make: *** [contribs] Error 2
```
This is my GOPATH variable:
```
[root@openstack-deployment skydive]# echo $GOPATH
/root/go
```

Any idea?

Thank you very much

**Comment by safchain** [comment]
Hi,

is the Skydive source folder in the right place, meaning in the $GOPATH folder? please have a look here if not already done:

http://skydive-project.github.io/skydive/getting-started/install/#install

please let me known if it solve your issue.

BTW, you can download the latest binary here: https://github.com/skydive-project/skydive-binaries
and the latest release binary here: https://github.com/skydive-project/skydive/releases/tag/v0.14.0

Thanks

**Comment by safchain** [comment]
Closing it for now, please re-open it if needed, thanks

**Comment by eranra** [comment]
Hi Sylvain,

I tried to compile today skydive on a new environment (https://docs.microsoft.com/en-us/windows/wsl/install-win10). This should actuallybe a typical ubuntu 16.04 environment and got the same build challenge:

```# do not export LastRawPackets used internally
sed -e 's/json:"LastRawPackets,omitempty"/json:"-"/g' -i.bak flow/flow.pb.go
# add flowState to flow generated struct
sed -e 's/type Flow struct {/type Flow struct { XXX_state flowState `json:"-"`/' -i.bak flow/flow.pb.go
gofmt -s -w flow/flow.pb.go
go-bindata  -nometadata -o statics/bindata.go -pkg=statics -ignore=bindata.go statics/* statics/css/images/* statics/css/themes/*/* statics/js/vendor/* statics/js/components/*
gofmt -w -s statics/bindata.go
make -C contrib/snort
make[1]: Entering directory '/root/go/src/github.com/skydive-project/skydive/contrib/snort'
govendor build snortSkydive.go
unexpected directory layout:
        import path: github.com/google/gopacket
        root: /root/go/src
        dir: /root/go/src/github.com/skydive-project/skydive/vendor/github.com/google/gopacket
        expand root: /root/go/src
        expand dir: /root/go/src/github.com/skydive-project/skydive/vendor/github.com/google/gopacket
        separator: /
Error: exit status 1
Makefile:6: recipe for target 'snortSkydive' failed
make[1]: *** [snortSkydive] Error 2
make[1]: Leaving directory '/root/go/src/github.com/skydive-project/skydive/contrib/snort'
Makefile:187: recipe for target 'contribs' failed
make: *** [contribs] Error 2

```

**Comment by eranra** [comment]
Environment variables:

```root@ERANRA2-TP [176] ~/go/src/github.com/skydive-project/skydive  (master u=)
# echo $PATH
/root/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

root@ERANRA2-TP [176] ~/go/src/github.com/skydive-project/skydive  (master u=)
# echo $GOROOT
/usr/local/go

root@ERANRA2-TP [176] ~/go/src/github.com/skydive-project/skydive  (master u=)
#
```

**Comment by eranra** [comment]
I think this might be connected somehow to the environment variables or shell but not totally sure

More info::

```# go version
go version go1.9.1 linux/amd64
````

'''
root@ERANRA2-TP [248] ~/go/src/github.com/skydive-project/skydive  (master u=)
# make
4e64886694f3
go get github.com/kardianos/govendor
/root/go/bin/govendor sync
patch -p0 < dpdk/dpdk.govendor.patch
patching file vendor/github.com/intel-go/yanff/low/low.go
rm -rf vendor/github.com/weaveworks/tcptracer-bpf/vendor/github.com/
go get github.com/golang/protobuf/proto
go get github.com/golang/protobuf/protoc-gen-go
go get github.com/jteeuwen/go-bindata/...
protoc --go_out . flow/flow.proto flow/set.proto flow/request.proto flow/defender_flow.proto
protoc --go_out . filters/filters.proto
# always export flow.ParentUUID as we need to store this information to know
# if it's a Outer or Inner packet.
sed -e 's/ParentUUID\(.*\),omitempty\(.*\)/ParentUUID\1\2/' -e 's/int64\(.*\),omitempty\(.*\)/int64\1\2/' -i.bak flow/flow.pb.go
# do not export LastRawPackets used internally
sed -e 's/json:"LastRawPackets,omitempty"/json:"-"/g' -i.bak flow/flow.pb.go
# add flowState to flow generated struct
sed -e 's/type Flow struct {/type Flow struct { XXX_state flowState `json:"-"`/' -i.bak flow/flow.pb.go
gofmt -s -w flow/flow.pb.go
go-bindata  -nometadata -o statics/bindata.go -pkg=statics -ignore=bindata.go statics/* statics/css/images/* statics/css/themes/*/* statics/js/vendor/* statics/js/components/*
gofmt -w -s statics/bindata.go
make -C contrib/snort
make[1]: Entering directory '/root/go/src/github.com/skydive-project/skydive/contrib/snort'
govendor build snortSkydive.go
unexpected directory layout:
        import path: github.com/google/gopacket
        root: /root/go/src
        dir: /root/go/src/github.com/skydive-project/skydive/vendor/github.com/google/gopacket
        expand root: /root/go/src
        expand dir: /root/go/src/github.com/skydive-project/skydive/vendor/github.com/google/gopacket
        separator: /
Error: exit status 1
Makefile:6: recipe for target 'snortSkydive' failed
make[1]: *** [snortSkydive] Error 2
make[1]: Leaving directory '/root/go/src/github.com/skydive-project/skydive/contrib/snort'
Makefile:187: recipe for target 'contribs' failed
make: *** [contribs] Error 2

root@ERANRA2-TP [233] ~/go/src/github.com/skydive-project/skydive  (master u=)
#
'''

**Comment by safchain** [comment]
I just tested on a fresh install using this script
https://gist.github.com/safchain/c552453869f81d6739f52843925fada5
Could you test it ?

**Comment by safchain** [comment]
No update since awhile closing it for now

**Comment by shadikardosh** [comment]
This is happening to us as well when we try to build the skydive project. the script you posted didn't help (or maybe I didn't understand what it does). can you please help us? we did install all the dependencies as specified here: http://skydive.network/documentation/build and we're working onb Ubuntu.

`unexpected directory layout:
	import path: github.com/jteeuwen/go-bindata
	root: /home/shadikardosh/go/src
	dir: /home/shadikardosh/go/src/github.com/skydive-project/skydive/vendor/github.com/jteeuwen/go-bindata
	expand root: /home/shadikardosh/go/src
	expand dir: /home/shadikardosh/go/src/github.com/skydive-project/skydive/vendor/github.com/jteeuwen/go-bindata
	separator: /
/home/shadikardosh/go/src/github.com/skydive-project/skydive
gofmt -w -s statics/bindata.go
make -C contrib/snort
make[1]: Entering directory '/home/shadikardosh/go/src/github.com/skydive-project/skydive/contrib/snort'
/home/shadikardosh/go/bin/govendor build -o $GOPATH/bin/snort-skydive snortSkydive.go
go build command-line-arguments: /home/shadikardosh/go/pkg/tool/linux_amd64/link: signal: killed
Error: exit status 1
Makefile:11: recipe for target 'snortSkydive' failed
make[1]: *** [snortSkydive] Error 2
make[1]: Leaving directory '/home/shadikardosh/go/src/github.com/skydive-project/skydive/contrib/snort'
Makefile:355: recipe for target 'contribs' failed
make: *** [contribs] Error 2`

I will also mention that the file $GOPATH/bin/snort-skydive snortSkydive.go is not present.

**Comment by safchain** [comment]
I just tested on a fresh ubuntu 18.04 taking the documentation steps which gives the following scripts

```
apt-get install -y git make patch golang findutils protobuf-compiler libprotobuf-dev   npm libpcap0.8-dev libxml2-dev libvirt-dev

mkdir $HOME/go
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$PATH

mkdir -p $GOPATH/src/github.com/skydive-project
git clone https://github.com/skydive-project/skydive.git \
  $GOPATH/src/github.com/skydive-project/skydive
cd $GOPATH/src/github.com/skydive-project/skydive
make
```

It seems that the build as been killed. 
`/home/shadikardosh/go/pkg/tool/linux_amd64/link: signal: killed`.
Is there enough memory ?

BTW the script pointed in this issue is deprecated, I deleted it.

**Comment by shadikardosh** [comment]
Correct! there wasn't enough memory. Thanks a lot!
