### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by safchain** [skydive-project/skydive#679]
Here some idea to improve performances : 

* Be sure of omitempty
  * netlink : DONE
* Rest API gzip compression
  * DONE
* Do not deserialize to pretty print on client side
  * DONE
* Use Protobuf instead of JSON from agent to analyzer communication
  * Step 1 convert first level message, meaning everything except metadata - DONE
  * Step 2 convert well known metadata to protobuf, like metrics, neutron metadata
    * Added a way to convert step by step, metrics already converted.
* Dict based JSON serialization
  * DONE (easyjson)
* WebSocket API compression : gorilla/websocket@a87eae1
  * The performances are worse : WONT FIX
* Schema based Graph
* Lazy loading, first level metadata always returned, second level only by GetNode/GetEdge
* Be sure backend connection uses compression
* Use Murmurhash3

**Comment by eranra** [comment]
Maybe just add as first phase a useful error message after some time-out value to indicate that the amount of data that is required from the back-end is too big. In this case, a user will be able to later get in and choose a filtered view ... the dynamic manner is the right approach ... but maybe first phase to make sure the GUI is always usable is useful here.

**Comment by safchain** [comment]
the goal here is to track idea to improve performances based on metric from pretty large scale deployment. The plan is to first identify what are the bottlenecks and what can be improved for the API, etc and then what can be done for the WebUI.

**Comment by safchain** [comment]
Closing it as most of the points have been addressed. Will open more specific issues to address remaining things.
