### ISSUE TITLE
Neutron: tap nodes can not update automatically

### ISSUE THREAD

**Issue by zhuzeyu** [skydive-project/skydive#687]
I add neutron topology in skydive conf, it works well first time
but in following condition, it got something wrong
when I execute "nova stop" to shut down a virtual machine, the tap node will disappear
then I execute "nova start" to power on virtual machine, tap node will rebuild
the new tap node doesn't have neutron topology

**Comment by zhuzeyu** [comment]
hi  safchain，i think this is different from #690,
this one shows that when we start skydive correctly, the tap node can not update automatically

#690 shows that if vm is SHUTOFF, the neutron topology of skydive will be error with qvb and qbr node

**Comment by safchain** [comment]
Thanks for re-open it if you thought it was different. I'll have a look at both. I saw that you submitted a fix for the other one I'll have a look at it too.
