### ISSUE TITLE
skydive client inject-packet and "All the parms not set properly"

### ISSUE THREAD

**Issue by esnible** [skydive-project/skydive#726]
When I do `skydive client inject-packet --src="G.V().Has('TID', '57c83106-174f-5565-7d60-d7f3d2c19b6e')" --dst="G.V().Has('TID', '99642be1-868e-5545-652c-0395bca6f38b')" --type="icmp" --count=15` the output is "400 Bad Request: All the parms not set properly"

If I leave off the `--type="icmp"`, it works.  (I think I should have used icmp4 instead of icmp.  The documentation doc/content/use-cases/packet-injector.md uses `--type="icmp"` as the syntax example.)

I am running on a Vagrant VM.  The source is a the eth0 on that VM; the target is the eth0 on a Docker container instance on that same VM.

The ideal fix would cause the server sending the 400 to be more explicit about which param is not set properly.  It is possible the HTTP code should not be 400 but instead 403 forbidden meaning the server understood the request but that it is impossible to inject on the source or target with the type.

**Comment by masco-enovance** [comment]
https://github.com/skydive-project/skydive/pull/736

**Comment by esnible** [comment]
Consider putting a correct example in _documentation doc/content/use-cases/packet-injector.md_ as part of this fix.  The example uses `--type="icmp"`

**Comment by masco-enovance** [comment]
@esnible complete docs update is in different patch https://github.com/skydive-project/skydive/pull/734
