### ISSUE TITLE
Sort order for flow numeric columns weird

### ISSUE THREAD

**Issue by lindhor** [skydive-project/skydive#804]
If you click the column label under the flow query table to sort the flows by that column, the sort order is a bit weird for numeric fields like AB/BA Packets/Bytes. It seems to treat the values like text instead of numbers, causing the order to be wrong.

For example:
1
1000
2
300

Instead of the natural
1
2
300
1000

**Comment by lindhor** [comment]
Just noticed that the sort order for ports in the Conversation view suffers from the same problem (when selecting TCP or UDP).

**Comment by masco-enovance** [comment]
fix for conversation order issue: https://github.com/skydive-project/skydive/pull/815
