### ISSUE TITLE
Capture and export full packets

### ISSUE THREAD

**Issue by lindhor** [skydive-project/skydive#805]
It would be very cool to be able to select to capture full packets incl. payload. If implemented it would be even cooler to be able to drill down in the details similar to Wireshark.

It also would be nice to be able to export captures in formats like .pcap so that they can be analysed with other tools. And possibly even have a way to forward captured packets live to other tools like Snort/Wireshark etc. This kind of functionality would centralised network analysis extremely powerful.

**Comment by lebauce** [comment]
@lindhor It is possible to capture full packets, including payloads. When you create a capture from the Web UI, there is an "Advanced options" dropdown that allows you to specify the "Raw packets limit".

There is even a tiny button in the "Flows" panel that would directly open them with Wireshark.

Right now, only 10 captures can be captured, but that is not a technical limitation.

**Comment by lindhor** [comment]
Thanks for the quick reply! That feature you describe is great, but was really well hidden ;-)
After I changed the Raw Packets Limit under Advanced, I found a button to download a capture next to the RawPacketsCaptured field shown after selecting a specific flow. I guess that's the button you mention? Is there some way to download the whole capture, not just for a single flow?

Unfortunately, in my setup nothing happens when pressing the download button and I see the following in the browser console (I see no errors in the server side log, the same is true for the two "chain" buttons next to ANodeTID and BNodeTID which I don't know what they are used for)
```
POST http://localhost:8082/api/topology 404 (Not Found)
$downloadRawPackets @ api.js:61
n @ vue.min-2.1.9.js:6
onClick @ flow-table.js:642
invoker @ vue.min-2.1.9.js:6
api.js:61 POST http://localhost:8082/api/topology 400 (Bad Request)
$downloadRawPackets @ api.js:61
n @ vue.min-2.1.9.js:6
xhr.onload @ api.js:16
XMLHttpRequest.send (async)
$downloadRawPackets @ api.js:61
n @ vue.min-2.1.9.js:6
onClick @ flow-table.js:642
invoker @ vue.min-2.1.9.js:6
```
Do you by any chance have any idea what could be the reason for this? Using `curl -X POST -d '{"GremlinQuery":"G.V()"}'  http://localhost:8082/api/topology` I do get data back.

I have tried Safari, Chrome and Firefox with the same results. Could it be something in my server setup causing this? My test environment uses Skydive 0.16.0 and run in Docker on CentOS 7.4. Or is there some other setting that could cause this behaviour?

**Comment by lindhor** [comment]
Found the problem. I had firewall issues between agent and analyser that stopped flows being sent via udp. After fixing this I get the download button to work. Now I'm happy! VERY good feature!

**Comment by lebauce** [comment]
@lindhor Glad it helped. By the way, you can use WebSocket instead of UDP by setting the `flow.protocol` configuration value to `websocket`.
