### ISSUE TITLE
Drill down from conversion to discovery and opposite

### ISSUE THREAD

**Issue by lindhor** [skydive-project/skydive#806]
It would be nice if the matrix in the conversation mode was clickable so that it was possible to jump to discovery mode. I.. use the selected address pairs in Conversation mode as a filter to Discovery mode, showing the protocols being sent between the two selected addresses. I guess this currently makes sense only for Ethernet and IP layers.

In a similar way it would make sense to be able to click on a arc in the Discovery mode and just to a filtered Conversation mode showing which addresses that generated the traffic.

If this is implemented it would also make sense to be able to jump from a selected node in Topology view to the Conversation and Discovery views, to see who the selected node has communicated with and what protocols are being used.

**Comment by safchain** [comment]
Closing as these views have been removed
