### ISSUE TITLE
Support for Elasticsearch 6.x

### ISSUE THREAD

**Issue by lindhor** [skydive-project/skydive#811]
In Elasticsearch 6.x Content-Type header is required for all requests received. See https://www.elastic.co/blog/strict-content-type-checking-for-elasticsearch-rest-requests

Sending Content-Type for all requests to Elasticsearch is not supported by elastigo, the library Skydive currently uses.

Unfortunately, elastigo seems more or less deserted. Possibly https://github.com/olivere/elastic should be used instead. See https://github.com/mattbaird/elastigo/issues/297

**Comment by safchain** [comment]
fixed: #1098
