### ISSUE TITLE
Add "or" predicate to match multiple metadata field 

### ISSUE THREAD

**Issue by safchain** [skydive-project/skydive#835]

**Comment by masco-enovance** [comment]
Could you please add a sample query. Thanks!

**Comment by safchain** [comment]
It's more a step I think than a predicate, something like this

http://gremlindocs.spmallette.documentup.com/#or

This is related to this PR too: #426

**Comment by lebauce** [comment]
Now that we have As/Select, do you think we can close it ?

**Comment by safchain** [comment]
@lebauce it is more about doing something G.V().Has(Or('MTU', 1500, 'IPv4', '192.168.0.'))

**Comment by safchain** [comment]
fixed: #1398
