### ISSUE TITLE
Select flows collected by specific named capture

### ISSUE THREAD

**Issue by lindhor** [skydive-project/skydive#837]
Is it possible, or would it be possible to add functionality, to write a gremlin query selecting all flows that has been collected by a specific capture? I would like something like G.Flows().Has('CaptureName','NameOfMyCapture').

The reason is that I want to be able to use Grafana with the Skydive datasource. In that case I would like to have a capture with a *fixed* name that can be configured in the Grafana dashboard. In this situation I do not want the dashboard to see flows captured by other captures started, even if they are collected by the same agent on the same interface.

My scenario is that I want to be able to use Grafana amount of captured traffic of different TCP/UDP ports based on predefined network interfaces. Without limiting the flows returned to Grafana to the selected capture, I will not get reliable graphs when users add/remove captures for other purposes. I also need to be able to use a fixed name rather than a generated GUID identifying the capture in the query to avoid having to change the Grafana dashboard definition (after recreating the capture or connecting to another skydive analyzer).

In the long run I would even prefer to be able to "lock" or hide the Grafana capture, so that it is not modified or deleted by mistake...

**Comment by safchain** [comment]
That's possible, let say you created a capture with the following gremlin expression

```
G.V().Has('Name', 'test123')
```

In order to get the flows just add the `Flows()` step like this:

```
G.V().Has('Name', 'test123').Flows()
```

**Comment by lindhor** [comment]
Well, that might work in some cases, but what I really would like is to "decouple" the gremlin capture expression from the Grafana query so that I will not need to change the Dashboard query each time we decide to change the capture rule. If I understand it correctly, your suggestion would not do that for me? I.e. 'test123' would be the node name (interface) which the capture was started and if I decide to change the capture to something like `G.V().Has('Name', RegEx('etc.*'))` I would have to change the dashboard to the same expression as well. That's the reason why I would like a Gremlin query to be able to get flows by the capture name itself, rather than repeating the capture query + `.flows()`.

**Comment by safchain** [comment]
This fix should help https://github.com/skydive-project/skydive/pull/845

**Comment by lindhor** [comment]
Thank you for really quick support! Can confirm that it works using queries like `G.V().has('Capture.ID','8d872abe-4a39-4556-6b52-2b4f104b181c').Flows()` or `G.V().has('Capture.Name','MyCapture').Flows()`
