### ISSUE TITLE
Skydive at my ICP v2101

### ISSUE THREAD

**Issue by eranra** [skydive-project/skydive#839]
From: chingl@hk1.ibm.com

I have installed Skydive at my ICP v2101. At the first time, I can see the topology. After a while, I cannot get any topology again, just blank screen.
If I delete all skydive pods again, it will come out again… But, after a while, the topology will be disappeared again.
Any thought on it?

ERAN: Can you share logs from those pods (execute kubectl logs <pod_name>). Also, did you had to restart the Analyzer pod, the Agent pods or all ?

**Comment by safchain** [comment]
Eran, can we close this one ? any news on this ?

**Comment by eranra** [comment]
No more details, closing
