### ISSUE TITLE
flows: Decoding Failure (flow/flow.go)

### ISSUE THREAD

**Issue by vperelmax** [skydive-project/skydive#852]
We have revealed in the environment of K8S some packets reporting Decoding failure (from try to decode externally it looks like DNS request).
Here is the raw packet example:
******************************************
00000000  f5 b9 81 80 00 01 00 04  00 00 00 00 10 73 65 63  
00000010  75 72 69 74 79 2d 61 64  76 69 73 6f 72 08 75 73  
00000020  2d 73 6f 75 74 68 07 62  6c 75 65 6d 69 78 03 6e
00000030  65 74 00 00 1c 00 01 c0  0c 00 05 00 01 00 00 05  
00000040  70 00 33 10 73 65 63 75  72 69 74 79 2d 61 64 76  
00000050  69 73 6f 72 08 75 73 2d  73 6f 75 74 68 07 62 6c  
00000060  75 65 6d 69 78 03 6e 65  74 07 65 64 67 65 6b 65  
00000070  79 03 6e 65 74 00 c0 43  00 05 00 01 00 00 2f 58  
00000080  00 1e 06 65 31 33 35 32  34 06 64 73 63 6b 73 64  
00000090  0a 61 6b 61 6d 61 69 65  64 67 65 03 6e 65 74 00  
000000a0  c0 82 00 1c 00 01 00 00  00 05 00 10 20 01 05 59  
000000b0  00 13 01 82 00 00 00 00  00 00 34 d4 c0 82 00 1c  
000000c0  00 01 00 00 00 05 00 10  20 01 05 59 00 13 01 83  
000000d0  00 00 00 00 00 00 00 00
************************************************
You can see its interpretation of the packet here:
https://www.gasmi.net/hpd/

**************************************************************************************
In Debug we get in the Logs of agent the following output:
2018-03-13T09:38:04.158Z        DEBUG   flow/flow.go:791 PacketSeqFromGoPacket  kube-dal10-cr6661a3c5d333452ab4dd6a01db17b9a7-w3.cloud.ibm: -- FULL PACKET DATA (256 bytes) ------------------------------------
00000000  72 f1 cb e9 6e d6 ee ee  ee ee ee ee 08 00 45 00  |r...n.........E.|
00000010  00 f4 aa 48 40 00 3f 11  4b d0 ac 15 00 0a ac 1e  |...H@.?.K.......|
00000020  ec a2 00 35 d4 e8 00 e0  45 d2 f5 b9 81 80 00 01  |...5....E.......|
00000030  00 04 00 00 00 00 10 73  65 63 75 72 69 74 79 2d  |.......security-|
00000040  61 64 76 69 73 6f 72 08  75 73 2d 73 6f 75 74 68  |advisor.us-south|
00000050  07 62 6c 75 65 6d 69 78  03 6e 65 74 00 00 1c 00  |.bluemix.net....|
00000060  01 c0 0c 00 05 00 01 00  00 05 70 00 33 10 73 65  |..........p.3.se|
00000070  63 75 72 69 74 79 2d 61  64 76 69 73 6f 72 08 75  |curity-advisor.u|
00000080  73 2d 73 6f 75 74 68 07  62 6c 75 65 6d 69 78 03  |s-south.bluemix.|
00000090  6e 65 74 07 65 64 67 65  6b 65 79 03 6e 65 74 00  |net.edgekey.net.|
000000a0  c0 43 00 05 00 01 00 00  2f 58 00 1e 06 65 31 33  |.C....../X...e13|
000000b0  35 32 34 06 64 73 63 6b  73 64 0a 61 6b 61 6d 61  |524.dscksd.akama|
000000c0  69 65 64 67 65 03 6e 65  74 00 c0 82 00 1c 00 01  |iedge.net.......|
000000d0  00 00 00 05 00 10 20 01  05 59 00 13 01 82 00 00  |...... ..Y......|
000000e0  00 00 00 00 34 d4 c0 82  00 1c 00 01 00 00 00 05  |....4...........|
000000f0  00 10 20 01 05 59 00 13  01 83 00 00 00 00 00 00  |.. ..Y..........|
--- Layer 1 ---
Ethernet        {Contents=[..14..] Payload=[..242..] SrcMAC=ee:ee:ee:ee:ee:ee DstMAC=72:f1:cb:e9:6e:d6 EthernetType=IPv4 Length=0}
00000000  72 f1 cb e9 6e d6 ee ee  ee ee ee ee 08 00        |r...n.........|
--- Layer 2 ---
IPv4    {Contents=[..20..] Payload=[..222..] Version=4 IHL=5 TOS=0 Length=244 Id=43592 Flags=DF FragOffset=0 TTL=63 Protocol=UDP Checksum=19408 SrcIP=172.21.0.10 DstIP=172.30.236.162 Options=[] Padding=[]}
00000000  45 00 00 f4 aa 48 40 00  3f 11 4b d0 ac 15 00 0a  |E....H@.?.K.....|
00000010  ac 1e ec a2                                       |....|
--- Layer 3 ---
UDP     {Contents=[..8..] Payload=[..214..] SrcPort=53(domain) DstPort=54504 Length=224 Checksum=17874}
00000000  00 35 d4 e8 00 e0 45 d2                           |.5....E.|
--- Layer 4 ---
DecodeFailure   Packet decoding error: resource record length exceeds data
00000000  f5 b9 81 80 00 01 00 04  00 00 00 00 10 73 65 63  |.............sec|
00000010  75 72 69 74 79 2d 61 64  76 69 73 6f 72 08 75 73  |urity-advisor.us|
00000020  2d 73 6f 75 74 68 07 62  6c 75 65 6d 69 78 03 6e  |-south.bluemix.n|
00000030  65 74 00 00 1c 00 01 c0  0c 00 05 00 01 00 00 05  |et..............|
00000040  70 00 33 10 73 65 63 75  72 69 74 79 2d 61 64 76  |p.3.security-adv|
00000050  69 73 6f 72 08 75 73 2d  73 6f 75 74 68 07 62 6c  |isor.us-south.bl|
00000060  75 65 6d 69 78 03 6e 65  74 07 65 64 67 65 6b 65  |uemix.net.edgeke|
00000070  79 03 6e 65 74 00 c0 43  00 05 00 01 00 00 2f 58  |y.net..C....../X|
00000080  00 1e 06 65 31 33 35 32  34 06 64 73 63 6b 73 64  |...e13524.dscksd|
00000090  0a 61 6b 61 6d 61 69 65  64 67 65 03 6e 65 74 00  |.akamaiedge.net.|
000000a0  c0 82 00 1c 00 01 00 00  00 05 00 10 20 01 05 59  |............ ..Y|
000000b0  00 13 01 82 00 00 00 00  00 00 34 d4 c0 82 00 1c  |..........4.....|
000000c0  00 01 00 00 00 05 00 10  20 01 05 59 00 13 01 83  |........ ..Y....|
000000d0  00 00 00 00 00 00                                 |......|

**Comment by safchain** [comment]
So not a real parsing error except that skip the whole packet even if the first layers were OK. As I'm rewriting the flow parsing thing, I'm going to not ignore them anymore.

**Comment by safchain** [comment]
fixed: #904
