### ISSUE TITLE
flow: Unable to Decode LinkType 12 (TUN packets) 

### ISSUE THREAD

**Issue by vperelmax** [skydive-project/skydive#853]
It seems that in gopacket parsing of TUN packets requires some workaround.
Similar discussion of the problem says that the error that we see is related to using  TUN interface, where the first layer to decode is an IP layer and then gopacket doesnt treat it in normal parsing flow but there exists trick to treate it.
Here is the link explaining the issue and the solution: https://github.com/google/gopacket/issues/99

Example log of failure while decoding such packet.:
--- Layer 1 ---
DecodeFailure   Packet decoding error: Unable to decode LinkType 12
00000000  45 00 05 76 37 b9 40 00  3f 06 8a 80 0a ab a9 f3  |E..v7.@.?.......|
00000010  c0 a8 ff 01 28 0a a1 24  d5 f3 d6 c1 44 ee 1a 59  |....(..$....D..Y|
00000020  80 10 01 28 f6 24 00 00  01 01 08 0a 1c 82 9f 11  |...(.$..........|
00000030  2a 19 e9 97 9e 33 6f 60  3d 68 81 33 17 87 1d a4  |*....3o`=h.3....|
00000040  22 84 61 ca 27 66 49 c8  59 4d 93 17 a8 ca a9 55  |".a.'fI.YM.....U|
00000050  d8 a8 77 84 49 2b e2 ad  12 e7 a7 d1 1f 5a b6 ba  |..w.I+.......Z..|
00000060  9e 2b d1 c1 0e f1 fa 15  3c 5a 15 c7 65 05 ff bc  |.+......<Z..e...|
00000070  f9 c2 58 a0 76 23 53 04  b5 e1 c3 28 5b ee 02 63  |..X.v#S....([..c|
00000080  2b b8 79 46 69 f5 43 6a  22 1a 4e 87 6e 90 df 20  |+.yFi.Cj".N.n.. |
00000090  3c 1f 25 42 b9 3f 0d 70  04 20 a3 bf 6d 69 97 54  |<.%B.?.p. ..mi.T|
000000a0  c1 8d 7c f8 c6 c9 aa 24  0a 88 2e ed f8 18 e4 37  |..|....$.......7|
000000b0  93 e9 be 81 71 e3 9f 33  8a e9 17 03 03 00 f7 00  |....q..3........|
000000c0  00 00 00 00 01 65 04 37  05 28 61 90 87 0e e7 74  |.....e.7.(a....t|
000000d0  f6 7c 1e fe 46 5e 33 86  94 b4 16 c4 de c2 30 f6  |.|..F^3.......0.|
000000e0  02 1e 56 bd fe 54 6a 0d  da e6 03 34 e3 f9 19 14  |..V..Tj....4....|
000000f0  f8 e3 92 f2 3f 69 e1 02  86 17 b8 3d 96 13 0e a7  |....?i.....=....|

**Comment by nplanel** [comment]
The kernel report LinkType 12 as #define DLT_RAW		12	/* raw IP */

In Skydive if you use gopacket capture probe, this should work as we use getGoPacketFirstLayerType() to find the first layer based on the encap link type.

**Comment by safchain** [comment]
fixed: #991
