### ISSUE TITLE
ShortestPathTo() result is alternating (triggering continuous changes on UI)

### ISSUE THREAD

**Issue by hunchback** [skydive-project/skydive#856]
As was reported by Eran:

We saw some strange behavior that caused icons to "jump" on the screen ... the investigation resulted with the understanding that  shortest path is inconsistent.

```
$ ./skydive client --analyzer 9.4.193.143:32501 query "G.V().Has('TID','ee3ec713-4904-5195-5151-350c6f48331d').ShortestPathTo(Metadata('Name','TOR1'))" | grep -e "\"Name"
                               "Name": "eth0",
                               "Name": "calib7df92e53e7",
                               "Name": "think-worker1",
                               "Name": "eth0",
                               "Name": "TOR1",

stack@SkyEran [1597] ~/go/bin
$ ./skydive client --analyzer 9.4.193.143:32501 query "G.V().Has('TID','ee3ec713-4904-5195-5151-350c6f48331d').ShortestPathTo(Metadata('Name','TOR1'))" | grep -e "\"Name"
                               "Name": "eth0",
                               "Name": "k8s_istio-proxy_productpage-v1-958623182-qdbrx_default_e643d311-18be-11e8-8fb6-06a24af7a53d_0",
                               "Name": "think-worker1",
                               "Name": "eth0",
                               "Name": "TOR1",
```

I assume that this is due to the order of the golang array returned that is not ordered (or something like that). Also, both paths are equal in length (=5 hops). If I remember correctly,  we said in the path that we will return ALL paths ... so, was that changed ? and if so, is there a way to get both and somehow dedupe ?

**Comment by safchain** [comment]
This can causes UI filtering inconsistency

**Comment by safchain** [comment]
I think the best approach is to return all the path, then adding a better way to filter

**Comment by safchain** [comment]
I will work on that

**Comment by lebauce** [comment]
@safchain Can we close this one ?

**Comment by hunchback** [comment]
closing
