### ISSUE TITLE
Use analyzers address when no etcd parameter provided

### ISSUE THREAD

**Issue by safchain** [skydive-project/skydive#86]
Currently we have to set the etcd servers parameter is the config file even if we are using the embed etcd. It would be better to use the analyzers list as etcd servers list when this list is not specified is the config file.

**Comment by masco-enovance** [comment]
http://softwarefactory-project.io/r/#/c/4628/

**Comment by masco-enovance** [comment]
the patch is merged successfully. closing the issue.
