### ISSUE TITLE
Viper not supporting Boolean variables from environment variable

### ISSUE THREAD

**Issue by vperelmax** [skydive-project/skydive#860]
Viper not supporting Boolean variables from environment variable.
The possible solution currently we use internally is to pass strings...

**Comment by lebauce** [comment]
I tested with etcd.embedded (SKYDIVE_ETCD_EMBEDDED=true), it worked. What variable are you testing with ?

**Comment by lebauce** [comment]
@vperelmax Can you please take an other look ?

**Comment by lebauce** [comment]
Closing it. Feel free to reopen it if the problem still occurs
