### ISSUE TITLE
Add Auth support to python RESTClient

### ISSUE THREAD

**Issue by safchain** [skydive-project/skydive#901]

**Comment by snapiri** [comment]
Currently when trying to use the RESTClient, no authentication is done with the analyzer, thus we get 'HTTPError: HTTP Error 401: Unauthorized' error.
Even after adding the authentication cookie I got from another login session, I still get a 'HTTPError: HTTP Error 400: Bad Request' error.
The request item after adding the cookie:
{'_Request__original': 'http://192.168.33.201:8082/api/topology', 'data': '{"GremlinQuery": "G.E().Has(\'source\': \'dragonflow\')"}', '_tunnel_host': None, 'host': None, 'origin_req_host': '192.168.33.201', 'headers': {'Content-type': 'application/json', 'Cookie': 'authtok=gAAAAABat1B09a_OJ9JtPgPpcxE9pdYH3sd88-zQVnfDGJolMAO-31Sjbm8XK0ikikWYeSs2G_QpwqD4DYyZaiWUi9JC9V9P2cmPrUGWiTzmsVBeLXibe-RcAvXO_GKdX3rnvoqtPdH1ha4_9Y-9WsdSgx4CxpWty65swlrwXtHSf6OOyDkjYyw'}, '_Request__fragment': None, 'unredirected_hdrs': {}, 'unverifiable': False, 'type': None, 'port': None}
The stack trace:
CRITICAL neutron [-] Unhandled error: HTTPError: HTTP Error 400: Bad Request
ERROR neutron Traceback (most recent call last):
...
ERROR neutron   File "/opt/stack/dragonflow/dragonflow/cmd/df_skydive_service.py", line 71, in clear_dragonflow_items
ERROR neutron     edges = restclient.lookup_edges("G.E().Has('source': 'dragonflow')")
ERROR neutron   File "/usr/local/lib/python2.7/dist-packages/skydive/rest/client.py", line 59, in lookup_edges
ERROR neutron     return self.lookup(gremlin, Edge)
ERROR neutron   File "/usr/local/lib/python2.7/dist-packages/skydive/rest/client.py", line 47, in lookup
ERROR neutron     resp = request.urlopen(req)
ERROR neutron   File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
ERROR neutron     return opener.open(url, data, timeout)
ERROR neutron   File "/usr/lib/python2.7/urllib2.py", line 435, in open
ERROR neutron     response = meth(req, response)
ERROR neutron   File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
ERROR neutron     'http', request, response, code, msg, hdrs)
ERROR neutron   File "/usr/lib/python2.7/urllib2.py", line 473, in error
ERROR neutron     return self._call_chain(*args)
ERROR neutron   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
ERROR neutron     result = func(*args)
ERROR neutron   File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
ERROR neutron     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
ERROR neutron HTTPError: HTTP Error 400: Bad Request
ERROR neutron

**Comment by safchain** [comment]
ongoing work : #905
