### ISSUE TITLE
flow: creating more general structure that will enable reporting on flows/topology data to a third party

### ISSUE THREAD

**Issue by vperelmax** [skydive-project/skydive#906]
Some clients prefer using SkyDive system rather as a system for analysis and monitoring (without UI).
What they need is the ability to subscribe and receive report including flows/topology in their specific format/using different policies also on conditions in which they should receive the data.
Currently to enable this it is possible for example to add new flow storage entities that instead of storing elements in ES or other DB actually send the data to a client pre-defined endpoint after formatting it in the required way.
I find it useful to create more pluggable system enabling adding more general mechanism to support such clients.

**Comment by safchain** [comment]
One can also subscribe to the graph in order to get notifications. One can use the python client library for that ?
https://pypi.python.org/pypi/skydive-client/

**Comment by safchain** [comment]
There are examples here : 
https://github.com/skydive-project/skydive/blob/master/contrib/python/api/samples/inject-nodes1.py
https://github.com/skydive-project/skydive/blob/master/contrib/python/api/skydive/wsshell.py

**Comment by vperelmax** [comment]
Hi, it is not exactly what we wanted to do, I am closing the issue for the meantime, Lets discuss it first.
