### ISSUE TITLE
Issues installing Skydive in Ubuntu 17.10 VM

### ISSUE THREAD

**Issue by sheeets** [skydive-project/skydive#925]
I'm trying to setup a test environment for Skydive using VM through VMware. Right now I am working on my monitoring VM that would function as the analyzer for all nodes. I keep getting `permission denied` errors when trying to find `skydive allineone --conf /etc/skydive/skydive.yml`.

This is what the error looks like running with the default skydive configuration file:

```
$ skydive allinone --conf /etc/skydive/skydive.yml
2018-04-03T15:41:03.839-0700    INFO        analyzer/analyzer.go:47 glob..func1 .        skydive: Skydive Analyzer 38f728372871 starting...
2018-04-03 15:41:03.845807  I  |  embed: listening for peers on http://127.0.0.1:12380
2018-04-03 15:41:03.845879  I  |  embed: listening for client requests on 127.0.0.1:12379
Failed to create analyzer: cannot access data directory: open /var/lib/skydive/etcd/.touch: permission denied
```

**Would I be better off just installing docker on all my systems and using a container as the agent?**

**Comment by lebauce** [comment]
@sheeets Are you running `skydive` as root ?

**Comment by sheeets** [comment]
I was having some issues with my environment, and running `go install github.com/skydive-project/skydive` seemed to get it installed properly with the right permissions. 

On a side note, is elasticsearch required for systems that are only running the agent?

**Comment by safchain** [comment]
Elasticsearch is only requiered on analyzer side
