### ISSUE TITLE
move ES unit test to functional test

### ISSUE THREAD

**Issue by nplanel** [skydive-project/skydive#963]
Please move the ElasticSearch unit tests to functional tests, as make test should not bind/create connection(s)

storage/elasticsearch/elasticsearch_test.go
topology/graph/elasticsearch_test.go

to 

tests/elasticsearch_test.go

**Comment by nplanel** [comment]
@eranra @hunchback

**Comment by nplanel** [comment]
@hunchback cool

**Comment by safchain** [comment]
Fixed: #996
