### ISSUE TITLE
ES: Lock-less rollover for ES topology index

### ISSUE THREAD

**Issue by hunchback** [skydive-project/skydive#965]
# Current implementation

We block incoming updates to ES live topology index (all requests building up in golang chan, in memory), the existing live index becomes an archive index and a new live is created and is seeded with the live topology state (measurements by @safchain indicate that even for several 10k of nodes this operation would take only several seconds).

# Issues with current implementation

* Writing to ES is blocked for several seconds: updates entering in this period are not reflected in topology map; a reboot of the system in this period will cause lose of this update events (as chan is only backed by memory) 
* the live map is duplicated again and again in every index, in large slow changing environments this will cause significant waste.

# High level design of alternative implementation

Before deleting the oldest index, move any entries which are required for creating a consistent view.

# Low level design of alternative implementation

 ## topology indexes
 
  * skydive_topology_live_v11 <--- new/updated/deleted topology items go here
  * skydive_topology_archive_v11_2017.04.01  <--- newly archived items go here
  * ...
  * skydive_topology_archive_v11_2018.03.28
  * skydive_topology_archive_v11_2018.03.27
  * skydive_topology_archive_v11_2018.03.26 <--- this index will be deleted during rollover

##   performing CRUD operations on topology

  * CREATE- add new item `to skydive_topology_live`
  * READ - read items from all indecies
  * UPDATE - handle as following:
    * add new item to `skydive_topology_live`
    * create an archived item in skydive_topology_archive set `archivedAt: now`
    * delete old item from `skydive_topology_live` (space not reclaimed at this stage)
  * DELETE - handle as following:
    * create an archived item in skydive_topology_archive set `archivedAt: now; deleted: true`
    * delete old item from `skydive_topology_live` (space not reclaimed at this stage)

##   Index rollover

*  move items `skydive_topology_archive_v11_2018.03.26` with `archiveAt > 2018.03.27` to `skydive_toplogy_archive_v11_2018.04.01`
* once all items above moved you can safely delete `skydive_topology_archive_v11_2018.03.16`

##   Reducing live index size

 *  peridocialy invoke ElasticSearch force merge https://www.elastic.co/guide/en/elasticsearch/reference/6.2/indices-forcemerge.html

**Comment by hunchback** [comment]
> from which information/version of the element you are going to create the archived entry ? 

We create the archived version from the previous live entry for example if I had node A which was replaced at time 13:45 by A' then A' is added to the live index and I move A {archivedAt: 13;45} to the archive index.

> does this mean that we need first to retrieve it ? 

No. following the example above - the old entry A exists in memory

> currently it is an update so that only the archivedAt is set meaning no need to retrieve the previous version. So is it an partial update or an insert ?
 
Its' an insert of A to the archive index and a partial update A --> A' in the live index

> if we have archived entries in skydive_topology_archive why do we need to delete something in the live index ?

All entries and some point in time move through the live index (weather we do an update replacing old version with new or delete an entry) we need to delete entries in the live which are no longer part of the current/live topology. 

> everything we will have in the live index will be alive ?
 
Correct, but while ES supports delete, reclaiming the space is done calling `forcemerge`

**Comment by safchain** [comment]
> No. following the example above - the old entry A exists in memory
If fact this is not true, at the ES stage the element as already been replaced. That's why the current approach is to update the previous element setting the archivedAt field and to create a new record for the current version of the element.

**Comment by safchain** [comment]
or we need to do it by using an elasticsearch request to move old entry from live to archived

**Comment by hunchback** [comment]
So what would be needed on getting an update for now A --> A'
* create an entry in archive with A + archivedAt
* delete the old entry A from live
* insert new entry A' into live

Please confirm

**Comment by hunchback** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html we can use reindex introduced in ES 2.3.

**Comment by eranra** [comment]
@hunchback et al, I am sharing some information on one of the ways we did that process in the past. look on https://patents.google.com/patent/US20130325810A1/en?oq=US20130325810A1

The "DETAILED DESCRIPTION" is written in "normal English" so hopefully readable.

**Comment by safchain** [comment]
fixed #1098.

We will re-open it if needed to improve the approach.
