### ISSUE TITLE
Group Openflow rules by priority and actions

### ISSUE THREAD

**Issue by pierrecregut** [skydive-project/skydive#970]
Long lists of rules can be hard to read. A first step would be to group them by priority and for a given priority by actions. Rules of a given subgroup would only be distinguishable by the filters (it should be read as a disjunction). 

Here is a table taken from an vswitch controlled by openstack/ovn with the current style: 
![old_layout](https://user-images.githubusercontent.com/7011215/38995030-39aef7aa-43e8-11e8-980d-c212ace8b3e8.png)

Here is the same with the new slightly more structured style:
![new-layout](https://user-images.githubusercontent.com/7011215/38995114-7aee724a-43e8-11e8-9638-1df01b781f5c.png)

**Comment by nplanel** [comment]
pretty nice :+1:  ordering by priority made it clearly more readable.
Adding an alphabetical order on the filters column, would be even better to read/find the rule easily.
