### ISSUE TITLE
use an API for OpenFlow communication 

### ISSUE THREAD

**Issue by nplanel** [skydive-project/skydive#975]
don't parse the output commandline

**Comment by nplanel** [comment]
if /usr/bin/ovs-ofctl didn't exist in docker image, OpenFlow probe can't monitor bridge

**Comment by safchain** [comment]
maybe this : https://github.com/superkkt/cherry

**Comment by lebauce** [comment]
https://github.com/lebauce/skydive/tree/openflow-gopacket

**Comment by safchain** [comment]
Fixed: #1474
