### ISSUE TITLE
Default filter (ui.topology.default_highlight) not applied

### ISSUE THREAD

**Issue by eranra** [skydive-project/skydive#986]
When using ```ui.topology.default_highlight``` to start the UI with specific filter the view is not always starting with the selected filtered view. 

The ```filter``` text box is propagated correctly with the Filter as expected, but the view itself (topology UI) is showing the complete none-filtered topology

This behavior is _not consistent_ and in some cases the UI does open with filtered view as expected. In my tests I saw that this abnormal behavior happens more on large environments.

**Comment by safchain** [comment]
Closing it for now as it seems it has been fixed recently
