### ISSUE TITLE
Reenable devstack job

### ISSUE THREAD

**Issue by lebauce** [skydive-project/skydive#99]

**Comment by matrohon** [comment]
using http://softwarefactory-project.io/r/#/c/4520/2 worked for me.
I Think keystone V3 is enabled by default in devstack now.

**Comment by matrohon** [comment]
I was wrong devstack doesn't use keystone v3 by default.
The error seems to come from the fact that the auth cookie is missing in "/api/" requets, while it is present in "/api/capture" requests.

I keep on investigating....

**Comment by lebauce** [comment]
http://softwarefactory-project.io/r/3474
