### ISSUE TITLE
Extend flow parsing to support network protocol such as DNS, DHCP, ARP etc...

### ISSUE THREAD

**Issue by eranra** [skydive-project/skydive#997]
1. Add support in capturing process BPF/eBPF to restrict capturing to specific types of protocols (e.g. DNS)
2. Add configuration to specify required (list) of extend flow protocols to parse
3. Extend Flow data structure to support extended flow protocol information *(similar to what was done to add raw packets)
4. Use gopacket to parse and append as needed to flow data (can be extended in the future to more protocols and 3rd parties beyond gopacket)
5. Validate / extend support in saving and retrieving from persistent storage 
6. UI support (as needed)?

**Comment by lebauce** [comment]
https://github.com/skydive-project/skydive/pull/1360
